apache/maven

- apache-maven/src/bin/mvn
- apache-maven/src/bin/mvnDebug
- apache-maven/src/bin/mvnyjp
This fixes the /usr/libexec/java_home choser (OSX) for the main script and adds the missing section to the other tows (ASF Commiter Signoff: ecki)
> [MNG-5686] Use /usr/libexec/java_home to find JAVA_HOME

- maven-model-builder/pom.xml
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- I don't like this, but it does let all the integration tests pass:
```
Running org.apache.maven.it.MavenITmng2199ParentVersionRangeTest
mng2199ParentVersionRange(ValidParentVersionRangeWithInclusiveUpperBound)OK (3.7 s)
mng2199ParentVersionRange(ValidParentVersionRangeWithExclusiveUpperBound)OK (1.7 s)
mng2199ParentVersionRange(InvalidParentVersionRange)........OK (0.7 s)
mng2199ParentVersionRange(ValidParentVersionRangeInvalidVersionExpression)OK (0.5 s)
mng2199ParentVersionRange(ValidParentVersionRangeInvalidVersionInheritance)OK (0.4 s)
mng2199ParentVersionRange(ValidLocalParentVersionRange).....OK (0.4 s)
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.509 sec - in org.apache.maven.it.MavenITmng2199ParentVersionRangeTest
Running …
```
> [MNG-5840] Parent version is a range hack

- maven-embedder/src/test/java/org/apache/maven/cli/transfer/FileSizeFormatTest.java
I noticed that there seem to be some misspellings in the test names in this test class (along with some similar misspellings in local variable names), and so this pull request simply addresses those misspellings.
> Fixing misspellings in test names (Progessed to Progressed)

- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
Idea is to let the user identify how many modules are still to be executed/processed
> [MNG-6302] logging the module count

- maven-model-builder/pom.xml
- maven-model-builder/src/test/java/org/apache/maven/model/inheritance/DefaultInheritanceAssemblerTest.java
- maven-model-builder/src/test/resources/poms/inheritance/plugin-configuration-expected.xml
- pom.xml
Small change only for maven-model-builder but lib later can be used by other modules
https://github.com/xmlunit/user-guide/wiki/DiffBuilder
> [MNG-6479] Upgrade XMLUnit to 2.2.1

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/FileModelSource.java
- maven-model-builder/src/test/java/org/apache/maven/model/building/FileModelSourceTest.java
- pom.xml
> [MNG-6261] - using java File api to compare

- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java
- maven-core/src/test/resources/projects/basic-resolveDependencies.xml
This adds a (failing) unit test showcasing that ProjectBuilder.build(List<File> projects, boolean, ProjectBuildingRequest) doesn't honor ProjectBuildingRequest.isResolveDependencies().
And then it adds a fix that turns the test green.
If your pull request is about ~20 lines of code …
> MNG-6529 - ProjectBuild.build(projectsList, ...) ignores request.isResolveDependencies()

- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- maven-core/src/test/java/org/apache/maven/project/MavenProjectTest.java
[MNG-6405](https://issues.apache.org/jira/browse/MNG-6405) since https://github.com/mojohaus/flatten-maven-plugin/issues/53#issuecomment-447826001 brought this up again. I have not received any hints on the proper approach to test this.
-----
By the way
Is this not already done by the `Jenkinsfile`? Maybe an obsolete PR template.
> [MNG-6405] Fix basedir in MavenProject.deepCopy

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
> [MNG-6655] Add support for "release" qualifier

- maven-core/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuilder.java
- maven-core/src/main/java/org/apache/maven/toolchain/io/DefaultToolchainsWriter.java
- maven-core/src/main/java/org/apache/maven/toolchain/io/ToolchainsWriter.java
- maven-core/src/test/java/org/apache/maven/toolchain/building/DefaultToolchainsBuilderTest.java
- pom.xml
Submitted by: Mike Mol and Martin Kanters
To make clear that you license …
> [MNG-6665] toolchain.xml file should support environment variables

- maven-model/src/main/mdo/maven.mdo
removed misleading "While it usually represents the extension on the filename of the dependency, that is not always the case. A type can be mapped to a different extension and a classifier. The type often corresponds to the packaging used, though this is also not always the case."
> MNG-6681 dependency type = extension+classifier

- maven-core/src/main/java/org/apache/maven/artifact/resolver/filter/ExclusionArtifactFilter.java
- maven-core/src/test/java/org/apache/maven/artifact/resolver/filter/ExclusionArtifactFilterTest.java
> [MNG-6713] Fix ExclusionArtifactFilter to respect wildcard exclusions.

- maven-model-builder/pom.xml
- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/StringSearchModelInterpolator.java
- maven-model-builder/src/test/java/org/apache/maven/model/interpolation/StringSearchModelInterpolatorTest.java
- pom.xml
The current implementation of `StringSearchModelInterpolator` introspects Java objects, e.g. `java.io.File`. This fix stops introspecting such objects. See the unit test `testNotInterpolateFile`.
We found this issue when our build process failed with this warning on the console output:
```
junit.framework.AssertionFailedError: expected:<[]> but was:<[WARNING: An illegal reflective access operation has occurred, WARNING: Illegal reflective access by org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction$CacheField (file:/home/jenkins/jenkins-slave/workspace/ven-box_maven_removed-java-tools/test/core-it-suite/target/apache-maven/lib/maven-model-builder-3.6.2-SNAPSHOT.jar) to field java.io.File.fs, WARNING: Please consider reporting this to the maintainers …
```
> [MNG-6729] StringSearchModelInterpolator introspects objects from Java API

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/VersionRange.java
- maven-compat/src/main/java/org/apache/maven/artifact/resolver/DebugResolutionListener.java
- maven-core/src/main/java/org/apache/maven/artifact/repository/MavenArtifactRepository.java
- maven-core/src/main/java/org/apache/maven/artifact/resolver/filter/ScopeArtifactFilter.java
- maven-core/src/main/java/org/apache/maven/plugin/CacheUtils.java
- maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginDescriptorCache.java
- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- maven-core/src/main/java/org/apache/maven/project/artifact/DefaultMavenMetadataCache.java
- maven-core/src/main/java/org/apache/maven/toolchain/DefaultToolchain.java
use utility method ( Objects.equals ) to rewrite some equals logic in code base.
> [refactor] use utility method of Objects to simplify code

- maven-embedder/src/main/java/org/apache/maven/cli/ResolveFile.java
https://builds.apache.org/job/maven-box/job/maven/job/MNG-6520
> [MNG-6071] Normalize relative paths for working directory

- apache-maven/pom.xml
- maven-compat/pom.xml
- maven-core/pom.xml
- maven-embedder/pom.xml
- pom.xml
Signed-off-by: olivier lamy <olamy@apache.org>
To make clear that you …
> [MNG-6886] upgrade plexus-cipher to 1.8 and update changed groupId

- maven-core/src/main/java/org/apache/maven/ReactorReader.java
- maven-core/src/main/java/org/apache/maven/execution/MavenSession.java
- maven-core/src/main/java/org/apache/maven/project/artifact/MavenMetadataSource.java
- pom.xml
Following this checklist to help us incorporate your contribution quickly and easily:
**This pull request makes sure that the `ReactorReader` looks at _all_ modules in the project, not only those that are part of the reactor. It also checks whether the workspace might contain built artifacts from earlier Maven invocations, and uses those files for the artifacts that they belong to.**
**Additionally, there is an extra integration test in maven-integration-testing: [apache/maven-integration-testing #54](https://github.com/apache/maven-integration-testing/pull/54).**
If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the developers list.
To make clear …
> [MNG-4660] --resume-from flag resolves inter-module dependencies

- maven-slf4j-wrapper/src/main/java/org/apache/maven/logwrapper/LogLevelRecorder.java
- maven-slf4j-wrapper/src/test/java/org/apache/maven/logwrapper/LogLevelRecorderTest.java
Following this checklist to help us incorporate your contribution quickly and easily:
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.
> [MNG-6891] Improve user-friendliness --fail-on-severity

- maven-builder-support/src/main/java/org/apache/maven/building/DefaultProblem.java
- maven-core/src/main/java/org/apache/maven/exception/DefaultExceptionHandler.java
- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- maven-core/src/main/java/org/apache/maven/project/ProjectBuildingException.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelProblem.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelBuildingException.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsProblem.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/SettingsBuildingException.java
This one turns non-sense output like this:
```
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] input contained no data @
@
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] input contained no data @
```
to this:
```
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] input contained no data
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems …
```
> Avoid empty locations

- maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
The MavenCliTest.testStyleColors is not failing when the build
is under JDK 8 or JDK 11.
After changing to JDK 16, the test fails, this commit is to fix
the NullPointerException.
Tested on JDK 8, 11 adn 16 with:
`mvn clean verify`
In JDK 8 the method `Paths.get` used in [ResolveFile.java#L47](https://github.com/apache/maven/blob/master/maven-embedder/src/main/java/org/apache/maven/cli/ResolveFile.java#L47) is using internally:
```java
public static Path get(String first, String... more) {
return FileSystems.getDefault().getPath(first, more);
}
```
but in JDK 16
```java
public static Path get(String first, String... more) {
return Path.of(first, more);
}
```
for the change (usually before you start …
> [MNG-7127] fix MavenCliTest.testStyleColors test in JDK 16

- .github/workflows/maven.yml
Follow-up for #456, now adding Java 17-ea to the matrix.
> Run GitHub actions integration tests with Java 17-ea

- apache-maven/pom.xml
- apache-maven/src/assembly/maven/component.xml
- pom.xml
This PR depends on https://github.com/apache/maven-shared-utils/pull/69 and the release of `maven-shared-utils`.
> [MNG-7079] Upgrade to jansi 2.2.0

- .mvn/readme.txt
- build/checkstyle-suppressions.xml
- maven-core/src/main/java/org/apache/maven/execution/BuildResumptionAnalyzer.java
- maven-core/src/main/java/org/apache/maven/execution/BuildResumptionDataRepository.java
- maven-core/src/main/java/org/apache/maven/project/collector/ProjectCollectionStrategy.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultBuildPomXMLFilterFactory.java
- maven-model/pom.xml
- pom.xml
This PR improves the build time wrt to checkstyle.
Two other PRs will follow eventually to incorporate https://github.com/codehaus-plexus/modello/pull/116, https://github.com/codehaus-plexus/modello/pull/117 and https://github.com/mojohaus/animal-sniffer/pull/165 if possible.
Those 4 fixes make subsequent builds much smoother.
> Improve the use of checkstyle in the build

- maven-core/src/main/resources/META-INF/maven/extension.xml
- pom.xml
> [MNG-7045] Drop CDI API from Maven

- maven-core/src/main/java/org/apache/maven/plugin/version/internal/DefaultPluginVersionResolver.java
- maven-core/src/main/java/org/apache/maven/rtinfo/internal/DefaultRuntimeInformation.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionSchemeProvider.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenResolverModule.java
This PR makes VersionScheme a component, is injected where needed
(instead of ad-hoc instantiation), but provides room for
different schemas, as GenericVersionScheme is "default"
but now nothing stops to add other schemes as well.
> [MNG-7103] VersionScheme provider

- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluator.java
This constructor was deprecated in Maven 3.0-RC1 (!!!).
Removal also means that Maven4 will NOT work with
(Maven2 compatible) m-enforcer-p 2.x, only with
modern m-enforcer-p 3.x line.
https://issues.apache.org/jira/browse/MNG-7279
> [MNG-7279] Drop deprecated constructor

- maven-bom/pom.xml
- pom.xml
This is required in order to be able to build master with itself.
To …
> [MNG-7329] Upgrade maven-enforcer-plugin

- maven-caching/src/main/java/org/apache/maven/caching/CacheControllerImpl.java
- maven-caching/src/main/java/org/apache/maven/caching/HttpCacheRepositoryImpl.java
- maven-caching/src/main/java/org/apache/maven/caching/artifact/RestoredArtifact.java
- maven-caching/src/main/java/org/apache/maven/caching/xml/CacheConfig.java
- maven-caching/src/main/java/org/apache/maven/caching/xml/CacheConfigImpl.java
Cache repositories refactoring for java8 - using optionals instead of nullables …
> [MNG-7129] http repo refactoring for java8

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java
Same as https://github.com/apache/maven/pull/627 for for 3.8.x branch.
> [3.8.x][MNG-7156][MNG-7285] Add locking in MojoExecutor

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java
Hopefully supersedes #476, #578, #625 in order to fix the threading problems in `MavenProject` during parallel builds.
This may need to be combined with #570  and https://github.com/apache/maven-integration-testing/pull/127
> [master][MNG-7156][MNG-7285] Add locking in MojoExecutor

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RelocatedArtifact.java
> [MNG-7374] Mutating RelocatedArtifact does not retain type

- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/internal/ExtensionResolutionException.java
- maven-embedder/src/main/mdo/core-extensions.mdo
> [MNG-6326] Make the build fail if core extensions can not be loaded

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleStarter.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/ReactorContext.java
- maven-core/src/main/java/org/apache/maven/session/scope/internal/SessionScope.java
- maven-core/src/test/java/org/apache/maven/session/scope/internal/SessionScopeTest.java
Related to 
*  https://github.com/apache/maven/commit/45563ff5cbfd066761913ae35a4e3e8e6e25e83c
*  https://github.com/apache/maven/commit/702acd2e8beb7d5c159edbc59bcbf752b5f1963d
The original scopes were working correctly but did not support multithreaded builds.
The new scope implementation does not use threading at all, so it's safer in a multithreaded build.
is to use the JIRA issue title in the pull request title and in the first …
> [MNG-7347] SessionScoped beans should be singletons for a given session

- maven-core/src/main/resources/META-INF/maven/extension.xml
Packages not exported from maven-core:
* o.a.m.bridge
* o.a.m.eventspy
* o.a.m.execution.infoproviders
* o.a.m.lifecycle.mapping
* o.a.m.feature
Packages not exported from dependencies
* org.eclipse.sisu
the above one is required for @Priority, but there may be others needed, not sure.
Packages that should not be exported
* o.a.m.rtinfo.internal
My commit only fixes `o.a.m.feature`, `org.eclipse.sisu` and `o.a.m.rtinfo.internal`.
> [MNG-7345] Fix exported packages

- maven-model/src/main/java/org/apache/maven/model/merge/ModelMerger.java
- maven-model/src/test/java/org/apache/maven/model/merge/ModelMergerTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7386
> [3.8.x][MNG-7386] Make sure the ModelMerger$MergingList can be serialized

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectDependenciesResolver.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RelocatedArtifact.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7349
IT: https://github.com/apache/maven-integration-testing/pull/134
> [3.8.x][MNG-7349] Limit relocation warning message to direct dependencies only

- maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/MojoDescriptor.java
- maven-plugin-api/src/test/java/org/apache/maven/plugin/descriptor/MojoDescriptorTest.java
It may lead to confusion as parameters (list) and
parametersMap (map) may "fall apart" easily.
Also, parametersMap did not honor parameter
ordering while parameters list makes it look
that order is important.
Simply, rebuild the map always and retain
ordering as well.
Added UT and also removed some cruft provided
by java8.
---
https://issues.apache.org/jira/browse/MNG-7309
See https://github.com/apache/maven/pull/291
> [MNG-6776] Inconsistent list of parameters for MojoDescriptor

- maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java
We at [Tycho](https://github.com/eclipse/tycho) have a combination of a core-extension and a build-plugin. What always is a source of confusion, that one is able to define e.g. a `<tycho-version>` property that could be overridden on the commandline using -D but no such thing exits for the `.mvn/extensions.xml`
This makes it also hard to make some regression-testing e.g. to check fast if a certain problem occurs also in the previous version as one always has to take in mind that the `.mvn/extensions.xml` must be edited by hand.
For that reason it would help if at least basic interpolation using the "maven-properties" would be possible.
This PR adds support for having basic interpolation in `.mvn/extensions.xml` to either:
1. Specify a (default) version in `maven.config`
2. Specify a …
> [3.8.x][MNG-7395] - Support system-properties in extension.xml

- maven-core/src/main/java/org/apache/maven/lifecycle/DefaultLifecycles.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecyclePluginAnalyzer.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/main/java/org/apache/maven/plugin/DefaultMojosExecutionStrategy.java
- maven-core/src/main/java/org/apache/maven/plugin/MojoExecutionRunner.java
- maven-core/src/main/java/org/apache/maven/plugin/MojosExecutionStrategy.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/test/java/org/apache/maven/lifecycle/DefaultLifecyclesTest.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/MojoExecutorStub.java
https://issues.apache.org/jira/browse/MNG-7391
supercedes #607
> [MNG-7391] add execution strategy+runner required by Maven Build Cache

- pom.xml
This issue is fluke, as logback is actually optional
dependency, but still, to cut reports like these from
root, let's do this update.
---
https://issues.apache.org/jira/browse/MNG-7441
> [MNG-7441] 3.8.x Update version of logback

- maven-core/src/main/java/org/apache/maven/ReactorReader.java
The commit c604db3c3a103e2212f4628d8e2a997017fe579e
changed ReactorReader to use MavenSession#getAllProjects()
instead of deprecated MavenSession#getProjectMap() that
is equivalent of MavenSession#getProjects().
This undoes this unintended change.
> [MNG-7447] Fix ReactorReader unintended change

- apache-maven/pom.xml
- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
- maven-resolver-provider/pom.xml
- pom.xml
But keep Wagon as default transport. This PR merely includes
resolver http and file transport and switches wagon-http
to non-shaded one.
Changes:
* switch to non-shaded wagon-http (as httpClient is now shared)
* include resolver http and file transport
* override resolver default behaviour (native transport preferred over wagon, when both on classpath)
* provide simplistic means to choose transport
The chosen transport can be seen in debug (-X) output on line
`[DEBUG] Using transporter XXX...`
The `-Dmaven.transport` simplistic switch can be used to choose transport:
* not set: default, that is Wagon
* `wagon`: explicitly sets Wagon
* `resolver`: explicitly sets resolver native transports (file and http)
* `auto`: relies on resolver "auto discovery" (priorities, etc). This is MUST to keep …
> [MNG-7454] Include resolver-transport-http in Maven 3.9.x

- apache-maven/pom.xml
- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
- maven-resolver-provider/pom.xml
- pom.xml
But keep Wagon as default transport. This PR merely includes
resolver http and file transport and switches wagon-http
to non-shaded one.
Changes:
* switch to non-shaded wagon-http (as httpClient is now shared)
* include resolver http and file transport
* override resolver default behaviour (native transport preferred over wagon, when both on classpath)
* provide simplistic means to choose transport
The chosen transport can be seen in debug (-X) output on line
`[DEBUG] Using transporter XXX...`
The `-Dmaven.transport` simplistic switch can be used to choose transport:
* not set: default, that is Wagon
* `wagon`: explicitly sets Wagon
* `resolver`: explicitly sets resolver native transports (file and http)
* `auto`: relies on resolver "auto discovery" (priorities, etc). This is MUST to keep …
> [MNG-7454] Include resolver-transport-http in Maven master

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
```
[DEBUG] Loading mojo org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[DEBUG] Configuring mojo execution 'org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test:default-test' with basic configurator -->
```
> MNG-7438 add execution id to "configuring mojo" debug message

- Jenkinsfile
- maven-compat/pom.xml
- maven-compat/src/test/java/org/apache/maven/artifact/deployer/ArtifactDeployerTest.java
- maven-compat/src/test/java/org/apache/maven/artifact/installer/ArtifactInstallerTest.java
- maven-core/src/main/java/org/apache/maven/execution/infoproviders/DefaultPluginsMetadataInfoProvider.java
- maven-core/src/main/resources/META-INF/plexus/default-bindings.xml
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadataGenerator.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadataGeneratorFactory.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadataInfoProvider.java
Maven Artifact Transfer silently prevents group level metadata to reach Resolver and causes metadata loss on install/deploy.
Fix is to "bridge" this from maven-resolver-provider (and core) by reusing the actual metadata that
m-plugin-p:addPluginArtifactMetadata mojo adds, but m-a-t filters out.
This is backport of commit d141957ff5a3c08ae53c68e4ba19b49055f717c4 from master to maven-3.9.x branch.
> [MNG-7055] Fix G level metadata handling in 3.9.x

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginConfigurationValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/ValidatingConfigurationListener.java
In previous solution we used `ConfigurationListener` where we had information about setting value on specific Mojo filed.
Value in listener (which can be any class instance) will be compared to custom prepared String from Mojo parameters default.
Plugin configurator (can be user implementation) has own logic how to create parameter value from strings provide in default arguments in plugin configuration.
So to achieve goal of issue - we want to check when user use deprecated Mojo parameter in configuration - we can check `XmlPlexusConfiguration` before plugin fields will be populated.
I introduce interface `MavenPluginConfigurationValidator` 
which has as input `XmlPlexusConfiguration` and `MojoDescriptor` for validating xml configuration used in plugin.
In this PR it is first …
> [MNG-5222] Improvement in deprecated params detection

- apache-maven/src/assembly/bin.xml
- apache-maven/src/assembly/dir.xml
- apache-maven/src/assembly/src.xml
As title says, XSD is ancient old 2.0.0, while all
latest assembly plugins uses 2.1.0.
Not that this matters or changes anything at all,
this is more about correctness.
---
https://issues.apache.org/jira/browse/MNG-7466
> [MNG-7466] Align assembly XSD version with plugin used

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
Instead of user properties, as this allows making "permanent" the
selection by using MAVEN_OPTS and other places as well. Currently
only via command line works.
Also, do not modify existing Maven behavior, so introduce "default" branch
in selection. See comment in code.
---
https://issues.apache.org/jira/browse/MNG-7478
> [MNG-7478] Transport selection should use config properties

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
This needs to be applied to 3.8.x, 3.9.x and master branches
> [3.8.x] [MNG-7476] Display a warning when an aggregator mojo locks other mojos executions

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultMojoExecutionConfigurator.java
After `MojoExecution` was created and configured all configuration will only contains parameters listed in plugin.xml
--- …
> [MNG-7468] Check unsupported plugins parameters in configuration

- maven-core/src/main/java/org/apache/maven/DefaultArtifactFilterManager.java
- maven-core/src/main/java/org/apache/maven/classrealm/DefaultClassRealmManager.java
- maven-core/src/main/java/org/apache/maven/extension/internal/CoreExportsProvider.java
- maven-embedder/pom.xml
- maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java
- maven-embedder/src/main/mdo/core-extensions.mdo
JIRA issue: https://issues.apache.org/jira/browse/MNG-7160
To make clear …
> [MNG-7160] Ability to customize core extensions classloaders

- maven-model-transform/src/main/java/org/apache/maven/model/transform/BuildToRawPomXMLFilterFactory.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/FastForwardFilter.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/RawToConsumerPomXMLFilterFactory.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/pull/BufferingParser.java
- maven-model-transform/src/test/java/org/apache/maven/model/transform/ParentXMLFilterTest.java
As hinted by @rfscholte , the `FastForwardFilter` is supposed to handle those problems by disabling the filters when parsing  xml config nodes.  I've added a unit test and investigated in that direction, which leads to this new PR.  It looks much simpler than #697, so I think it's better to keep that one.
> [MNG-7360] Fix xml transformation to ensure proper context

- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/EarLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/EjbLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/JarLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/MavenPluginLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/PomLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/RarLifecycleMappingProvider.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/WarLifecycleMappingProvider.java
To lessen mistake (copy-paste vs forgotten update) but also just to
make things less redundant. This also makes possible "experimenting"
much more easier.
This is merely a refactoring that does not takes or gives anything, just tidies up.
> Pull out lifecycle plugin versions

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleStarter.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/MultiThreadedBuilder.java
- maven-core/src/test/java/org/apache/maven/execution/DefaultMavenExecutionTest.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
JIRA: https://issues.apache.org/jira/browse/MNG-7511
This PR ensures the `degreeOfConcurrency` is always a positive number (defaulting to `1`). It resolves issues when the computed value is `< 1`.
[Individual Contributor License …
> [MNG-7511] Ensure the degreeOfConcurrency is a positive number in MavenExecutionRequest

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleStarter.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/MultiThreadedBuilder.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
Backports #767 into the `3.9.x`.
JIRA: https://issues.apache.org/jira/browse/MNG-7511
This PR ensures the `degreeOfConcurrency` is a positive number. It resolves issues when the computed value is `< 1`.
> [MNG-7511] Ensure the degreeOfConcurrency is a positive number (3.9.x)

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleTaskSegmentCalculator.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoDescriptorCreator.java
https://issues.apache.org/jira/browse/MNG-7353
> [MNG-7353] support CLI "mvn pluginPrefix:version:goal"

- apache-maven/src/bin/mvn
- apache-maven/src/bin/mvn.cmd
- apache-maven/src/bin/mvnDebug
- apache-maven/src/bin/mvnDebug.cmd
- apache-maven/src/bin/mvnyjp
https://maven.apache.org/configure.html shows the MAVEN_ARGS
environment variable which is extremely useful for customizing build
scripts and processes. Unfortunately, it is only support for (unreleased)
Maven 4.
This patch backports support to Maven 3.8.x in the hope that this
support would arrive much sooner than with Maven 4.x.x
be performed on …
> [MNG-7523] Backport MAVEN_ARGS support to 3.8.x

- maven-core/src/main/java/org/apache/maven/execution/MavenSession.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/BuildListCalculator.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleStarter.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/ReactorContext.java
- maven-core/src/main/java/org/apache/maven/session/scope/internal/SessionScope.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/BuildListCalculatorTest.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilderTest.java
https://issues.apache.org/jira/browse/MNG-7401
https://issues.apache.org/jira/browse/MNG-7474
@laeubi this supersedes https://github.com/apache/maven/pull/666
> [3.9.x] [MNG-7401] [MNG-7474] Keep a single maven session and fix session scope

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
@cstamas  This is the discussed alternate fix for MNG-7529. I structured it differently. The actual meat is in the e70b8c86a99d65c4f1290402f014069178499444 fix; I put that on top of a reversal of the previous fix; I do intend to squash and merge though (not have a reversal and a full new fix).
Please let me know if that is more along the shape that you were thinking of. 
title in the pull request title and in the first line …
> MNG-7529 alternate fix

- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
- maven-embedder/src/test/java/org/apache/maven/cli/event/ExecutionEventLoggerTest.java
This PR ensures that when a multi module project is resumed halfway, the project progress counter is not reset. 
[Related issue](https://issues.apache.org/jira/browse/MNG-7098).
[Individual Contributor License …
> [MNG-7098] Keep the project counter intact when resuming a multi-module project.

- .gitignore
- maven-bom/pom.xml
- pom.xml
When switching branches, left-over `target` folder *often* causes issues with the `rat-maven-plugin`.
Ignoring those folders does help from a day-to-day pov.
See #814 and #815
> Make sure RAT plugin ignores files in the target folder

- .github/workflows/maven_build_itself.yml
- api/modello-plugin-velocity/pom.xml
- maven-artifact/pom.xml
- maven-compat/pom.xml
- maven-core/pom.xml
- maven-core/src/main/resources/META-INF/maven/extension.xml
- maven-embedder/pom.xml
- maven-model-builder/pom.xml
- maven-model-transform/pom.xml
- maven-plugin-api/pom.xml
- maven-repository-metadata/pom.xml
- maven-resolver-provider/pom.xml
- maven-settings-builder/pom.xml
- maven-settings/pom.xml
- maven-toolchain-builder/pom.xml
- maven-toolchain-model/pom.xml
- plexus-utils/pom.xml
- pom.xml
> Fix the repackaged plexus-utils groupId

- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/MavenBuildTimestamp.java
Restore compatibility with maven 3.x.
This is causing some plugins to fail:
```
[ERROR] Failed to execute goal
org.codehaus.mojo:flatten-maven-plugin:1.3.0:flatten (flatten) on project maven-super: Execution flatten of goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:flatten 
failed: An API incompatibility was encountered while executing org.codehaus.mojo:flatten-maven-plugin:1.3.0:flatten: java.lang.NoSuchMethodError: 'void 
org.apache.maven.model.interpolation.MavenBuildTimestamp.<init>(java.util.Date, java.util.Properties)'
```
> Restore compatibility with 3.x

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/ProfileActivationContext.java
This can be used for packaging specific profiles with the property activator.
To make clear …
> [MNG-6609] expose packaging via property "project.packaging"

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
> [MNG-7561] never resolve version ranges with same lower and upper bound

- maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginDescriptorCache.java
- maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginRealmCache.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginDescriptorCache.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginRealmCache.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7583
This would allow a better integration with mvnd.
At the moment, `mvnd` has to rewrite the `MavenPluginManager` to work around this synchronisation bottleneck.
See https://github.com/apache/maven-mvnd/blob/master/daemon/src/main/java/org/mvndaemon/mvnd/plugin/CliMavenPluginManager.java
Having the additional `get` methods on the cache would allow `mvnd` to simply provide a different cache, without having to rewrite the `DefaultMavenPluginManager`.
This will ease mvnd maintenance and maven upgrades a lot !
> [MNG-7583] Allow concurrent access to the MavenPluginManager

- api/maven-api-core/src/main/java/org/apache/maven/api/services/BuilderProblem.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilder.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilderResult.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilder.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilderException.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilderResult.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/Source.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainsBuilder.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainsBuilderException.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainsBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainsBuilderResult.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSettingsBuilder.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultToolchainsBuilder.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7580
Supersedes https://github.com/apache/maven/pull/823
> [MNG-7580] Introduce new SettingsBuilder and ToolchainsBuilder services

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/ProfileActivationContext.java
In short: do NOT set request.setRawModel as NOTHING sets it. The Maven4 vs Maven3 is different, in Maven 3 NOTHING calls request.setRawModel
Full explanation: as ModelBuildingRequest is REUSED, and nothing sets this value in Maven3, once you set it here (as in original PR https://github.com/apache/maven/pull/849 ) results in awkward situation in Maven3: it will not load any other model...
---
https://issues.apache.org/jira/browse/MNG-6609
> [MNG-6609] Profile activation based on packaging

- api/maven-api-core/src/main/java/org/apache/maven/api/services/Transport.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/TransportProvider.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/TransportProviderException.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTransport.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTransportProvider.java
Something simple to use and would reuse all the auth/proxy etc data from Maven. Intentionally super-trivial API.
If something more "serious" needed, plugin should probably roll it's own solution.
---
https://issues.apache.org/jira/browse/MNG-7607
> [MNG-7607] Add M4 Transport API

- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteChecker.java
- maven-core/src/test/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteCheckerTest.java
- maven-plugin-api/src/main/mdo/plugin.mdo
Always assume version constraint (the same as in requiredMavenVersion)
> [MNG-7611] Change semantics of plugin descriptor's "requiredJavaVersion"

- api/maven-api-xml/src/main/java/org/apache/maven/api/xml/Dom.java
- maven-xml-impl/src/main/java/org/apache/maven/internal/xml/Xpp3Dom.java
- maven-xml-impl/src/main/java/org/apache/maven/internal/xml/Xpp3DomBuilder.java
- maven-xml-impl/src/test/java/org/apache/maven/internal/xml/Xpp3DomTest.java
- pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7596
Upgrade to plexus 3.5.0 and change the xml merge accordingly
Note that I had to hack a bit the order to keep the current ordering, see https://issues.apache.org/jira/browse/MNG-5474
> [MNG-7596] Upgrade to plexus 3.5.0

- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingResult.java
- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/BuildTimestampValueSource.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileActivationContext.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileSelector.java
> [MNG-7617] Small optimisations and cleanup in the project/model building

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
This immediately cuts in "half" the count of HTTP requests against Maven Central or any major MRM.
Altering the meaning of "default": is now same as "auto", but still leaving it in place for future, as "default" at some point may again become something different than "native".
---
https://issues.apache.org/jira/browse/MNG-7608
> [MNG-7608] Make native transport the default

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/DefaultArtifactVersionTest.java
Fix versions comparison https://issues.apache.org/jira/browse/MNG-7559
intention is:
* 1.0.0.RC1 < 1.0.0-RC2
* ( edr, pfd, etc.) < final, ga, release
* 9.4.1.jre16 > 9.4.1.jre16-preview
following semver rules should be encouraged, natural ordering is used without the need to hard code strings, except for hard coded qualifiers 'a', 'b', 'm', 'cr', 'snapshot', 'final', 'ga', 'release', '' and 'sp':
* alpha = a < beta = b < milestone = m < rc = cr < 'snapshot' < '' = 'final' = 'ga' = 'release' < 'sp'
the documentation should discourage the usage of 'CR', 'final', 'ga', 'release' and 'SP' qualifiers.
Maven Central should begin to reject new artifact using CR and SP qualifiers.
---
for the change (usually …
> [MNG-7559] Fix versions comparison

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
- maven-core/src/main/java/org/apache/maven/internal/aether/ReverseTreeRepositoryListener.java
- maven-core/src/test/java/org/apache/maven/internal/aether/ReverseTreeRepositoryListenerTest.java
Adds Maven feature that is able to explain why an artifact is present in local repository.
Usable for diagnosing resolution issues.
In local repository, for each artifact it records `.tracking` folder, containing farthest artifact that got to this artifact, and the list of graph nodes that lead to it.
Note: this is based on by @grgrzybek proposal and reuses some code he provided. See https://github.com/apache/maven-resolver/pull/182
---
https://issues.apache.org/jira/browse/MNG-7619
> [MNG-7619] Reverse Dependency Tree

- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7618
Related to https://github.com/apache/maven-mvnd/issues/745
> [MNG-7618] Use goalPrefix instead of artifactId to display mojos being executed

- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileSelector.java
Restore compatibility for the flatten maven plugin which needs an no-arg constructor.
> [MNG-7576] Restore compatibility for flatten-maven-plugin

- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
JIRA issue : https://issues.apache.org/jira/browse/MNG-7624
> [MNG-7624] Use groupId:artifactId instead of empty goal

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
LocalRepositoryManager needs configurations from RepositorySystemSession so must be created after session configuration is finished.
(cherry picked from commit b1c1f7556d6b66d984c4ed2c0eb723c9b99b38be)
---
- [ x] You have run the [Core IT][core-its] successfully.
If your pull request is about ~20 lines …
> [MNG-7600] LocalRepositoryManager is created too early

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
This closes #917
the [Apache License …
> [MNG-7634] Revert MNG-5982 and MNG-7417 (Maven 3.9.x)

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
The current version parser does not treat .RC and -RC correctly:
actual : 1.0.0.RC1 > 1.0.0-RC2
expected : 1.0.0.RC1 < 1.0.0-RC2
 
because RC1 < RC2
how to fix : place a list item before qualifier
as a consequence for any string qualifier x:
previously:
* 1.0.0.X1 > 1.0.0-X2
* 1.0.X < 1.0.0.X
now:
* 1.0.0.X1 < 1.0.0-X2
* 1.0.X == 1-X == 1.0.0.X
---
Best practice is to use the JIRA issue title in both the pull request title and in the …
> [MNG-7644] Fix version comparison ( .X1 < -X2 for any string qualifier x ), 4.0.x branch

- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
Lack of these changes are making IT suite to fail with maven-3.9.x branch.
OTOH, the change is nearly trivial, while value is high, so let's backport them.
---
https://issues.apache.org/jira/browse/MNG-7618
https://issues.apache.org/jira/browse/MNG-7624
> [MNG-7618][MNG-7624] Backport to Maven 3.9.x

- maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java
- maven-core/src/test/projects/project-builder/MNG-7648/pom.xml
- maven-core/src/test/remote-repo/org/apache/maven/its/bom/0.1/bom-0.1.pom
- maven-core/src/test/remote-repo/org/apache/maven/its/bom/maven-metadata.xml
- maven-core/src/test/remote-repo/org/apache/maven/its/parent/0.1/parent-0.1.pom
- maven-core/src/test/remote-repo/org/apache/maven/its/parent/maven-metadata.xml
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuildingRequest.java
This fixes missing `locationTracking` in project model.
Missing `locationTracking` was causing issues down the line in enforcer plugin that was not able to verify source of the model configuration.
--
Following this checklist to help us incorporate your contribution quickly and easily:
If your pull request is about ~20 lines of code you don't need to …
> [MNG-7648] Fix locationTracking in DefaultModelBuildingRequest copy constructor.

- Jenkinsfile
> Jenkinsfile: pickup results from ITs - 3.9.x

- maven-core/src/main/resources/META-INF/plexus/components.xml
- maven-core/src/main/resources/META-INF/plexus/default-bindings.xml
Finally use 3.x plugins for all.
---
https://issues.apache.org/jira/browse/MNG-7666
> [maven-3.9.x] [MNG-7666] Update default binding and lifecycle plugin versions

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
This immediately cuts in "half" the count of HTTP requests against Maven Central or any major MRM.
Altering the meaning of "default": is now semantically same as "auto", but still leaving it in place for future, as "default" at some point may again become something different than "native". This change is exactly same as happened in Maven 4.x and transports are aligned now.
---
https://issues.apache.org/jira/browse/MNG-7608
> [3.9.x][MNG-7608] Make native transport the default

- maven-core/src/main/java/org/apache/maven/DefaultMaven.java
- maven-core/src/main/java/org/apache/maven/ReactorReader.java
Similar to #912 but without removing the best effort artifact resolution to keep `mvn test` working _if possible_.
This require a few ITs to be modified:
https://github.com/apache/maven-integration-testing/pull/234/
> [MNG-7629] Change reactor reader to copy packaged artifacts and reuse them across builds if needed

- apache-maven/pom.xml
As POM uses deprecated configuration.
> Get rid of surefire warning

- apache-maven/pom.xml
The commit 36f02c9de1792478538a171108048c8b86d5a5a1 is wrong, as new config property is a Map.
> Get rid of surefire warning, take 2

- maven-core/src/main/java/org/apache/maven/DefaultMaven.java
- maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java
Follow up to MNG-7629 and #954, the idea for this PR is to not parse all the reactor.
The idea of this PR is to parse all projects from the reactor only if the _makeBehavior_ is set (i.e. `-am` and/or `-amd` option has been used), or if a project activation has been set (i.e. `-pl`, `-r` or `-rf` is used).  Note that parents are always resolved from the file system, even if not included in the reactor.
The ITs only require a single modification: https://github.com/apache/maven-integration-testing/pull/239
> [MNG-7646] Do not parse all projects in the reactor when building a subtree

- maven-core/src/site/apt/getting-to-container-configured-mojos.apt
- maven-core/src/site/apt/offline-mode.apt
As date format in these two files were not parsed.
> [3.9.x] Fix site plugin warning

- apache-maven/pom.xml
Wrong goal is being used that does not honor classifiers. Also, have to reshuffle the config, move it inside execution otherwise ASF parent pom execution is NOT overridden.
---
https://issues.apache.org/jira/browse/MNG-7676
> [MNG-7676] Fix checksum plugin configuration

- apache-maven/pom.xml
Not only src but bin needs SHA512 as well. Plugin now does:
```
[INFO] --- checksum:1.11:artifacts (source-release-checksum) @ apache-maven ---
[INFO] apache-maven-4.0.0-alpha-5-SNAPSHOT-bin.tar.gz - SHA-512 : 2ee4c27ff611852caffab6543582918c06d900da184cdd389e64bae05fb8a2ac959edf27a946c60c9129c87baa6ec593a64d25edf3739339dd3f8d3d7942c7db
[INFO] apache-maven-4.0.0-alpha-5-SNAPSHOT-bin.zip - SHA-512 : 078667f3aad060163cad692eab7ced00fa377ba3a89f43431b23bd5248fc1603d3668cd68a7f096abcbc460ef4fbb47981b6bf5acc236a522e40fd700bb415c6
[INFO] apache-maven-4.0.0-alpha-5-SNAPSHOT-src.tar.gz - SHA-512 : ad2ca325ef138389fa967bde5e176a2447b5dd9e7edfa5cd1bf3f586fd39b93a1d415b55bb41b29e996104a4e14d4ef5fcc0e2c2eff65609121595f2695c96d4
[INFO] apache-maven-4.0.0-alpha-5-SNAPSHOT-src.zip - SHA-512 : …
```
> Add bin packages to SHA512 checksumming as well

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
- pom.xml
The crux was  in resolver 1.9.5, but there are other "low hanging fruits" like delegate created on a "hot method".
---
https://issues.apache.org/jira/browse/MNG-7677
> [MNG-7677] Maven slowness improvement

- maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepository.java
- maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepositoryPolicy.java
- maven-artifact/src/main/java/org/apache/maven/artifact/repository/layout/ArtifactRepositoryLayout.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginDescriptorSourcedParametersValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginParametersValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedCoreExpressionValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java
This PR deprecates the 'localRepository' mojo parameter expression, and Core will emit warning if used by any Mojo.
---
https://issues.apache.org/jira/browse/MNG-7706
> [MNG-7706] Deprecate 'localRepository' parameter expression

- maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepository.java
- maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepositoryPolicy.java
- maven-artifact/src/main/java/org/apache/maven/artifact/repository/layout/ArtifactRepositoryLayout.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginDescriptorSourcedParametersValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginParametersValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedCoreExpressionValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java
This PR deprecates the 'localRepository' mojo parameter expression, and Core will emit warning if used by any Mojo.
Forward port of https://github.com/apache/maven/pull/1009
---
https://issues.apache.org/jira/browse/MNG-7706
> [MNG-7706] Deprecate 'localRepository' parameter expression (#1009)

- pom.xml
As version 3.4.0 and above introduced several issues related to XML parsing and merging.
---
https://issues.apache.org/jira/browse/MNG-7710
> [MNG-7710] Downgrade plexus-utils to 3.3.1

- maven-xml-impl/src/main/java/org/codehaus/plexus/util/xml/Xpp3Dom.java
and we remove reference to class we want to delete
> remove unused code

- maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequest.java
- maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java
- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
There is really no need for it, and there is a resolver option if really must (but really should not, local repo is and should be considered as transient).
---
https://issues.apache.org/jira/browse/MNG-7713
> [maven-3.9.x] [MNG-7713] Drop legacy-local-repository option

- maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginDescriptorCache.java
- maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginRealmCache.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginDescriptorCache.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginRealmCache.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
Backport to 3.9.x branch.
Aligning both 3.9.x and 4.0.x branches would help reducing the maintenance in `mvnd`.
> [3.9.x][MNG-7583] Allow concurrent access to the MavenPluginManager

- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
As with previous PR (simple removal) the `-llr` got interpreted as `-l lr`, it logged all output to `lr` file. This would maean that use of `-llr` would still sneakily 'work' and probably cause surprise down the road to users.
Returned the option, and expicitly checking for it's presence to be able to fail with meaningful message.
---
https://issues.apache.org/jira/browse/MNG-7713
> [MNG-7713] Make Maven fail if option present

- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
As with previous PR (simple removal) the `-llr` got interpreted as `-l lr`, it logged all output to `lr` file. This would maean that use of `-llr` would still sneakily 'work' and probably cause surprise down the road to users.
Returned the option, and expicitly checking for it's presence to be able to fail with meaningful message.
---
https://issues.apache.org/jira/browse/MNG-7713
> [MNG-7713] Make Maven fail if option present (#1021)

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
Also clean up docs, generics, and comparisons
> [MNG-7700] test some edge cases with leading zeroes

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
This option promotes "Maven2" in latest Maven 3 versions that is insane. Also, this option was really meant to bridge transition from Maven2 to Maven3, when both were sharing same local repository. Hopefully, in 2023 nobody does that anymore.
---
https://issues.apache.org/jira/browse/MNG-6889
> [3.8.x] [MNG-6889] Deprecate llr option

- src/mdo/reader.vm
How do I hate git? Let me count the ways. 
In any case, this PR should bring the repo back to the state it was in before an accidental commit to master.
> restore src/mdo/reader.vm

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/ConcurrencyDependencyGraph.java
- maven-core/src/test/java/org/apache/maven/project/ProjectModelResolverTest.java
- maven-resolver-provider/src/test/java/org/apache/maven/repository/internal/DefaultModelResolverTest.java
- pom.xml
Update and apply some adjustments to UTs as
error message did change.
---
https://issues.apache.org/jira/browse/MNG-7715
> [MNG-7715] Update to resolver 1.9.6

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
The original fix MNG-7672 matched the "scope" but missed the "order". `project.collectedProjects` are in order as loaded (POM order), is not topologically sorted.
Fix is to use DAG of projects, ask for downstream projects (will return more then we need but sorted) and narrow that list to only contain collected projects.
Related commit: 48cac1c003fdc409e8c455c21fcba07050393b0c
---
https://issues.apache.org/jira/browse/MNG-7720
> [3.9.x] [MNG-7720] Wrong build order of forked projects

- maven-core/src/test/java/org/apache/maven/configuration/DefaultBeanConfiguratorPathTest.java
- maven-core/src/test/java/org/apache/maven/configuration/DefaultBeanConfiguratorTest.java
- maven-embedder/src/main/java/org/eclipse/sisu/plexus/PlexusXmlBeanConverter.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadataGenerator.java
Remove remaining references to the plexus-utils Xpp3DomBuilder and favour the internal XmlNodeBuilder instead.
This also removes one reference to the plexus-utils ReaderFactory.
> Remove references to Xpp3DomBuilder and use XmlNodeBuilder instead

- maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeBuilder.java
- maven-xml-impl/src/main/java/org/codehaus/plexus/util/xml/Xpp3DomBuilder.java
For compatibility reason, the Xpp3DomBuilder will close those.
> Fix callee closing streams and readers instead of callers

- api/maven-api-model/src/main/mdo/maven.mdo
JIRA issue: https://issues.apache.org/jira/browse/MNG-7728
The PluginContainer from the v4 api uses the same additional code block than the v3 api and thus offers a `getPluginsAsMap()` method along with a `flushPluginMap()` which makes the whole class non immutable.
Given additional constructor arguments are not supported by the generator, using a lazy computed field should be enough to ensure that the content of the class never changes, even though the field itself can change, the value returned by `getPluginsAsMap()` cannot.
> [MNG-7728] Fix mutable api in PluginContainer

- maven-embedder/src/main/java/org/apache/maven/cli/logging/Slf4jConfigurationFactory.java
- maven-embedder/src/main/java/org/apache/maven/cli/logging/impl/UnsupportedSlf4jBindingConfiguration.java
This is a more direct approach to avoiding the warnings. Just take them out. They're not actionable and no one cares about this.
> [MNG-7724] don't warn about unsupported SLF4J configs; no one cares

- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileActivationContext.java
There was a typo: the stream contains entries, so e.getKey and e.getValue is needed.
---
https://issues.apache.org/jira/browse/MNG-7726
> [MNG-7726] Maven 3.9.0 resolves properties incorrectly

- api/maven-api-model/src/main/java/org/apache/maven/api/model/ImmutableCollections.java
- api/maven-api-settings/src/main/java/org/apache/maven/api/settings/ImmutableCollections.java
- api/maven-api-settings/src/test/java/org/apache/maven/api/settings/SettingsTest.java
- api/maven-api-toolchain/src/main/java/org/apache/maven/api/toolchain/ImmutableCollections.java
- maven-plugin-api/src/main/java/org/apache/maven/plugin/lifecycle/ImmutableCollections.java
- src/mdo/model.vm
JIRA issue: https://issues.apache.org/jira/browse/MNG-7678
> [MNG-7678] Settings (v3) and Settings.Builder() cannot unset a non-null field

- apache-maven/src/assembly/component.xml
Additional fix for [MNG-7697](http://issues.apache.org/jira/browse/MNG-7697)
> [MNG-7697] Fix assembly which should not include plexus-utils-3.5.0

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
Simplify code from MNG-7720 because the getCollectedProjects() already returns all submodules recursively, so no need to recurse again.
> [MNG-7720] Simplify code

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
A minor detail while trying to resolve an underlying bug. The doc comment here does not accurately describe how the string 1.0alpha1 is actually parsed, and this is significant.
> [MNG-7714] correct comment

- maven-artifact/pom.xml
- maven-artifact/src/main/java/org/apache/maven/artifact/ArtifactUtils.java
- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/DefaultArtifactVersion.java
- maven-compat/src/main/java/org/apache/maven/artifact/repository/metadata/MetadataBridge.java
- maven-compat/src/test/java/org/apache/maven/artifact/deployer/ArtifactDeployerTest.java
- maven-core/pom.xml
- maven-core/src/main/java/org/apache/maven/configuration/DefaultBeanConfigurationRequest.java
- maven-core/src/main/java/org/apache/maven/execution/DefaultBuildResumptionDataRepository.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactCoordinateFactory.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactFactory.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginJavaPrerequisiteChecker.java
- maven-core/src/main/java/org/apache/maven/project/artifact/ProjectArtifactMetadata.java
- maven-core/src/main/java/org/apache/maven/rtinfo/internal/DefaultRuntimeInformation.java
- maven-core/src/test/java/org/apache/maven/artifact/handler/ArtifactHandlerTest.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestRepositorySystem.java
- maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java
- maven-core/src/test/java/org/apache/maven/repository/TestRepositoryConnector.java
- maven-embedder/pom.xml
- maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/AbstractMavenTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListener.java
- maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
- pom.xml
https://issues.apache.org/jira/browse/MNG-7756 and https://issues.apache.org/jira/browse/MNG-6825
> [MNG-6825] Get rid of commons-lang

- maven-core/src/main/java/org/apache/maven/plugin/PluginValidationManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginDescriptorSourcedParametersValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginParametersValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedCoreExpressionValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/Maven2DependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenMixedDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginConfigurationValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenScopeDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/PlexusContainerDefaultDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/PluginValidationManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/ReadOnlyPluginParametersValidator.java
This is general rework of current Maven 3.9.x line how it handles plugin and mojo validations.
Changes:
* added plugin validations for dependencies
* introduced pluginValidationManager that gathers violations
* manager creates a report at build end, with dense and non repeating data
* this is in spirit to lessen already too verbose logging, as current solution would report violations as many times plugin is used in reactor, and that can be many (ie. a plugin from parent for each module)
Example report of Maven 3.9.x build: https://gist.github.com/cstamas/b62fdcd53eaf316123cf183f5a24e6a5
---
https://issues.apache.org/jira/browse/MNG-7754
> [MNG-7754] Improvement and extension of plugin validation

- maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
- maven-core/src/test/resources-project-builder/plugin-interpolation-build/pom.xml
- maven-core/src/test/resources-project-builder/plugin-interpolation-reporting/pom.xml
This is the port of https://github.com/apache/maven/pull/1075 to the master branch.
The good thing is that this is ONLY the tests because the maven 4 does not have the problem of MNG-7750.
A few small changes in the tests were needed to handle the internal differences between maven 3.x and maven 4.x.
> [MNG-7750] Ensure no unwanted interpolation in plugins from profiles.

- maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
- maven-core/src/test/resources-project-builder/plugin-interpolation-build/pom.xml
- maven-core/src/test/resources-project-builder/plugin-interpolation-reporting/pom.xml
- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileInjector.java
> [MNG-7750] Executions for plugins from an active profile are interpolated in the originalModel.

- maven-core/src/main/java/org/apache/maven/internal/aether/ReverseTreeRepositoryListener.java
- maven-core/src/test/java/org/apache/maven/internal/aether/ReverseTreeRepositoryListenerTest.java
> [MNG-7741] Track missing files, plugin and parent pom dependencies

- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
As PBR session setter was added in Maven3. Still, this causes unexpected NPE during plugin execution, while Maven3 should support Maven2 plugins.
---
https://issues.apache.org/jira/browse/MNG-7759
> [MNG-7759] Maven2 plugins will not have even session

- maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
- maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
- maven-model-builder/src/site/apt/index.apt
JIRA issue: https://issues.apache.org/jira/browse/MNG-7763
Discussion: https://lists.apache.org/thread/0mjosk1wp58fjvhz812htqfjot0n930g
> [MNG-7763] Provide UTF-8 as a default value for project.build.sourceEncoding and project.reporting.outputEncoding

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
This change reduces default output making it more compact, and also renames the "levels" to brief, default and verbose.
---
https://issues.apache.org/jira/browse/MNG-7767
> [MNG-7767] Tone down plugin validator

- maven-embedder/src/main/java/org/apache/maven/cli/CliRequest.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
Reuse as much as possible from master, but keep existing stuff like multiModuleProjectDirectory alone.
Changes:
* interpolate user properties and arguments
* introduce session.topDirectory and session.rootDirectory expressions (for interpolation only)
* Maven fails to start if any of the new properties are undefined but their use is attempted
* leave everything else untouched
---
https://issues.apache.org/jira/browse/MNG-7774
> [MNG-7774] Maven config and command line interpolation

- maven-slf4j-provider/src/main/java/org/slf4j/impl/MavenSimpleLogger.java
- maven-slf4j-provider/src/test/java/org/slf4j/impl/MavenSimpleLoggerTest.java
Instead of only including causes, suppressed exceptions are now included
as well. A similar indentation strategy as in
`Throwable.printStackTrace` is used.
---
https://issues.apache.org/jira/browse/MNG-7778
> [MNG-7778] - Include suppressed exceptions when logging failures

- maven-compat/src/main/java/org/apache/maven/execution/DefaultRuntimeInformation.java
- maven-compat/src/main/java/org/apache/maven/profiles/activation/FileProfileActivator.java
- maven-compat/src/main/java/org/apache/maven/profiles/activation/SystemPropertyProfileActivator.java
- maven-compat/src/main/java/org/apache/maven/repository/DefaultMirrorSelector.java
- maven-compat/src/main/java/org/apache/maven/repository/legacy/LegacyRepositorySystem.java
- maven-core/src/main/java/org/apache/maven/bridge/MavenRepositorySystem.java
- maven-core/src/main/java/org/apache/maven/classrealm/DefaultClassRealmManager.java
- maven-core/src/main/java/org/apache/maven/exception/DefaultExceptionHandler.java
- maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequestPopulator.java
- maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleExecutionPlanCalculator.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultMojoExecutionConfigurator.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDebugLogger.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/main/java/org/apache/maven/lifecycle/mapping/LifecyclePhase.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterException.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/main/java/org/apache/maven/plugin/version/internal/DefaultPluginVersionResolver.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/project/ProjectSorter.java
- maven-core/src/main/java/org/apache/maven/project/collector/DefaultProjectsSelector.java
- maven-core/src/main/java/org/apache/maven/settings/DefaultMavenSettingsBuilder.java
- maven-core/src/test/java/org/apache/maven/graph/DefaultGraphBuilderTest.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestRepositorySystem.java
- maven-core/src/test/java/org/apache/maven/project/harness/Xpp3DomNodeIterator.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/PropertyProfileActivator.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
Part of an ongoing effort to phase out StringUtils.
https://issues.apache.org/jira/browse/MNG-6829
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
Review requested of @elharo 
---
be performed on your …
> [MNG-6829] Replace any StringUtils#isEmpty(String) and #isNotEmpty(String)

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/main/java/org/apache/maven/plugin/version/internal/DefaultPluginVersionResolver.java
> [MNG-7785] Clean usage of SessionData

- maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/Maven2DependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenMixedDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginDescriptorDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenScopeDependenciesValidator.java
Reword the validation warning and add new check for real plugin dependencies in wrong scopes (do not rely on build-time derived descriptor, but on real data instead).
---
https://issues.apache.org/jira/browse/MNG-7786
> [MNG-7786] Fix plugin validation misleading message

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
This change uses different technique to hook into "session end", and thus is invoked before ExecutionEventLogger is.
---
https://issues.apache.org/jira/browse/MNG-7788
> [MNG-7788] Plugin Validation Report logged before summary

- maven-artifact/src/main/java/org/apache/maven/artifact/DefaultArtifact.java
- maven-artifact/src/test/java/org/apache/maven/artifact/DefaultArtifactTest.java
> [MNG-7780] DefaultArtifact.equals throws NullPointerException if o.version is null

- maven-core/src/test/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactoryTest.java
> [MNG-7639] Add unit test for DefaultRepositorySystemSessionFactory#newRepositorySession

- maven-core/src/main/java/org/apache/maven/plugin/PluginValidationManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedCoreExpressionValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/Maven2DependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/Maven3CompatDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenMixedDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/MavenScopeDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/PlexusContainerDefaultDependenciesValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/ReadOnlyPluginParametersValidator.java
Changes:
* introduce "internal" (to project) and "external" aspect
* make "inline" default as it was in 3.9.0 and 3.9.1
* remove "default" report level
* summary and verbose reports "internal only" or ALL issues
Example of outputs while building maven-3.8.x:
https://gist.github.com/cstamas/defd6a52939f5a277bf5fc669c01aedb
---
https://issues.apache.org/jira/browse/MNG-7791
> [MNG-7791] Split validation issues by "locality" aspect

- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7796
> [MNG-7796] Be lenient when using toRealPath

- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelBuildingRequest.java
- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/AbstractStringBasedModelInterpolator.java
- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/ProblemDetectingValueSource.java
- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/StringVisitorModelInterpolator.java
- maven-model-builder/src/test/java/org/apache/maven/model/interpolation/AbstractModelInterpolatorTest.java
This reverts commit b2a21f12f8a0598dd4a286177e340bda0148e9ba.
JIRA issue: https://issues.apache.org/jira/browse/MNG-7604
> [MNG-7604] Removal of pom.* interpolation makes some older plugins defunct

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/LocalSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/LocalSnapshotMetadataGenerator.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadataGenerator.java
- maven-resolver-provider/src/test/java/org/apache/maven/repository/internal/RemoteSnapshotMetadataTest.java
JIRA issue: https://issues.apache.org/jira/projects/MNG/issues/MNG-7548
> [MNG-7548] Kill off "legacy" repository metadata support

- maven-core/src/main/java/org/apache/maven/configuration/internal/DefaultBeanConfigurator.java
- maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedConverterLookup.java
JIRA issue [MNG-7751](https://issues.apache.org/jira/browse/MNG-7751)
This PR provides the ability to inject an `XmlNode` object into a plugin.  This can be currently done by injecting a `PlexusConfiguration`, but injecting an `XmlNode` ensures there's no dependency on the internal plexus configuration bits and limits the plugin exposure to the maven v4 api.
> [MNG-7751] Provide a way to inject XmlNode into plugins

- maven-bom/pom.xml
- pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7816
> [MNG-7816] Bump parent pom from 39 to 40

- pom.xml
Resolver 1.9.11 release notes:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12353188
---
> [MNG-7800] Bump maven-resolver from 1.9.10 to 1.9.11

- pom.xml
Update parent to 40. Also align plugin requirements with those from parent.
This lowers plugin validation "external" warnings from 12 to 3 (site, plexus-component-metadata and rat).
---
https://issues.apache.org/jira/browse/MNG-7816
> [MNG-7816] Update parent to 40, align maven requirements with those from plugins

- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilder.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilderRequest.java
- api/maven-api-settings/src/main/mdo/settings.mdo
- maven-compat/src/main/java/org/apache/maven/settings/DefaultMavenSettingsBuilder.java
- maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequest.java
- maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/CliRequest.java
- maven-embedder/src/main/java/org/apache/maven/cli/configuration/SettingsXmlConfigurationProcessor.java
- maven-settings-builder/pom.xml
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsBuilder.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsBuildingRequest.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/SettingsBuilder.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/SettingsBuildingRequest.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/validation/DefaultSettingsValidator.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/validation/SettingsValidator.java
This add support for project specific settings using:
* a default location of `${session.rootDirectory}/.mvn/settings.xml`
* an alternate location specified by `-ps` or `--project-settings` and resolved against the current dir if provided with a relative path
Note that project settings have some limitations:
* no `localRepository`
* no `interactiveMode`
* no `offline`
* no `proxies`
* no `server[x].username`, `server[x].password`, `server[x].privateKey`, `server[x].passphrase`, `server[x].filePermissions`, `server[x].directoryPermissions`
* no `usePluginRegistry`
Simple IT provided with https://github.com/apache/maven-integration-testing/pull/265
===
Related discussions to be considered (but note that this PR does not depend on the following):
* …
> [MNG-5659] Provide project-specific settings located in ${session.rootdir}/.mvn/settings.xml by default

- apache-maven/src/assembly/maven/conf/settings.xml
- api/maven-api-settings/pom.xml
- api/maven-api-settings/src/main/mdo/settings.mdo
- maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequestPopulator.java
- maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
- maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
- maven-embedder/src/main/java/org/apache/maven/cli/configuration/SettingsXmlConfigurationProcessor.java
- maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
- maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsBuilder.java
- maven-settings-builder/src/main/java/org/apache/maven/settings/merge/MavenSettingsMerger.java
- maven-settings-builder/src/test/java/org/apache/maven/settings/validation/DefaultSettingsValidatorTest.java
- maven-settings/pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-4645
IT PR: https://github.com/apache/maven-integration-testing/pull/266
Supersedes: https://github.com/apache/maven/pull/419
> [MNG-7059][MNG-4645] Move Central repo definition out of Maven's core so it can be more easily changed

- maven-model-transform/src/main/java/org/apache/maven/model/transform/BuildToRawPomXMLFilterFactory.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/ModelVersionXMLFilter.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/pull/BufferingParser.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/pull/NodeBufferingParser.java
- maven-model-transform/src/test/java/org/apache/maven/model/transform/ModelVersionXMLFilterTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7805
The downside of this PR is that if the build/consumer feature is enabled, all poms will be parsed as events and kept in memory by the `ModelVersionXMLFilter`.  The reason is that in theory, the `modelVersion` element can be the last element of the root `project` element.  Given the way the build/consumer POM feature is implemented, the same mechanism is used to read the POM (i.e. xml to object model) and rewrite it (when installing/deploying), so that the transformed XML has to be _clean_ wrt formatting, etc...
A possible performance improvement would be to have filters operate in two modes, the first one during the first phase (I.e. xml element ordering, formatting is irrelevant, and this phase could even be done on the object …
> [MNG-7805] Make the modelVersion optional when using build pom

- maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
- maven-xml-impl/src/test/java/org/apache/maven/internal/xml/XmlNodeImplTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7632
> [MNG-7632] Regression: combine.children breaks when combining executions

- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
> [MNG-7714] Fixed a scenario in version sorting where sp1 is less than final

- pom.xml
Fixes https://issues.apache.org/jira/browse/MNG-7818
Removed exclusion of hamcrest from JUnit 4
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
> [MNG-7818] Removed exclusion of hamcrest from junit 4

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
Changes:
* always parse it at session start
* hence, will WARN if needed there as well, and will warn once
* do not re-parse and possibly warn always, reuse parsed enum
---
https://issues.apache.org/jira/browse/MNG-7823
> [MNG-7823] Improve plugin validation level parsing

- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7228
IT PR: https://github.com/apache/maven-integration-testing/pull/273
> [MNG-7228] MavenProject.getOriginalModel returns interpolated parts

- maven-model/src/test/java/org/apache/maven/model/DependencyManagementTest.java
- maven-model/src/test/java/org/apache/maven/model/ModelTest.java
- src/mdo/model-v3.vm
JIRA issue: https://issues.apache.org/jira/browse/MNG-7834
The flatten-maven-plugin fails with a NPE:
```
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.5.0:flatten (default-cli) on project camel: failed to create a clean pom: Cannot invoke "java.util.List.stream()" 
because "dependencies" is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.5.0:flatten (default-cli) on project camel: failed to create a clean 
pom
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:341)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:324)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at …
```
> [MNG-7834] Fix NullPointerException in flatten-maven-plugin

- pom.xml
Update due to CVE-2023-2976.
See https://issues.apache.org/jira/browse/MNG-7828 for more context.
--
Doing on master too, following @cstamas instructions at https://github.com/apache/maven/pull/1189#issuecomment-1611048094
> [MNG-7828] Bump guava from 30.1-jre to 32.0.1-jre

- pom.xml
Update due to CVE-2023-2976.
See https://issues.apache.org/jira/browse/MNG-7828 for more context.
> [MNG-7828] Bump guava from 31.1-jre to 32.0.1-jre

- maven-core/src/main/java/org/apache/maven/exception/DefaultExceptionHandler.java
- maven-core/src/test/java/org/apache/maven/exception/DefaultExceptionHandlerTest.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java
- maven-slf4j-provider/src/main/java/org/slf4j/impl/MavenSimpleLogger.java
When there is a loop in throwable causes, DefaultExceptionHandler falls into an endless loop to produce message. Use plain hashSet to gather processed throwable instances to break out.
---
https://issues.apache.org/jira/browse/MNG-7846
> [MNG-7846] Break out of endless loop

- maven-core/src/test/projects/lifecycle-executor/project-with-inheritance/pom.xml
- maven-core/src/test/projects/plugin-manager/project-with-inheritance/pom.xml
- maven-core/src/test/resources-project-builder/micromailer/pom.xml
(that are not applicable, but look ugly).
These tests are NOT built, but are taken from real projects several years ago, and used in POM related UTs.
Hence, for example update of velocity is completely okay, even if in "real life" it would not compile.
> Fix dependabot alerts

- maven-artifact/src/main/java/org/apache/maven/artifact/handler/ArtifactHandler.java
Noticed this was a unclear and out of date
> Improve API doc for ArtifactHandler

- api/maven-api-model/src/main/mdo/maven.mdo
- maven-core/src/main/java/org/apache/maven/project/ReactorModelPool.java
- maven-core/src/test/java/org/apache/maven/internal/transformation/ConsumerPomArtifactTransformerTest.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultBuildPomXMLFilterFactory.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultTransformerContext.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/FileModelSource.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelSource3.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/TransformerContext.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/BuildToRawPomXMLFilterFactory.java
- maven-model-transform/src/main/java/org/apache/maven/model/transform/ParentXMLFilter.java
- maven-model-transform/src/test/java/org/apache/maven/model/transform/ParentXMLFilterTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7862
IT PR: https://github.com/apache/maven-integration-testing/pull/289
There are a few places where the `pom.xml` file name is hardcoded. There's a known interface to locate those, so those references should be cleaned.
One IT has to be adjusted (see PR) because the default value in the model is changed from `../pom.xml` to `..` for the parent `relativePath` default value.
> [MNG-7862] The ModelLocator should always be used when locating pom.xml

- api/maven-api-core/src/main/java/org/apache/maven/api/services/MessageBuilder.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultMessageBuilder.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/jansi/JansiMessageBuilder.java
- maven-embedder/src/main/java/org/apache/maven/cli/jansi/Style.java
- maven-slf4j-provider/src/main/java/org/slf4j/impl/MavenSimpleLogger.java
> [MNG-7822] Add support for TRACE logging level (with style "bold,magenta") 

- api/maven-api-model/src/main/mdo/maven.mdo
- maven-core/src/main/java/org/apache/maven/artifact/resolver/filter/ExclusionArtifactFilter.java
- maven-core/src/test/java/org/apache/maven/artifact/resolver/filter/ExclusionArtifactFilterTest.java
Excluding a bunch of dependencies is quite verbose. A simple glob pattern would really help.
> [MNG-7843] Allow glob patterns in dependency exclusions

- apache-maven/pom.xml
- apache-maven/src/main/appended-resources/licenses/unrecognized-asm-9.5.txt
- maven-core/pom.xml
- maven-embedder/pom.xml
- maven-model-builder/pom.xml
- maven-resolver-provider/pom.xml
- pom.xml
- [MNG-7587] Upgrade to sisu 0.9.0.M2
- Use a non shaded version of asm in guice and sisu
- Fix missing asm for maven-resolver-provider
- IT PR: https://github.com/apache/maven-integration-testing/pull/290
I've extracted the use of a standalone ASM version as JDK 17 support is already covered by the upgrade to 0.9.0.M2.
To support JDK >= 19, we need ASM 9.5 and we thus need to use a standalone version of ASM and upgrade it.
This is a follow-up to https://github.com/apache/maven/pull/1119
> [MNG-7792] Use a standalone asm version

- maven-repository-metadata/src/main/mdo/metadata.mdo
- maven-repository-metadata/src/site/apt/index.apt
The modello generated classes should not be deprecated, and they are in use. 
---
https://issues.apache.org/jira/browse/MNG-7870
> [MNG-7870] Undeprecate G level metadata

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadataGeneratorFactory.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/SnapshotMetadataGeneratorFactory.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/VersionsMetadataGeneratorFactory.java
Maven Resolver Provider: get rid of name free string literals.
---
https://issues.apache.org/jira/browse/MNG-7874
> [MNG-7874] Use name constants instead of free string literals

- api/maven-api-spi/pom.xml
- api/pom.xml
- maven-bom/pom.xml
- maven-core/pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7810
This PR provides an empty placeholder for the Maven 4 SPI.
The package is `org.apache.maven.api.spi` and should contain all services that can be easily provided by extensions.
> [MNG-7810] Provide a SPI for the v4 api

- maven-embedder/src/main/java/org/apache/maven/cli/transfer/AbstractMavenTransferListener.java
https://issues.apache.org/jira/browse/MNG-7875
before:
after: 
(initial proposal:
)
> MNG-7875 colorize transfer messages

- .github/workflows/maven.yml
- api/maven-api-model/pom.xml
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ModelParser.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ModelParserException.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilderFactory.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelProcessor.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7836
IT PR: https://github.com/apache/maven-integration-testing/pull/276
> [MNG-7836] Support alternative syntaxes for POMs

- maven-core/src/main/java/org/apache/maven/artifact/handler/providers/BomArtifactHandlerProvider.java
- maven-core/src/main/java/org/apache/maven/internal/transformation/ConsumerPomArtifactTransformer.java
- maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/BomLifecycleMappingProvider.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7879
Doc PR: https://github.com/apache/maven-site/pull/451
The purpose of the BOM packaging is to more cleanly identify POM that will be consumed as BOM from POM that will be used as parents.  The BOMs can be turned into a consumer POM, whereas parents can not lose any information.
> [MNG-7879] Add a bom packaging

- api/maven-api-core/src/main/java/org/apache/maven/api/services/SuperPomProviderException.java
- maven-core/src/main/java/org/apache/maven/DefaultMaven.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSuperPomProvider.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/superpom/DefaultSuperPomProvider.java
- maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.1.0.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7893
Btw, I wonder if the recent changes such as https://github.com/apache/maven/pull/1139 and https://github.com/apache/maven/pull/1085 should be updated to only affect the 4.1.0 superpom...  Thoughts welcomed.
> [MNG-7893] Allow versioning the superpom according to the model version

- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluator.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4.java
- maven-core/src/main/java/org/apache/maven/plugin/ReflectionValueExtractor.java
As indicated at https://github.com/apache/maven/pull/812#discussion_r990825335
If the interpolated string is `${settings.foo}`, the expression is `settings.foo` and we pass `ettings.foo` to the `ReflectionValueExtractor`. It's working because the call just ignore whatever is on the left of the first `.`...
> Fix unneeded/wrong substring calls in expression evaluation and put back weak references in cache

- maven-compat/src/main/java/org/apache/maven/repository/metadata/MetadataGraph.java
Avoid creating a StringBuilder instance when not needed to reduce
temporary objects creation
> [MNG-7899] Various memory usage improvements 2

- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileSelector.java
It uses immutable list and while it suggests it allows this below, it actually fails on constructs like this (worse even, it compiles ok, but fails runtime only): 
```
new DefaultProfileSelector()
.addProfileActivator(new JdkVersionProfileActivator())
.addProfileActivator(new PropertyProfileActivator())
```
As default ctor creates immutable list, but API kinda suggests this is ok. So either this PR should go in, or just remove `addProfileActivator` and make class immutable. Am fine with both (unless something else requires it to be extended).
---
https://issues.apache.org/jira/browse/MNG-7910
> [MNG-7910] DefaultProfileSelector empty ctor uses immutable list

- pom.xml
Now that JDK 11 is required, we use the `release` option for compiling and it already takes care about signatures.
> [MNG-7821] Remove useless animal-sniffer-plugin

- apache-maven/src/assembly/maven/bin/m2.conf
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Jira issue: [MNG-7772](https://issues.apache.org/jira/browse/MNG-7772)
Enables to register extensions through the ${user.home}/.m2 directory. An extension can be placed in an ext directory in the .m2 directory or by adding a extensions.xml file in the .m2 directory
> [MNG-7772] Allow to register maven core extension in .m2 directory instead of MAVEN_HOME

- maven-compat/src/test/java/org/apache/maven/artifact/resolver/ArtifactResolverTest.java
- maven-embedder/src/main/java/org/eclipse/sisu/plexus/PlexusXmlBeanConverter.java
- maven-model/src/main/java/org/apache/maven/model/InputLocation.java
@elharo if you could review once more for https://issues.apache.org/jira/browse/MNG-6847 
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/SEvWu02zw?organizationId=QXBhY2hlIE1hdmVu
> [MNG-6847] Use diamond operator

- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
https://issues.apache.org/jira/browse/MNG-7899
Reuse a StringBuilder in a for loop by setting its lenght to zero.
Help reduce temporary objects creation.
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [X ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [X ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).
> [MNG-7899] Various memory usage improvements 3

- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSession.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4.java
Maven 4 api is still in alpha, it would be better to not start adding deprecated methods now...
> Get rid of deprecated method in the v4 Session interface

- api/maven-api-core/src/main/java/org/apache/maven/api/services/MessageBuilder.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultMessageBuilder.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/jansi/JansiMessageBuilder.java
- maven-slf4j-provider/src/main/java/org/slf4j/impl/MavenSimpleLogger.java
https://issues.apache.org/jira/browse/MNG-7899
Multiple optimizations :
- renderLevel() method use static constants instead of rebuilding the
strings on each call
- replace + operator usage with more PrintStream.print() calls to reduce
temporary strings creation
- reduce usage of MessageBuilder.a() method usage with more
PrintStream.print() calls to reduce temporary strings creation
- replace the builder() method with a static import
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [X ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January …
> [MNG-7899] Various memory usage improvements 5

- maven-plugin-api/pom.xml
Since the v3 model has been replaced by the v4 model, that would be in line.  We can revisit and restore full compatibility later if needed.
JIRA issue: https://issues.apache.org/jira/browse/MNG-7916
> [MNG-7916] Simply get rid of LifecycleMappingsXpp3Reader/Writer

- pom.xml
To version that supports gleaning JSR330 component classes up to Java 19. The reasoning of this change is only to allow 3rd party Maven plugins/Maven extensions/other JSR330 components (managed by Maven embedded Sisu) to use bytecode newer that Java 14 (Sisu 0.3.5).
---
https://issues.apache.org/jira/browse/MNG-7913
> [3.9.x] [MNG-7913] Upgrade Sisu version

- api/maven-api-model/pom.xml
- api/maven-api-model/src/main/mdo/maven.mdo
- maven-core/src/main/java/org/apache/maven/internal/transformation/ConsumerPomArtifactTransformer.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingHelper.java
- maven-embedder/pom.xml
- maven-model/pom.xml
- src/mdo/model-v3.vm
Fix model doc generation, change the intermediate model to use 4.0.99 and align the new model to 4.1.0
This requires https://github.com/apache/maven-integration-testing/pull/315 to pass ITs...
> Use 4.0.99 as as intermediate model to keep 4.1.0 for the Maven 4.x model

- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/test/java/org/apache/maven/internal/transformation/ConsumerPomArtifactTransformerTest.java
- maven-model-builder/pom.xml
- maven-model-builder/src/main/java/org/apache/maven/model/building/BuildModelSourceTransformer.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultTransformerContext.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultTransformerContextBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/Graph.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelCache.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/TransformerContext.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileInjector.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileSelector.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/ProfileInjector.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/ProfileSelector.java
- maven-model-builder/src/test/java/org/apache/maven/model/building/BuildModelSourceTransformerTest.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultModelCache.java
Same PR as #803 but reformatted.
> [MNG-7615] Multithreaded model builder

- maven-core/pom.xml
- pom.xml
From 3.8.7 to 3.8.8, but these two minors have binary incompatibilities (in ctor), so ignores updated as well.
---
https://issues.apache.org/jira/browse/MNG-7961
> [MNG-7961] Up japicmp baseline

- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverResult.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactDeployer.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactResolver.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyCollector.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/SetWithResolutionResult.java
- maven-core/src/main/java/org/apache/maven/project/artifact/DefaultProjectArtifactsCache.java
- maven-core/src/main/java/org/apache/maven/project/artifact/ProjectArtifactsCache.java
- maven-core/src/test/java/org/apache/maven/project/artifact/DefaultProjectArtifactsCacheTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7966
This is a bit of an ugly hack, but I don't think we should modify the Maven 3 api for the `ProjectArtifactCache`, so I introduced:
```
interface ArtifactsSetWithResult extends Set<Artifact> {
DependencyResolutionResult getResult();
}
```
If that's deemed too ugly, I can modify the `ProjectArtifactCache` to add a `DependencyResolutionResult` in the `CacheRecord` maybe...
> [MNG-7966] Augment api to provide a Map<Dependency, Path> in the resolution result

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenArtifactRelocationSource.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/relocation/DistributionManagementArtifactRelocationSource.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/relocation/UserPropertiesArtifactRelocationSource.java
I had this change parked on laptop, assumed was pushed :(
The "ban" was unfinished and wrong: what is actually needed is to have exception with proper explanation instead.
---
https://issues.apache.org/jira/browse/MNG-7959
---
Now the command line:
```
$ mvn clean install -Dmaven.relocations.entries="org.slf4j:*:*>>"
```
(global ban of ANY org.slf4j group artifact) causes output like this:
https://gist.github.com/cstamas/c57efa1e1d56ca605fdfa88c431eab97
> [MNG-7959] User controlled relocations Addendum

- maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/MojoDescriptor.java
- maven-plugin-api/src/test/java/org/apache/maven/plugin/descriptor/MojoDescriptorTest.java
It may lead to confusion as parameters (list) and
parametersMap (map) may "fall apart" easily.
Also, parametersMap did not honor parameter
ordering while parameters list makes it look
that order is important.
Simply, rebuild the map always and retain
ordering as well.
Added UT and also removed some cruft provided
by java8.
---
https://issues.apache.org/jira/browse/MNG-7309
Best practice is to use the JIRA issue title in both the pull …
> [MNG-6776] Inconsistent list of parameters for MojoDescriptor (#584)

- maven-core/src/main/java/org/apache/maven/RepositoryUtils.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilderTest.java
- maven-core/src/test/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4Test.java
- maven-embedder/src/test/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListenerTest.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenRepositorySystemUtils.java
- pom.xml
Update to alpha-6. 
Also, move off from deprecated default ctor of def repo session in tests.
---
https://issues.apache.org/jira/browse/MNG-7994
> [MNG-7994] Update to Resolver 2.0.0-alpha-6

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultTransformerContextBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/Graph.java
- maven-model-builder/src/test/java/org/apache/maven/model/building/GraphTest.java
- maven-model-builder/src/test/resources/dag.txt
Simplify graph.
First step before making it concurrent if possible.
> Simplify graph

- maven-core/src/main/java/org/apache/maven/DefaultMaven.java
- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
- maven-core/src/main/java/org/apache/maven/internal/aether/MavenChainedWorkspaceReader.java
- maven-core/src/test/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactoryTest.java
- maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java
Maven4 seems sets but then drops/overrides some workspace readers. Partially due hazy borders who or what manages them, as role is split between session factory and session factory caller.
Changes:
* session factory does NOTHING re workspace readers, it becomes fully the caller duty
* two spots calling session factory (default maven, extension bootstrap) are now fully in charge to properly setup workspace readers
Co-authored-by: Jonas Rutishauser <jonas.rutishauser@alumni.ethz.ch>
---
https://issues.apache.org/jira/browse/MNG-8005
> [MNG-8005] Fix workspace reader drop bug

- api/maven-api-core/src/main/java/org/apache/maven/api/Project.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectManager.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProject.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectManager.java
Introduce new method that returns POM and project Artifact in sensible manner (so install or deploy and other does not need to figure out anything).
Also, javadoc the class.
---
https://issues.apache.org/jira/browse/MNG-8023
> [MNG-8023] New method + javadoc on Project

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/scopes/MavenDependencyScopes.java
- pom.xml
Update to Resolver 2.0.0-alpha-7, sort out TODO.
This is also one simple change "sneaked in" for RAT, to ignore local `.mvn` that is unrelated to all this, but does not make any harm. In turn, it allows dev local checkout to have various stuff set without
decorating those with headers or fighing RAT plugin.
---
https://issues.apache.org/jira/browse/MNG-8035
> [MNG-8035] Update to Resolver 2.0.0-alpha-7

- api/maven-api-core/src/main/java/org/apache/maven/api/Project.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilder.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectManager.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProject.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectManager.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSession.java
- maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
- maven-core/src/test/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4Test.java
Follow-up to https://github.com/apache/maven/pull/1387
JIRA issue: https://issues.apache.org/jira/browse/MNG-8037
> [MNG-8037] Restrict project to the entity being built and make it immutable

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelProblem.java
- maven-model-builder/src/main/java/org/apache/maven/model/composition/DefaultDependencyManagementImporter.java
- maven-model-builder/src/test/java/org/apache/maven/model/building/DefaultModelBuilderTest.java
- maven-model-builder/src/test/resources/poms/depmgmt/distant-import.xml
- maven-model-builder/src/test/resources/poms/depmgmt/import.xml
- maven-model-builder/src/test/resources/poms/depmgmt/junit-0.1.xml
- maven-model-builder/src/test/resources/poms/depmgmt/junit-0.2.xml
- maven-model-builder/src/test/resources/poms/depmgmt/other-import.xml
- maven-model-builder/src/test/resources/poms/depmgmt/root-dep-first.xml
- maven-model-builder/src/test/resources/poms/depmgmt/root-dep-last.xml
- maven-model-builder/src/test/resources/poms/depmgmt/root-distance-explicit.xml
- maven-model-builder/src/test/resources/poms/depmgmt/root-distance.xml
- maven-model-builder/src/test/resources/poms/depmgmt/root-two-imports.xml
The artificial (or "bolted on") scope "import" behaves wildly differently that rest of Maven, causes surprise to our users. For start, we should emit "actionable" warnings about these, ultimate goal is to align this behaviour with "maven way" of working ("closest occurence wins" vs current weird "direct occurrence then first occurence wins" strategy)
---
https://issues.apache.org/jira/browse/MNG-7854
> [MNG-7854] Warn if imported dep is ignored

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectDependenciesResolver.java
https://issues.apache.org/jira/browse/MNG-8045
> [MNG-8045] Use DependencyGraphDumper instead of own implementation

- api/maven-api-model/src/main/mdo/maven.mdo
- api/maven-api-settings/src/main/mdo/settings.mdo
- maven-core/src/main/java/org/apache/maven/settings/SettingsUtils.java
- maven-core/src/main/java/org/apache/maven/settings/SettingsUtilsV4.java
- maven-core/src/test/java/org/apache/maven/settings/SettingsUtilsTest.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/PackagingProfileActivator.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8053
Following up https://issues.apache.org/jira/browse/MNG-6609, we should now make the packaging activation for profiles a first class citizen in the model.
> [MNG-8053] Profile activation by packaging in the POM

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadataGenerator.java
- maven-resolver-provider/src/test/java/org/apache/maven/repository/internal/RemoteSnapshotMetadataTest.java
For snapshot deploys
---
https://issues.apache.org/jira/browse/MNG-8054
> [MNG-8054] Ability to force build number

- apache-maven/src/site/site.xml
- maven-artifact/src/site/site.xml
- maven-builder-support/src/site/site.xml
- maven-compat/src/site/site.xml
- maven-core/src/main/java/org/apache/maven/bridge/MavenRepositorySystem.java
- maven-core/src/site/site.xml
- maven-embedder/src/site/site.xml
- maven-model-builder/src/site/site.xml
- maven-model/src/site/site.xml
- maven-plugin-api/src/site/site.xml
- maven-repository-metadata/src/site/site.xml
- maven-resolver-provider/src/site/site.xml
- maven-settings-builder/src/site/site.xml
- maven-settings/src/main/mdo/settings.mdo
- maven-settings/src/site/apt/index.apt
- maven-settings/src/site/site.xml
- maven-slf4j-provider/src/site/site.xml
- src/site/site.xml
https://issues.apache.org/jira/browse/MNG-8029
> [MNG-8029] improve documentation about mirror settings

- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/OperatingSystemProfileActivator.java
- maven-model-builder/src/main/java/org/apache/maven/utils/Os.java
- maven-model-builder/src/test/java/org/apache/maven/model/profile/activation/OperatingSystemProfileActivatorTest.java
OS version
This requires using the reserved prefix "regex:" in the version element.
please …
> [MNG-5726] Support regular expression matching in profile activation for

- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- maven-core/src/main/java/org/apache/maven/internal/impl/AbstractSession.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyCollector.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProject.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
Before the upgrade to maven-resolver 4.0.0-alpha-7, it was necessary to go through the maven 3 layer to resolve project dependencies.
> Use v4 api to resolve project dependencies

- api/maven-api-core/src/main/java/org/apache/maven/api/ExtensibleEnum.java
- api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/PathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Type.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverResult.java
- maven-artifact/src/main/java/org/apache/maven/artifact/handler/ArtifactHandler.java
- maven-artifact/src/test/java/org/apache/maven/artifact/handler/ArtifactHandlerMock.java
- maven-compat/src/test/java/org/apache/maven/repository/TestArtifactHandler.java
- maven-core/src/main/java/org/apache/maven/artifact/handler/DefaultArtifactHandler.java
- maven-core/src/main/java/org/apache/maven/artifact/handler/manager/DefaultArtifactHandlerManager.java
- maven-core/src/main/java/org/apache/maven/internal/aether/TypeRegistryAdapter.java
- maven-core/src/main/java/org/apache/maven/internal/impl/AbstractSession.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependency.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolverResult.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTypeRegistry.java
- maven-core/src/main/java/org/apache/maven/internal/impl/PathModularization.java
- maven-core/src/main/java/org/apache/maven/internal/impl/PathModularizationCache.java
- maven-core/src/main/java/org/apache/maven/internal/transformation/impl/TransformedArtifactHandler.java
- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- maven-core/src/main/java/org/apache/maven/project/artifact/PluginArtifact.java
- maven-core/src/main/java/org/apache/maven/project/artifact/ProjectArtifact.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestArtifactHandler.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/ArtifactDescriptorReaderDelegate.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/type/DefaultType.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/type/DefaultTypeProvider.java
#1378  merged with master and pushed to maven so that we can actually collaborate on it (as the branch for #1378 is not writable)
> [MNG-8015] Control the type of path where each dependency can be placed

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelBuilder.java
This should be in fact prevented.
Also, model builder missed File uses are corrected.
---
https://issues.apache.org/jira/browse/MNG-8012
> [MNG-8012] Warn if in-reactor BOM import happens

- maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java
- maven-plugin-api/src/main/mdo/plugin.mdo
https://issues.apache.org/jira/browse/MNG-4840
but not integrated in documentation until now https://maven.apache.org/ref/3.9.6/maven-plugin-api/plugin.html
> [MNG-4840] document requiredMavenVersion in plugin descriptor

- maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/Builder.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/singlethreaded/SingleThreadedBuilder.java
- maven-core/src/site/apt/configuration-management.apt
- maven-core/src/site/apt/offline-mode.apt
- maven-embedder/src/main/java/org/eclipse/sisu/plexus/PlexusXmlBeanConverter.java
> Typo fixes: remove repetitive words

- maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java
- maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptorBuilder.java
- maven-plugin-api/src/main/mdo/plugin.mdo
fix mistake done in #1444 and clarify in javadoc
> [MNG-4840] fix requiredMavenVersion description #1444

- api/maven-api-core/src/main/java/org/apache/maven/api/Type.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/type/DefaultTypeProvider.java
These are dependency types to be used when dependency is "self contained", or is wanted be used as such: handle if like it has no dependencies, if any.
---
https://issues.apache.org/jira/browse/MNG-8089
> [MNG-8089] Introduce fat-JAR types

- maven-core/pom.xml
- maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/project/ProjectModelResolver.java
- maven-core/src/test/java/org/apache/maven/project/ProjectModelResolverTest.java
- maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
- maven-jline/src/main/java/org/apache/maven/jline/FastTerminal.java
- maven-jline/src/main/java/org/apache/maven/jline/MessageUtils.java
- maven-slf4j-provider/src/main/java/org/apache/maven/slf4j/MavenSimpleLogger.java
- maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
- src/mdo/transformer.vm
This saves 15-20% on the startup time on the maven project for example.
On bigger projects, most of time is spent in loading projects, so this becomes negligible.
> Improve maven startup time

- maven-api-impl/pom.xml
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
- maven-resolver-provider/pom.xml
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenRepositorySystemSupplier.java
- pom.xml
~~Currently is under vote, so using staging repository, that will be removed once/if vote passes.~~ Vote passed, but Maven Central sync is busted.
Changes:
* update Resolver to 2.0.0-alpha-10
* Maven must not depend on supplier, it should be other way around.
Once this is merged (and released), Resolver gets these changes:
https://github.com/apache/maven-resolver/pull/454
---
https://issues.apache.org/jira/browse/MNG-8091
> [MNG-8091] Update Resolver to 2.0.0-alpha-10

- .github/workflows/maven.yml
Avoid warning like:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
and be up to-day
> Update GitHub actions to v4

- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/SimplexTransferListener.java
- maven-embedder/src/test/java/org/apache/maven/cli/transfer/SimplexTransferListenerTest.java
Backport of simplex transfer listener.
---
https://issues.apache.org/jira/browse/MNG-8031
> [MNG-8031] Backport concurrent friendly transport listener

- maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequest.java
- maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java
- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Backport of the Maven4 feature: ignore transitive repositories.
---
https://issues.apache.org/jira/browse/MNG-8030
> [MNG-8030] Backport itr: ignore transitive repositories

- apache-maven/README.txt
The site already contains all the required information, point user at it. It would be insane for us to maintain all these information here as well (as example shows, it was totally outdated).
Keep it short, and just keep pointers to proper info sources.
---
https://issues.apache.org/jira/browse/MNG-8011
> [MNG-8011] Neuter the README

- .github/workflows/maven.yml
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/LocalSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/VersionsMetadata.java
As currently if given metadata serves multiple roles (G, A or V level), data loss occurs.
---
https://issues.apache.org/jira/browse/MNG-8106
> [3.9.x][MNG-8106] Fix metadata merge

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/LocalSnapshotMetadata.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/PluginsMetadata.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/RemoteSnapshotMetadata.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/VersionsMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/LocalSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/VersionsMetadata.java
As currently if given metadata serves multiple roles (G, A or V level), data loss occurs.
---
https://issues.apache.org/jira/browse/MNG-8106
> [MNG-8106] Fix metadata merge

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenRepositorySystemSupplier.java
- pom.xml
Update to Resolver 2.0.0-alpha-11 and restore renamed class.
---
https://issues.apache.org/jira/browse/MNG-8107
> [MNG-8107] Update Resolver 2.0.0-alpha-11

- maven-embedder/src/main/java/org/apache/maven/cli/CleanArgument.java
> Simplified redundant judgment

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
- maven-model-builder/src/test/java/org/apache/maven/model/validation/DefaultModelValidatorTest.java
- maven-model-builder/src/test/resources/poms/validation/raw-model/profile-activation-property-with-project-expressions.xml
Evaluate profile activations after having interpolated embedded property constructs.
please …
> [MNG-8081] interpolate available properties during default profile selection (Maven 4.x)

- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
fixes `./${user.home}` directory creation during tests execution
that is after running `mvn clean test`, I get
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
maven-api-impl/${user.home}/
```
> [MNG-8084] add system properties to test

- maven-core/src/main/java/org/apache/maven/plugin/version/internal/DefaultPluginVersionResolver.java
Produces output like this:
https://gist.github.com/cstamas/3ca4bc6cea5f701054061871b5db3f35
---
https://issues.apache.org/jira/browse/MNG-8117
> [MNG-8117] Maven PluginVersionResolver improvement

- api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/PathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Toolchain.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Type.java
- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/Log.java
- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/Mojo.java
- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/MojoException.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverResult.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolverResult.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/PathModularization.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/PathModularizationCache.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
- maven-embedder/src/main/java/org/fusesource/jansi/Ansi.java
- maven-model-builder/src/main/java/org/apache/maven/utils/Os.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/type/DefaultTypeProvider.java
This pull request makes the following changes in API related to `PathType`. Those changes are for supporting the development of the Maven compiler plugin:
* Add new artifact types for annotation processor paths:
* `PROCESSOR`
* `MODULAR_PROCESSOR`
* `CLASSPATH_PROCESSOR`
* Establish a relationship between `org.apache.maven.api.JavaPathType` and `javax.tools.StandardLocation`:
* New `location()` public method returning `Optional<JavaFileManager.Location>`.
* New `valueOf(JavaFileManager.Location location)` public static method (converse of the above).
* New _"Relationship with Java compiler standard location"_ section in class Javadoc.
* Modify the return type of `option(Iterable<? extends Path> paths)` from `String` to `String[]`.
* Delete `DependencyResolverResult.option(PathType)` …
> [MNG-8015] Adjustments in new API related to PathType

- maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
When building projects, the following can happen:
```
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] Total time:  3.423 s
[INFO] Finished at: 2024-05-13T10:12:27+02:00
[INFO] --------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.1.1:install (default-install) on project camel-util: Execution default-install of goal org.apache.maven.plugins:maven-install-plugin:3.1.1:install failed: 2 problems were …
```
> [MNG-8108] Fix problem when building the consumer pom

- api/maven-api-metadata/src/main/mdo/metadata.mdo
There is an NPE if existing metadata due bug of nx-staging-m-p had no prefix present.
---
https://issues.apache.org/jira/browse/MNG-8121
> [MNG-8121] Fix NPE in metadata merge

- maven-model-builder/pom.xml
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/ModelValidator.java
> [MNG-8050] emit warn in case of repo id clashes between settings and POM

- api/maven-api-core/src/main/java/org/apache/maven/api/services/LifecycleRegistry.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
- maven-compat/src/test/java/org/apache/maven/project/EmptyLifecycleBindingsInjector.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultPackagingRegistry.java
- maven-core/src/main/java/org/apache/maven/lifecycle/DefaultLifecycles.java
- maven-core/src/main/java/org/apache/maven/lifecycle/Lifecycle.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/ExecutionPlanItem.java
- maven-core/src/test/java/org/apache/maven/lifecycle/DefaultLifecyclesTest.java
- maven-core/src/test/java/org/apache/maven/lifecycle/MavenExecutionPlanTest.java
- maven-core/src/test/java/org/apache/maven/project/EmptyLifecycleBindingsInjector.java
IT PR: https://github.com/apache/maven-integration-testing/pull/342
> [MNG-8123] Fix Lifecycle in v3

- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
**Summary**
This pull request addresses the JIRA issue [MNG-7902](https://issues.apache.org/jira/browse/MNG-7902). The goal of this change is to enhance the readability and usability of the validation report by sorting the plugins in a case-insensitive manner. Currently, the report outputs the content of a set of plugins without sorting them, which can result in a random order, making it difficult for users to locate specific entries or identify patterns.
**Changes Made**
Added sorting logic: Implemented a sorting mechanism to order plugins case-insensitively in the validation report.
Updated `reportSessionCollectedValidationIssues` function: Modified this function to include the sorting logic for plugins before they are logged.
**Why This Change Is Necessary**
By sorting the plugins in …
> [MNG-7902] Sort plugins in the validation report

- .github/workflows/maven.yml
Can be useful when I want to trigger a build after IT changed.
> Allow to manually execute GitHub Action

- maven-core/src/main/java/org/apache/maven/exception/DefaultExceptionHandler.java
[MNG-5693] Remove unhelpful links that don't describe failure reasons from output
This removes these lines from the end of every failing build:
```
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
> [MNG-5693] Remove unhelpful links that don't describe failure reasons from output

- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/OperatingSystemProfileActivator.java
- maven-model-builder/src/test/java/org/apache/maven/model/profile/activation/OperatingSystemProfileActivatorTest.java
Backport of 0456c7c629d6fc872073268faeb77d2bde9a1b7d
---
https://issues.apache.org/jira/browse/MNG-8135
> [MNG-8135] Profile activation based on OS properties is no longer case insensitive

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultDependencyManagementImporter.java
- maven-model-builder/src/main/java/org/apache/maven/model/composition/DefaultDependencyManagementImporter.java
Fix grammar and whitespace in validation message.
To make …
> Fix grammar in validation message

- maven-core/src/main/java/org/apache/maven/exception/DefaultExceptionHandler.java
- maven-core/src/test/java/org/apache/maven/exception/DefaultExceptionHandlerTest.java
If there is a recursion in throwable causes, Maven will hang forever, instead to return.
---
https://issues.apache.org/jira/browse/MNG-8066
> [MNG-8066] Default exception handler does not handle recursion

- maven-model-builder/src/main/java/org/apache/maven/model/profile/DefaultProfileSelector.java
- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/JdkVersionProfileActivator.java
- maven-model-builder/src/test/java/org/apache/maven/model/profile/DefaultProfileSelectorTest.java
- maven-model-builder/src/test/java/org/apache/maven/model/profile/activation/JdkVersionProfileActivatorTest.java
If property `java.version` is in unexpected format, the activator throws `NumberFormatEx`, that in turn, is caught and reported by `DefaultProfileSelector` w/o any cause.
These should be cleanly reported instead: report that `java.version` property is in "unexpected format", and also report why was there are failure to evaluate a property activation.
Note 1: Maven allows `-Djava.version` override (!!!), this is exactly what IT MNG-3746 does, but the `NumberFormatEx` went unnoticed, was swallowed, no cause reported.
Note 2: This bug was revealed by #1555 as it reported the issue, and later "asserted error free log" which was not error-free. Hence, this bug was simply revealed by improved logging on unrelated issue.
---
https://issues.apache.org/jira/browse/MNG-8142
> [MNG-8142] Hidden bug: JDK profile activator throw NumberFormatEx

- maven-artifact/pom.xml
- maven-artifact/src/main/java/org/apache/maven/artifact/ArtifactUtils.java
- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/DefaultArtifactVersion.java
- maven-artifact/src/test/java/org/apache/maven/artifact/versioning/DefaultArtifactVersionTest.java
- maven-core/pom.xml
- maven-core/src/main/java/org/apache/maven/configuration/DefaultBeanConfigurationRequest.java
- maven-core/src/main/java/org/apache/maven/rtinfo/internal/DefaultRuntimeInformation.java
- maven-core/src/test/java/org/apache/maven/rtinfo/internal/DefaultRuntimeInformationTest.java
- maven-embedder/pom.xml
- maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/AbstractMavenTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListener.java
- maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
- pom.xml
For start, keeping almost same LOC but the distro zip lost almost 1 MB (was 10MB now is 9MB). Second, am really unsure why it was introduced in the first place, as it merely caused confusion, over StringUtils for example.
---
https://issues.apache.org/jira/browse/MNG-8146
> [MNG-8146] Drop commons-lang

- maven-core/src/main/java/org/apache/maven/internal/aether/LoggingRepositoryListener.java
The info is there, but we redirect user to rinse-repeat in debug mode, that that creates a TON of output.
All is there, just tell why.
---
https://issues.apache.org/jira/browse/MNG-8140
> [MNG-8140] Always tell why model was discarded as "invalid"

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/test/java/org/apache/maven/model/building/DefaultModelBuilderTest.java
- maven-model-builder/src/test/resources/poms/building/badprofiles.xml
And not rely that model was validated, which is not true in some cases. Model builder can still easily detect issues with models while building them.
Provides "escape hatch" for projects stuck on invalid models in form of user property that can be enabled with `-Dmaven.modelBuilder.failOnInvalidModel=false`, this reverts to _old_ behaviour of maven, and the JavaFX reproducer goes back to error "unable to resolve" errors with uninterpolated `${javafx.platform}` property as classifier.
---
https://issues.apache.org/jira/browse/MNG-8141
> [MNG-8141] Model builder should report problems it finds during build

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/BuildModelTransformer.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
> Move modelVersion inference to model builder so that it is also effective on consumer models

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelBuildingException.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
Fix and improvement in one PR as they are closely related.
First, this PR restores the ability (broken by MNG-8081) to calculate Profile activation for POMs with duplicate Profile ID.
Second, this PR improves UX by warning them about invalid models in their build.
The reproducer now looks like this:
https://gist.github.com/cstamas/165a610b233f4c03e381a0a2697903eb
Notice:
* WARNs issued about models (all Maven versions are mute about this)
* still, property `${javafx.platform}` properly evaluated just like in 3.9.6 (but not in 3.9.7)
* build succeeds (fails in 3.9.7)
---
https://issues.apache.org/jira/browse/MNG-8147
https://issues.apache.org/jira/browse/MNG-8141
> [MNG-8141][MNG-8147] Restore profile ID invariance but warn if duplicate IDs present

- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
No (logic) change, merely moved the new code to proper place (validation) to not piggy back onto processing: this is much cleaner.
---
https://issues.apache.org/jira/browse/MNG-8141
Inspired by suggestions in master PR https://github.com/apache/maven/pull/1569
> [MNG-8141] Aftermath, and tidy up

- maven-embedder/src/main/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/SimplexTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/TransferResourceIdentifier.java
- maven-embedder/src/test/java/org/apache/maven/cli/transfer/SimplexTransferListenerTest.java
Backporting https://github.com/apache/maven/pull/1575 to Maven 3.9.x.
> [MNG-8150] Backport TransferListener improvements for Maven 3.9.x

- maven-embedder/src/main/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/SimplexTransferListener.java
- maven-embedder/src/main/java/org/apache/maven/cli/transfer/TransferResourceIdentifier.java
- maven-embedder/src/test/java/org/apache/maven/cli/transfer/SimplexTransferListenerTest.java
The PR address two issues observed in the `SimplexTransferListener` and `ConsoleMavenTransferListener`:
1. [TransferResource#getFile()](https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/main/java/org/eclipse/aether/transfer/TransferResource.java#L170) can be null. The current `SimplexTransferListener` will break with an NPE if the `file` is not set on the resource.
2. `TransferResource` is not immutable and does not implement `equals` or `hashCode,` making its usage in collections brittle. Listener consumers are not guaranteed to reuse the same instance across listener invocations. I suggest wrapping it in an immutable identifier.
Let me know if I am overthinking this or if anything else is needed.
Resolves https://issues.apache.org/jira/browse/MNG-8150
> [MNG-8150] Handle absent source/target files in transfer listener

- maven-core/src/main/java/org/apache/maven/plugin/PluginResolutionException.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/project/DependencyResolutionException.java
- maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java
The build result will be as:
```
[ERROR] Failed to execute goal on project test-artifact: Could not resolve dependencies for project test-group:test-artifact:jar:1
[ERROR] dependency: org.apache.test:test1:jar:1.0 (compile)
[ERROR] 	Could not find artifact org.apache.test:test1:jar:1.0 in central (https://repo.maven.apache.org/maven2)
[ERROR] 	Could not find artifact org.apache.test:test1:jar:1.0 in repo.apache-stage (https://repository.apache.org/content/groups/staging/)
[ERROR] dependency: org.apache.test:test2:jar:1.0 (compile)
[ERROR] 	Could not find artifact org.apache.test:test2:jar:1.0 in central (https://repo.maven.apache.org/maven2)
[ERROR] 	Could not find artifact org.apache.test:test2:jar:1.0 in repo.apache-stage (https://repository.apache.org/content/groups/staging/)
```
``` …
```
> [MNG-7758] Report dependency problems for all repository

- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8159 …
> [MNG-8159] Fix search for topDirectory when using -f / --file

- maven-core/src/test/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorTest.java
> [MNG-7194] Test missing property evaluation

- api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/XmlReaderRequest.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-core/src/main/resources/META-INF/maven/extension.xml
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- **Add rootDirectory to XmlReaderRequest and fix maven-core exported artifacts**
- **Set the thread context classloader to the container realm to fix class loading from extensions**
> Fix Maven 4 extensions

- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/OperatingSystemProfileActivator.java
A call to context.getSystemProperties() may yield empty an empty map, or one missing the desired key, which makes a subsequent call of toLowerCase fail with a NullPointerException.
Fall-back to using System.getProperty (with an empty default, in case that one fails too).
be performed on your pull request …
> [MNG-8178] Fall back to System.getProperty for missing context props

- maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/OperatingSystemProfileActivator.java
- **[MNG-8178] Fall back to System.getProperty for missing context props**
- **Use Os class to grab values instead**
Forward port of https://github.com/apache/maven/pull/1603
> [MNG-8178] Fall back to system properties for missing profile activation context properties

- maven-artifact/pom.xml
- maven-artifact/src/main/java/org/apache/maven/artifact/DefaultArtifact.java
- maven-artifact/src/main/java/org/apache/maven/artifact/versioning/VersionRange.java
- maven-artifact/src/test/java/org/apache/maven/artifact/DefaultArtifactTest.java
coordinates
This fixes throwing NPE for version being null.
please ask on the developers …
> [MNG-8192] Consistently throw InvalidArtifactRTException for invalid

- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverRequest.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/AbstractSession.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/AetherDependencyWrapper.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependency.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyCoordinate.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProject.java
The important change in this commit is in the implementation of `getClassifier()` methods. However, this commit opportunistically refactors the code with a base class shared by `DefaultDependency` and `DefaultDependencyCoordinate` implementations.
Trying to compile Maven with itself (4.0.0-beta-4-SNAPSHOT) fails with a `NullPointerException` in the `PluginsMetadataGenerator` class of the _"Maven Compat (deprecated)"_ module. The issue seems more serious than a missing null check, because according the sanity check at line 137, the plugin is operating on the wrong artifact. However, this issue is not related to this commit. Testing with the commit before this one produces the same result. Building with Maven 3 works fine.
---
https://issues.apache.org/jira/browse/MNG-8197
> [MNG-8197] Use default classifier when Eclipse Aether specifies none

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
Fix for MNG-8132.
The original patch from MNG-5600 had not been ported to the new model builder
> [MNG-8132] Fix BOM dependency exclusions

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/PluginsMetadata.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/PluginsMetadataGenerator.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadata.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/PluginsMetadataGenerator.java
There was an NPE possibility when plugin.xml had no expected tags present.
Also: maven-compat has plugin.xml (!) w/o "name" tag, it NPEd and failed build. This was NOT picked up by CI as "rebuild itself" step does not install (just verify).
---
https://issues.apache.org/jira/browse/MNG-8180
> [MNG-8180] Handle NPE due non-existent tags

- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RequestTraceHelper.java
As they really can come from anywhere. In case of this issue even from some eliminated POM that was read while collecting dirty tree, and was later eliminated. So confusing for users.
---
https://issues.apache.org/jira/browse/MNG-8177
> [MNG-8177] Add contextual info for model warnings

- apache-maven/src/assembly/shared/init
As one does check for .mvn directory in FS root while other does not, stops one level before.
---
https://issues.apache.org/jira/browse/MNG-8165
> [MNG-8165] Align mvn.sh script with mvn.cmd

- apache-maven/src/assembly/shared/init
Use of "==" is a bashism.
---
https://issues.apache.org/jira/browse/MNG-8165
> [MNG-8165] Get rid of bashism creeped in

- api/maven-api-plugin/src/main/mdo/plugin.mdo
It is already removed for 2.0.0
To make clear that you …
> [MPLUGIN-530] Deprecate requirements in plugin descriptor 1.1.0

- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverResult.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolverResult.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/PathModularization.java
Clarify the meaning of "module" in documentation, then add two methods for getting Java module information from a `DependencyResolverResult`:
* `getModuleName(Path)` returns a `java.lang.String`
* `getModuleDescription(Path)` returns a `java.lang.module.ModuleDescriptor`
"Get name" may seem redundant with "get description" because the name can be obtained from the description by `ModuleDescriptor.name()`. The difference is that "get name" fallbacks on the `Automatic-Module-Name` attribute of `META-INF/MANIFEST.MF` if the module descriptor is not found.
The rational for providing those methods in the API is because it allows to use the cache managed by the `DefaultDependencyResolverResult` implementation. It avoids decoding many times the `module-info.class` files. Plugins need those …
> [MNG-8195] Add `DependencyResolverResult.getModuleName(Path)` method

- maven-core/src/main/java/org/apache/maven/exception/DefaultExceptionHandler.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/main/java/org/apache/maven/plugin/DefaultBuildPluginManager.java
The boxing of `MojoException` into a `MojoExecutionException` brought two issues:
1. It added another layer to the stacktrace, making it a bit less readable for users and breaking test expectations for Maven extension authors (the latter was my main motivation for this change)
2. It lost the `longMessage`, which meant that this message was no longer shown at the end of the build.
This change fixes both problems by passing through the original `MojoException` and treating this new exception type directly in `DefaultExceptionHandler` and `MojoExecutor`
require a JIRA issue. Your pull request should address just this …
> [MNG-8196] Make exception messages match Maven 3 again

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/DefaultModelResolver.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelProcessor.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8172
Workaround for https://issues.apache.org/jira/browse/DOXIASITETOOLS-343
> [MNG-8172] Fix site building

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
As this is almost always source of confusion. If feature is used and there is no proper value set, fail the build, as users for sure does not plan to deploy artifacts with version `${revision}` (or any expression in project.version).
Still, to not be disruptive, the old behaviour can be achieved by setting `maven.build.allowExpressionInEffectiveProjectVersion`=true project property.
---
https://issues.apache.org/jira/browse/MNG-8211
> [MNG-8211] Fail the build if project effective version has expression

- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/AbstractStringBasedModelInterpolator.java
- maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
As this is almost always source of confusion. If feature is used and there is no proper value set, fail the build, as users for sure does not plan to deploy artifacts with version `${revision}` (or any expression in project.version).
Still, to not be disruptive, the old behaviour can be achieved by setting `maven.build.allowExpressionInEffectiveProjectVersion`=true project property.
---
https://issues.apache.org/jira/browse/MNG-8211
> [MNG-8211] Fail the build if CI Friendly revision used without value

- maven-model-builder/src/main/java/org/apache/maven/model/interpolation/ModelVersionProcessor.java
No JIRA, but is annoying that faily modern
interfaces have no since set properly.
Arrived with commit:
https://github.com/apache/maven/commit/2bb1228de60e805b2f864254a0b1efef7e2d7dde
> Add missing since

- api/maven-api-plugin/pom.xml
- api/maven-api-plugin/src/test/java/org/apache/maven/api/plugin/descriptor/another/ExtendedPluginDescriptorTest.java
- src/mdo/model.vm
This makes the constructor protected and takes the Builder as argument …
> [MNG-8214] Improve model velocity template to support subclasses

- apache-maven/src/assembly/maven/conf/maven.properties
- src/site/markdown/configuring.md
Follow-up to https://github.com/apache/maven/pull/1595
> [MNG-7914] Add doc for the new maven.properties file

- api/maven-api-core/src/main/java/org/apache/maven/api/Lifecycle.java
- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/After.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/LifecycleRegistry.java
- api/maven-api-plugin/pom.xml
- api/maven-api-plugin/src/main/mdo/lifecycle.mdo
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
- maven-compat/src/test/java/org/apache/maven/project/EmptyLifecycleBindingsInjector.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java
- maven-core/src/main/java/org/apache/maven/internal/impl/Lifecycles.java
- maven-core/src/main/java/org/apache/maven/lifecycle/DefaultLifecycles.java
- maven-core/src/main/java/org/apache/maven/lifecycle/Lifecycle.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleExecutionPlanCalculator.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleMappingDelegate.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/PhaseComparator.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/PhaseExecutionPoint.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/PhaseId.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/PhaseRecorder.java
- maven-core/src/test/java/org/apache/maven/lifecycle/DefaultLifecyclesTest.java
- maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorTest.java
- maven-core/src/test/java/org/apache/maven/project/EmptyLifecycleBindingsInjector.java
- maven-plugin-api/pom.xml
- src/mdo/reader-stax.vm
- src/mdo/writer-stax.vm
- src/mdo/writer.vm
JIRA issue: [MNG-8052](https://issues.apache.org/jira/browse/MNG-8052)
The lifecycle is now defined as a tree of phases, each phase being split with a `before:` phase and a `after:` phase.  Each phase is given a list of timing constraints: a phase from the same lifecycle (`compile` must be executed after `sources`), a phase in project dependencies (`compile` must execute after `compile-only` project dependencies have reached the `ready` phase), or a set of children project dependencies (to re-define aggregators, not yet implemented).
The default lifecycle is defined in the [`DefaultLifecycleRegistry`](https://github.com/gnodet/maven/blob/dynamic-phases/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java#L349-L379)
In addition to the `before:` and `after:` …
> [MNG-8052] New lifecycle for Maven 4

- maven-core/src/main/java/org/apache/maven/internal/impl/SisuDiBridgeModule.java
- maven-core/src/main/java/org/apache/maven/session/scope/internal/SessionScope.java
- maven-di/src/main/java/org/apache/maven/di/Key.java
- maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Need to setup an IT based on https://github.com/maveniverse/nisse/pull/6
JIRA issue: [MNG-8220](https://issues.apache.org/jira/browse/MNG-8220)
IT PR: https://github.com/apache/maven-integration-testing/pull/355
> [MNG-8220] Fix loading DI-powered beans from extensions

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/ProfileActivationFilePathInterpolator.java
- maven-model-builder/src/main/java/org/apache/maven/model/path/ProfileActivationFilePathInterpolator.java
- maven-model-builder/src/test/java/org/apache/maven/model/profile/activation/FileProfileActivatorTest.java
JIRA: https://issues.apache.org/jira/browse/MNG-7897
> [MNG-7897] Support ${project.rootDirectory} in file profile activation

- api/maven-api-core/src/main/java/org/apache/maven/api/Lifecycle.java
- maven-core/pom.xml
- maven-core/src/main/java/org/apache/maven/execution/BuildFailure.java
- maven-core/src/main/java/org/apache/maven/execution/BuildSuccess.java
- maven-core/src/main/java/org/apache/maven/execution/BuildSummary.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/CompoundProjectExecutionListener.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlan.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanExecutor.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanLogger.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildStep.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/ConcurrentLifecycleStarter.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/ConcurrentLogOutput.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/MojoExecutor.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/PhasingExecutor.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/PluginLifecycle.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanCreatorTest.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/concurrent/PhasingExecutorTest.java
JIRA issue: [MNG-8225](https://issues.apache.org/jira/browse/MNG-8225)
This PR aims at defining a complete new lifecycle for Maven 4.  This lifecycle is disabled by default and needs to be turned on using `mvn --builder=concurrent`.
Note that the builder is fully concurrent, so that a project may not be executed in a single thread and continuously, rather, all mojos will be scheduled independently.  The builder displays a nice summary at the beginning (currently at `info` level).
To avoid [MNG-7335](https://issues.apache.org/jira/browse/MNG-7335), [MNG-6843](https://issues.apache.org/jira/browse/MNG-6843) and all those long standing related bugs, the new lifecycle/builder warns when using non Maven 4 mojos (kinda like we have with the multithreaded builder which warns when mojos are not …
> [MNG-8225] Fully concurrent builder for Maven 4

- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/Mojo.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilder.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelProblem.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelSource.java
- api/maven-api-model/src/main/mdo/maven.mdo
- maven-api-impl/pom.xml
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelTransformerContextBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
- maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomArtifactTransformerTest.java
- maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
- maven-core/src/test/resources/consumer/simple/pom.xml
- maven-core/src/test/resources/consumer/simple/simple-parent/pom.xml
- maven-core/src/test/resources/consumer/simple/simple-parent/simple-testutils/pom.xml
- maven-core/src/test/resources/consumer/simple/simple-parent/simple-weather/pom.xml
- maven-core/src/test/resources/consumer/simple/simple-parent/utils-parent/pom.xml
- maven-core/src/test/resources/consumer/trivial/pom.xml
- maven-core/src/test/resources/projects/subprojects-discover/child/pom.xml
- maven-core/src/test/resources/projects/subprojects-discover/pom.xml
- maven-core/src/test/resources/projects/transform/before.pom
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelProblem.java
- src/mdo/model.vm
Based on @desruisseaux initial commit to rename subproject #1649.
This PR adds `subprojects` to 4.1.0 POM, deprecate `modules`, and add a discovery mechanism which kicks in when:
* pomVersion == 4.1.0
* packaging == pom
* no modules or subprojects are specified
> [MNG-8210] Replace Maven "module" term by "subproject"

- maven-core/src/main/java/org/apache/maven/ReactorReader.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7838
IT PR: https://github.com/apache/maven-integration-testing/pull/278
I'm not sure yet it solves the original reported problem though.
> [MNG-7838] Fix usage of older packaged artifacts from project local repository

- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- **[MNG-8229] Fix interpolation of CI friendly versions**
- **[MNG-8090] Fix missing repositories during parent artifact resolution**
> Fix jenkins build

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/BuildModelTransformer.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8252
IT PR: https://github.com/apache/maven-integration-testing/pull/360
A simple empty parent should be sufficient if the parent is located in the parent directory:
```
<project xmlns="http://maven.apache.org/POM/4.1.0">
<parent />
<artifactId>maven-resolver-util</artifactId>
...
</project>
```
If the parent is in a different location,
```
<project xmlns="http://maven.apache.org/POM/4.1.0">
<parent>
<location>../parent/</location>
</parent>
<artifactId>maven-resolver-util</artifactId>
...
</project>
```
> [MNG-8252] Fully infer the parent coordinates if the location points to a valid model

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/BuildModelTransformer.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/MavenModelMerger.java
Fix things
The original PR was passing UT and IT, but to sure how it worked
Anyway, this aims at fixing the computation. Using the `BuildModelTransformer` is not a good option: when the full reactor is loaded, we parse file models and expect them to have valid groupId/artifactId, so the processing has to be done during file model loading.
> [MNG-8252] Fully infer the parent coordinates if the location points to a valid model (#1706)

- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
- maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8237
> [MNG-8237] Option deprecation notices cleanup

- api/maven-api-di/src/main/java/org/apache/maven/api/di/MojoExecutionScoped.java
- api/maven-api-di/src/main/java/org/apache/maven/api/di/SessionScoped.java
- maven-core/src/main/java/org/apache/maven/internal/impl/SisuDiBridgeModule.java
- maven-di/src/main/java/org/apache/maven/di/Injector.java
- maven-di/src/main/java/org/apache/maven/di/impl/Binding.java
- maven-di/src/main/java/org/apache/maven/di/impl/BindingInitializer.java
- maven-di/src/main/java/org/apache/maven/di/impl/Dependency.java
- maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java
- maven-di/src/main/java/org/apache/maven/di/impl/ReflectionUtils.java
- maven-di/src/main/java/org/apache/maven/di/impl/Types.java
- maven-di/src/test/java/org/apache/maven/di/impl/InjectorImplTest.java
- **Code cleanup**
- **Provide build path with causes when an exception occur**
- **Fix toString to display meaningful info**
- **Javadoc**
- **Add @NonNull and @Overrides annotations**
- **Support for @Nullable on fields and parameters**
> DI improvements

- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ModelTransformer.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ModelTransformerException.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/RepositorySystemSupplier.java
- maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenRepositorySystemSupplier.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8232
Requires https://github.com/apache/maven/pull/1704
> [MNG-8232] Introduce ModelTransformer

- api/maven-api-model/src/main/mdo/maven.mdo
- maven-model/src/test/java/org/apache/maven/model/v4/MavenModelVersionTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8234
IT PR: https://github.com/apache/maven-integration-testing/pull/361
> [MNG-8234] Revert the addition of the priority tag

- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactResolver.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactResolverRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderResult.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelResolver.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionRangeResolver.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionRangeResolverRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionResolverRequest.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/AbstractSession.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultArtifactResolver.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultVersionRangeResolver.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultVersionResolver.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/DefaultArtifactDescriptorReader.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/DefaultModelResolver.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/resolver/DefaultModelResolverTest.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectBuilder.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8235
> [MNG-8235] Move remote repositories into requests

- maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java
- maven-core/src/main/java/org/apache/maven/graph/FilteredProjectDependencyGraph.java
- maven-core/src/test/java/org/apache/maven/graph/DefaultProjectDependencyGraphTest.java
The `FilteredProjectDependencyGraph` class fix for non-transitive case and an UT. Also contains some improvement in classes, making them immutable as intended.
---
https://issues.apache.org/jira/browse/MNG-8256
> [MNG-8256] FilteredProjectDependencyGraph fix for non-transitive case

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/BuildModelTransformer.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelTransformerContextBuilder.java
JIRA issue: [MNG-7255](https://issues.apache.org/jira/browse/MNG-7255)
IT PR: https://github.com/apache/maven-integration-testing/pull/356
> [MNG-7255] Infer groupId for intra-reactor dependencies

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8242
During model building, we do not cache any hierarchy inheritance due to profiles that may be activated based on properties from the child projects.
So there's no way to cache the effective parent and just inject it into the child, the whole hierarchy need to be taken into account.
However, flattening the parent (i.e. inject the flattened parent's parent into the raw parent) should provide a parent model which has no parents anymore, not activated and not interpolated, but which can be cached and reused.
> [MNG-8242] Cache flattened parents during model building

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderResult.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelProblem.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelBuildingResult.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/ModelProblem.java
Javadoc states wrong things (about format of modelId, they are paths in reality), but also these all are "implementation details". Crafting modelIds to "walk" lineage is wrong, there is a dedicated method that provide "opaque" key Strings in defined order to do that. And client should not care (nor assume) anything about format of the key String.
As per MNG-8233, "modelIds" in Maven4 are NOT `g:a:v`s as Javadoc wrongly states, but paths.
---
https://issues.apache.org/jira/browse/MNG-8233
> [MNG-8233] Client should handle modelIds as "opaque"

- maven-embedder/src/main/resources/META-INF/maven/slf4j-configuration.properties
Just a simple PR to make properties file a "properties file" as majority would expect. According to spec '=', ':', or white space can be delimiter and this file IS valid, but still, users my be surprised, or tools like IDEs may misinterpret this, otherwise valid Java Properties File.
> No issue, no change

- apache-maven/pom.xml
- maven-embedder/pom.xml
- maven-jline/pom.xml
- maven-jline/src/main/java/org/apache/maven/jline/JLineMessageBuilderFactory.java
- pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-8261
> [MNG-8261] Remove jline-terminal-ffm direct dependency

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/PathModularizationCache.java
When Maven detects a non-modular JAR file on the module path, it produces a warning. However, the warning is currently not very readable. The message and all dependencies are put on the same line, and a space is missing between the last dependency and the rest of the message. This commit splits the message with each dependency on its own line.
Note: the relevance of this warning is questionable. This commit does not address the issue about whether we should just completely remove it.
> More readable formatting of the warning about automatic modules

- apache-maven/pom.xml
- apache-maven/src/assembly/maven/bin/m2.conf
...just found no reason not adding it, as all other scripts/shell have added, and this file format actually can accept \# comments...
> Add license header to m2.conf

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelPathTranslator.java
- maven-model-builder/src/main/java/org/apache/maven/model/path/DefaultModelPathTranslator.java
As discovered by @desruisseaux , this method is once used for "change detection" (if result is not null, apply change), and once directly where it -- probably by mistake -- nullifies the field value.
@gnodet
> Probable bug: method that nullifies model

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
It seems Maven is eager to get POM from rootDirectory to support CI Friendly versions. This change makes it "best effort", as in if there is no POM, just walk away.
---
https://issues.apache.org/jira/browse/MNG-8288
> [MNG-8288] "path cannot be null"

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectDependenciesResolver.java
This is one of the root cause for IT instability.
@slawekjaranowski I've also re-enabled full stack traces, as the causes are currently completely lost (only the first level of exceptions is kept in the message)
> Fix concurrency issue in DefaultModelValidator

- api/maven-api-model/src/main/mdo/maven.mdo
- api/maven-api-settings/src/main/mdo/settings.mdo
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/profile/FileProfileActivator.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/model/ComplexActivationTest.java
- maven-api-impl/src/test/resources/poms/factory/complex.xml
- maven-api-impl/src/test/resources/poms/factory/complexExistsAndMissing.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-5910
> [MNG-5910] Warn if both exists and missing file activation are set

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderRequest.java
- api/maven-api-model/src/main/mdo/maven.mdo
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
- maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java
- maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
JIRA issue: [MNG-8294](https://issues.apache.org/jira/browse/MNG-8294)
IT PR: https://github.com/apache/maven-integration-testing/pull/383
> [MNG-8294] Consistency checks when loading parent

- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/Options.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
Show errors when verbose as well; behave as old MavenCLI did.
---
https://issues.apache.org/jira/browse/MNG-8305
> [MNG-8305] Fix MER showErrors setting

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/MavenSessionBuilderSupplier.java
IT PR: https://github.com/apache/maven-integration-testing/pull/384
JIRA issue: [MNG-8295](https://issues.apache.org/jira/browse/MNG-8295)
-----
From @DidierLoiseau 
Actually use TransitiveDependencyManager when maven.resolver.dependencyManagerTransitivity=true, instead of ClassicDependencyManager(true, …) as per https://github.com/apache/maven/pull/1357.
This fixes [MNG-8295](https://issues.apache.org/jira/browse/MNG-8295) and the integration tests proposed in https://github.com/apache/maven-integration-testing/pull/384.
I thought that, since the change is trivial, it doesn’t cost much to create a PR for it already – even if the consensus turns out to be something else in the end.
------
Supersedes https://github.com/apache/maven/pull/1785 to align branch names
> [MNG-8295] Dependency Manager Transitivity (now default) handles dependency management inconsistently

- maven-cli/src/main/java/org/apache/maven/cling/MavenCling.java
- maven-cli/src/main/java/org/apache/maven/cling/MavenEncCling.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/DefaultEncryptInvoker.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/ConfiguredGoalSupport.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/Decrypt.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/Diag.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/Encrypt.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/GoalSupport.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/Init.java
LookupInvoker does terminal stuff now, remove them from "early" entry classes, also adopt mvnenc
> Cleanup after last commit

- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolver.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverRequest.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/AbstractSession.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/TestApiStandalone.java
- maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
JIRA issue: [MNG-8041](https://issues.apache.org/jira/browse/MNG-8041)
IT PR: https://github.com/apache/maven-integration-testing/pull/390
> [MNG-8041] Move PathScope into the dependency collection request

- maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
In https://issues.apache.org/jira/browse/MNG-8311, I reported the issue that an empty `<localRepository/>` element in the settings.xml uses the current working directory or home directory for the local repository.
This PR fixes that issue by adding a check for the empty `String`.
> [MNG-8311] empty but existing <localRepository/> in settings.xml

- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/rootlocator/DefaultRootLocator.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
- maven-compat/src/test/java/org/apache/maven/AbstractCoreMavenComponentTestCase.java
- maven-compat/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java
- maven-compat/src/test/java/org/apache/maven/repository/LegacyRepositorySystemTest.java
- maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequest.java
- maven-core/src/test/java/org/apache/maven/AbstractCoreMavenComponentTestCase.java
- maven-core/src/test/java/org/apache/maven/MavenTestHelper.java
- maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
- maven-core/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java
This reverts commit 608a99fb08cf7fabcc73c0691ff0b35bd5f326ed.
> [MNG-8302] Revert "Make rootDirectory really mandatory"

- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/InvokerRequest.java
- maven-api-impl/src/main/java/org/apache/maven/api/services/model/RootLocator.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/rootlocator/DefaultRootLocator.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseInvokerRequest.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/Utils.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/BaseMavenParser.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/DefaultMavenInvoker.java
First, `rootDirectory` is nullable, CLIng code was not assuming this, fixed.
Second, emit the "no root found" warning ONLY when appropriate (when we have a POM in picture).
---
https://issues.apache.org/jira/browse/MNG-8302
> [MNG-8302] Warn when appropriate

- apache-maven/src/assembly/maven/bin/mvn.cmd
JIRA issue: [MNG-8315](https://issues.apache.org/jira/browse/MNG-8315)
Port to master of #1806
> [MNG-8315] Fix MAVEN_PROJECTBASEDIR in mvn.cmd when .mvn is at drive root

- maven-jline/pom.xml
- pom.xml
These exclusions were here for historical reasons, but are not needed anymore.
> Remove unused exclusions

- maven-docgen/pom.xml
maven-docgen module warns about multiple providers being on classpath. As Maven logging that is a slf4j provider already present, simple not needed.
> Get rid of slf4j warning

- maven-api-impl/src/main/java/org/apache/maven/api/services/model/ModelResolver.java
- maven-api-impl/src/main/java/org/apache/maven/internal/impl/resolver/DefaultModelResolver.java
- maven-core/src/main/java/org/apache/maven/ReactorReader.java
- maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java
- **[MNG-8326] The ModelBuilder cannot import BOM with classifiers**
- **[MNG-8325] The ReactorReader should know about build/consumer POMs**
- **[MNG-8327] Failure when building the consumer POM**
This PR should be rebased and not squashed...
> [MNG-8325][MNG-8326][MNG-8327] Fix bugs 

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
> [MNG-8331] Sometimes versioned dependencies disappear

- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/Options.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/LayeredOptions.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/DefaultMavenInvoker.java
- maven-jline/src/main/java/org/apache/maven/jline/MessageUtils.java
JIRA issue: [MNG-8334](https://issues.apache.org/jira/browse/MNG-8334)
- **Fix empty output when using -l or redirecting output**
- **Fix incomplete log in file**
Alternative PR to #1824 @cstamas, and it should fix both type of redirections (`-l` and shell stdout `>` redirection)
This PR is more in line with what I had in mind.
In particular, this would allow stuff like the multiplexed output from mvnd
where we display information to the terminal, but not the actual log output.
> [MNG-8334] Fix output redirection

- maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java
JIRA issue: [MNG-8342](https://issues.apache.org/jira/browse/MNG-8342)
----
Output is the following:
```
➜  maven git:(MNG-8342) ✗ ~/work/git/maven/apache-maven/target/apache-maven-4.0.0-beta-6-SNAPSHOT/bin/mvn --verbose -v
Apache Maven 4.0.0-beta-6-SNAPSHOT (3425b4dd08fa4dd416e0e16c39c5dc8c6d80b6cc)
Maven home: /Users/gnodet/work/git/maven/apache-maven/target/apache-maven-4.0.0-beta-6-SNAPSHOT
Java version: 22.0.2, vendor: Eclipse Adoptium, runtime: /Users/gnodet/.sdkman/candidates/java/22.0.2-tem
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "15.0.1", arch: "aarch64", family: "mac"
Command line: /Users/gnodet/.sdkman/candidates/java/22/bin/java -DtrimStackTrace=false --enable-native-access=ALL-UNNAMED -classpath …
```
> [MNG-8342] Add command line and terminal information when verbose

- maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
JIRA issue: [MNG-8348](https://issues.apache.org/jira/browse/MNG-8348)
> [MNG-8348] Fix typos in deprecation warning message

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectManager.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/DefaultModelVersionParserTest.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectManager.java
- maven-core/src/test/java/org/apache/maven/internal/impl/DefaultProjectManagerTest.java
JIRA issue: [MNG-8330](https://issues.apache.org/jira/browse/MNG-8330)
> [MNG-8330] Enforce attached artifacts to have the same GAV than their project

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultInterpolator.java
- maven-api-impl/src/test/java/org/apache/maven/internal/impl/model/DefaultInterpolatorTest.java
JIRA issue: [MNG-8344](https://issues.apache.org/jira/browse/MNG-8344)
----
The goal is to enhance the supported syntax for operators in variable expansion, so that we can use those as a ternary operator:
```
maven.user.config = ${env.MAVEN_XDG:+${env.XDG_CONFIG_HOME:-${user.home}/.config}/maven}:-${user.home}/.m2}
```
> [MNG-8344] Support multiple operators in variable expansion

- apache-maven/pom.xml
- apache-maven/src/assembly/component.xml
- apache-maven/src/assembly/maven/bin/mvn
- apache-maven/src/assembly/maven/bin/mvn.cmd
- apache-maven/src/assembly/maven/lib/jansi-native/README.txt
- apache-maven/src/assembly/maven/lib/jline-native/README.txt
JIRA issue: [MNG-8328](https://issues.apache.org/jira/browse/MNG-8328)
> [MNG-8328] Clean up assembly from Jansi remains and add JLine native libraries

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
JIRA issue: [MNG-8349](https://issues.apache.org/jira/browse/MNG-8349)
The output is now the expected one (albeit duplicated):
```
[INFO] Scanning for projects...
[ERROR] Some problems were encountered while processing the POMs
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.test:foo:jar:1.0-SNAPSHOT (/Users/gnodet/tmp/MNG-8189/pom.xml) has 2 errors
[ERROR]     'modelVersion' must be one of [4.0.0, 4.1.0] but is '4..0.0'. @ org.test:foo:1.0-SNAPSHOT, file:///Users/gnodet/tmp/MNG-8189/pom.xml, line 2, column 3
[ERROR]     'modelVersion' must be one of [4.0.0, 4.1.0] but is '4..0.0'. @ org.test:foo:1.0-SNAPSHOT, file:///Users/gnodet/tmp/MNG-8189/pom.xml, line 2, column 3
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with …
```
> [MNG-8349] Avoid exceptions with invalid modelVersion

- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java
- maven-core/src/main/java/org/apache/maven/internal/impl/DefaultPackagingRegistry.java
- maven-core/src/main/java/org/apache/maven/internal/impl/Lifecycles.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecyclePluginAnalyzer.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/BuilderCommon.java
- maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanExecutor.java
- maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/LifecycleExecutionPlanCalculatorStub.java
Also move the default location into DefaultLifecycleRegistry as the DefaultLifecyclePluginAnalizer is not used anymore
---
JIRA issue: [MNG-8189](https://issues.apache.org/jira/browse/MNG-8189)
> [MNG-8189] Warn about plugin versions not pinned for all lifecycles

- maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
The deadlock can happen when the root pom inherit from a parent which is a subproject, the subproject inheriting from an external parent.
JIRA issue: [MNG-8341](https://issues.apache.org/jira/browse/MNG-8341)
IT PR: https://github.com/apache/maven-integration-testing/pull/394
The reproducer project is https://github.com/apache/pdfbox.git master, but an IT would be a good idea.
> [MNG-8341] Fix possible deadlock in ModelBuilder

- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
JIRA issue: [MNG-8360](https://issues.apache.org/jira/browse/MNG-8360)
IT PR: https://github.com/apache/maven-integration-testing/pull/396
Fix parent profiles being activated but not reported as such.
> [MNG-8360] Fix parent profiles not reported as activated

- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
JIRA issue: [MNG-8368](https://issues.apache.org/jira/browse/MNG-8368)
> [MNG-8368] Fix dependency resolver not using project repositories

- its/core-it-suite/pom.xml
- its/core-it-suite/src/test/java/org/apache/maven/it/HttpServer.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6255FixConcatLines.java
- its/core-it-suite/src/test/resources-filtered/bootstrap.txt
- its/core-it-support/core-it-javaagent/pom.xml
- its/core-it-support/core-it-support-artifacts/pom.xml
- its/pom.xml
Yet another round
Changes:
* get rid of Guava (2 classes affected)
* align dependencies
* align plugins
> IT: cleanup

- compat/maven-settings-builder/src/main/java/org/apache/maven/settings/crypto/DefaultSettingsDecrypter.java
- its/core-it-suite/src/test/resources/mng-8347-transitive-dependency-manager/README.md
@cstamas sorry I formatted the commit messages differently .... hopefully the ITS run through.
> [MNG-8372] Augment error message to give users more context when running into deprecated encryption warning

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderRequest.java
- impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- impl/maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
- impl/maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelInterpolator.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/resolver/DefaultArtifactDescriptorReader.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/model/ComplexActivationTest.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/standalone/TestApiStandalone.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8340GeneratedPomInTargetTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8340/child1/pom.xml
- its/core-it-suite/src/test/resources/mng-8340/child2/pom.xml
- its/core-it-suite/src/test/resources/mng-8340/pom.xml
JIRA issue: [MNG-8340](https://issues.apache.org/jira/browse/MNG-8340)
We need to double check one last time that it works, or better, add an IT.
> [MNG-8340] Resolve parent according to the exact model location

- apache-maven/src/assembly/maven/bin/mvn
- apache-maven/src/assembly/maven/bin/mvn.cmd
Needs to be tested on windows, or maybe just add an IT ?
> [MNG-8376] Exit with a nicer error message when running on JDK < 17

- .mvn/maven.config
- pom.xml
Use latest Resolver with bugfixes and enhancements. Also, downgrades default JDK Transport to HTTP/1.1.
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12355229
---
https://issues.apache.org/jira/browse/MNG-8378
> [MNG-8378] Upgrade to Resolver 2.0.4

- its/core-it-suite/src/test/java/org/apache/maven/it/MavenIT0108SnapshotUpdateTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng1751ForcedMetadataUpdateDuringDeploymentTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2362DeployedPomEncodingTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2790LastUpdatedMetadataTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2820PomCommentsTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3415JunkRepositoryMetadataTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3441MetadataUpdatedFromDeploymentRepositoryTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3503Xpp3ShadingTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3599useHttpProxyForWebDAVMk2Test.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3693PomFileBasedirChangeTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3892ReleaseDeploymentTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3940EnvVarInterpolationTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4309StrictChecksumValidationForMetadataTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4368TimestampAwareArtifactInstallerTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4554PluginPrefixMappingUpdateTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4660OutdatedPackagedArtifact.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4745PluginVersionUpdateTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4874UpdateLatestPluginVersionTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4952MetadataReleaseInfoUpdateTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5387ArtifactReplacementPlugin.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5742BuildExtensionClassloaderTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5753CustomMojoExecutionConfiguratorTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6127PluginExecutionConfigurationInterferenceTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6386BaseUriPropertyTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6656BuildConsumer.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6957BuildConsumer.java
No dependency change yet, just remove all the use of `maven-shared-utils` from IT classes, as `plexus-utils` is anyway present. Also, Java alone has many of these utils now.
> IT: Move ITs off maven-shared-utils

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupContext.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- impl/maven-core/src/main/java/org/apache/maven/execution/ExecutionEvent.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultEvent.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/EventSpyImpl.java
JIRA issue: [MNG-8394](https://issues.apache.org/jira/browse/MNG-8394)
Changes:
* The event type conversion is wrong (mvn3-mvn4 event bridge).
* The user properties were pushed too late for logging configuration. Now we push user properties two times, immediately (only those keys that does not exists), and 2nd time after property contributor we "refresh" all we pushed.
> [MNG-8394] Event bridge and properties fix

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupContext.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/MavenInvoker.java
The "effective" paths for 3 settings file was not set on MavenExecutionRequest.
---
https://issues.apache.org/jira/browse/MNG-8389
> [MNG-8389] MavenExReq lacks u/p/i settings file paths

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8400CanonicalMavenHomeTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
As currently it is mixing canonical paths with non-canonical ones.
---
https://issues.apache.org/jira/browse/MNG-8400
> [MNG-8400] Make sure base parser uses canonical maven.home

- compat/maven-embedder/pom.xml
- impl/maven-cli/pom.xml
- impl/maven-impl/pom.xml
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelInterpolator.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/model/DefaultModelInterpolatorTest.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/model/MavenBuildTimestampTest.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/model/profile/SimpleProblemCollector.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/standalone/RepositorySystemSupplier.java
- pom.xml
JIRA issue: [MNG-8402](https://issues.apache.org/jira/browse/MNG-8402)
Add tests from Maven 3 and fix a few things in DefaultModelInterpolator
> [MNG-8402] System properties can take precedence over builtin expressions

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/CommonsCliEncryptOptions.java
Expand mvnenc help
---
https://issues.apache.org/jira/browse/MNG-8423
> [MNG-8423] mvnenc -h

- its/core-it-suite/pom.xml
- its/core-it-suite/src/test/java/org/apache/maven/it/ItUtils.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng0553SettingsAuthzEncryptionTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3955EffectiveSettingsTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5669ReadPomsOnce.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7772CoreExtensionFoundTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7772CoreExtensionsNotFoundTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8379SettingsDecryptTest.java
- its/core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/Verifier.java
Implement proper IT isolation, in a way, that user running ITs should not have it's own env "mixed in" into IT runs. In essence, use "alternate" `user.home` for ITs. Also use proper means to set user home. This will also stop fork 4 ITs (as they were forked due presence of env variable).
Note: yes, this causes longer IT execution time (as can be seen), as the ITs user home (core-it-suite/target/user-home) starts as empty (tail is set to "outer" local repo), so ITs do download stuff.
---
https://issues.apache.org/jira/browse/MNG-8406
> [MNG-8406] Proper IT isolation

- api/maven-api-core/src/main/java/org/apache/maven/api/services/MavenBuilderException.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilderException.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainsBuilderException.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/DefaultSettingsBuilder.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3748BadSettingsXmlTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8379SettingsDecryptTest.java
Toned down the Maven4 sec dispatcher messages. Also, IF maven3 passwords detected AND there was `.mvn/extensions.xml` the warnings were doubled.
Examples:
Failure to start Maven (due non-decryptable passwords):
```
$ mvn clean
[ERROR] Error executing Maven.
[ERROR] Error building settings
* FATAL: Could not decrypt password (fix the corrupted password or remove it, if unused) {xL6L/HbmrY++sNkphnq3fguYepTpM04WlIXb8nB1pk=}
* WARNING: Detected 2 pre-Maven 4 legacy encrypted password(s) - configure password encryption with the help of mvnenc for increased security.
$
```
Warning at start (due Maven3 passwords):
```
$ mvn clean
[INFO]
[INFO] Some problems were encountered while building the effective settings (use -X to see details)
[INFO]
[INFO] Scanning for projects...
[INFO] …
```
> [MNG-8419][MNG-8424] Too aggressive warning for pre-Maven4 passwords

- api/maven-api-core/src/main/java/org/apache/maven/api/Lifecycle.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/event/ExecutionEventLogger.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/Lifecycle.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleExecutionPlanCalculator.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleMappingDelegate.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/PhaseComparator.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanExecutor.java
- impl/maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8244PhaseAllTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8244-phase-all/pom.xml
- **[MNG-5729] Fix possible NPE with introduction of mononic clock**
- **[MNG-8244] Using before:all / all / after:all is not triggered**
> [MNG-8244] Using before:all / all / after:all is not triggered

- maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
Based on: 1ab2ccf066ceb5a2a491c8a9779fef8c5e57bb22
https://issues.apache.org/jira/browse/MNG-8370
> [MNG-8370] Add maven.repo.local.head

- apache-maven/pom.xml
- impl/maven-jline/pom.xml
- impl/maven-jline/src/main/java/org/apache/maven/jline/JLineMessageBuilderFactory.java
Move to Maven DI
---
https://issues.apache.org/jira/browse/MNG-8438
> [MNG-8438] maven-jline: Migrate to Maven DI (off javax.inject)

- impl/maven-cli/src/main/java/org/apache/maven/cling/transfer/AbstractMavenTransferListener.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/transfer/FileSizeFormat.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/transfer/FileSizeFormatTest.java
```
Downloaded from central: https://repo.maven.apache.org/maven2/org/graalvm/compiler/compiler/24.1.1/compiler-24.1.1.pom (1.7 kB at 9223372036854775807 GB/s)
```
---
https://issues.apache.org/jira/browse/MNG-8436
> [MNG-8436] Fix wrong transfer rates displayed in console

- impl/maven-core/src/main/java/org/apache/maven/logging/LoggingOutputStream.java
LoggingOutputStream used by default as sysout and syserr were NOT flushing (def method is empty), and flush happened only when EOL was printed.
Still, prompts and help:evaluate does print out unterminated strings.
---
https://issues.apache.org/jira/browse/MNG-8460
> [MNG-8460] Implement flush()

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java
Effective settings are (should be) created twice, once for "early boot" of Plexus when extensions are loaded up, and then again when Maven "boots".
Bug was that early call "corrupted" (inited settings) in context causing that 2nd required call (due spy) was omitted. This resulted in lack of settings related spy events firing (as we do have IT for spy but it does not test settings events).
---
https://issues.apache.org/jira/browse/MNG-8461
Related: https://github.com/alextu/maven4-reproducer/issues/1
> [MNG-8461] Initial settings method must restore context state

- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelInterpolator.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelValidator.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/model/DefaultModelValidatorTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8465RepositoryWithProjectDirTest.java
- its/core-it-suite/src/test/resources/mng-8465/pom.xml
Valid expressions in repositories are:
* `${project.basedir}`
* `${project.basedir.uri}`
* `${project.rootDirectory}`
* `${project.rootDirectory.uri}`
JIRA issues  [MNG-8465](https://issues.apache.org/jira/browse/MNG-8465)
> [MNG-8465] Add support for project.rootDirectory in repositories and fix other expressions

- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8461SpySettingsEventTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8461/extension/README.md
- its/core-it-suite/src/test/resources/mng-8461/extension/pom.xml
- its/core-it-suite/src/test/resources/mng-8461/extension/src/main/java/org/example/SimpleEventSpy.java
- its/core-it-suite/src/test/resources/mng-8461/project/.mvn/extensions.xml
- its/core-it-suite/src/test/resources/mng-8461/project/pom.xml
Integrate the reproducer into ITs.
---
https://issues.apache.org/jira/browse/MNG-8461
> [MNG-8461] Integrate reproducer as IT

- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelInterpolator.java
- impl/maven-impl/src/test/java/org/apache/maven/internal/impl/model/DefaultModelInterpolatorTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8469InterpolationPrecendenceTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8469/pom.xml
Restore precedence as it was in Maven3:
- basedir
- buildTime
- prefixed model
- user props
- model props
- system props
- env
- prefixless model
---
https://issues.apache.org/jira/browse/MNG-8469
> [MNG-8469] Fix interpolation precedence order

- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTest.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTestSupport.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/resident/ResidentMavenInvokerTest.java
- impl/maven-executor/src/main/java/org/apache/maven/api/cli/ExecutorRequest.java
- impl/maven-executor/src/main/java/org/apache/maven/cling/executor/internal/HelperImpl.java
- impl/maven-executor/src/test/java/org/apache/maven/cling/executor/impl/HelperImplTest.java
- its/core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/Verifier.java
UTs were using real user home, and in case user had user-wide extensions.xml, it resulted in failure. Goal: make sure all UTs are properly protected and isolated from user env, by providing "fake" user home (to not have user-wide extensions in real user home affect test outcome).
---
https://issues.apache.org/jira/browse/MNG-8487
> [MNG-8487] Completely isolate UTs

- impl/maven-core/src/main/java/org/apache/maven/ReactorReader.java
Use 'ejb' not 'ejb3' as type in ReactorReader artifact resolution for compile phase
I left this as a Draft to reflect the fact that I don't really understand this layer of code, but had just guess and confirmed that it seemed to fix the problem.
Hopefully more discussion can occur on the issue at: 
https://issues.apache.org/jira/browse/MNG-8479
---
Best practice is to use the JIRA issue title in both the pull request title and in the …
> MNG-8479 - Use 'ejb' not 'ejb3' as type in ReactorReader artifact resolution for compile phase

- api/maven-api-core/src/main/java/org/apache/maven/api/Dependency.java
- api/maven-api-core/src/main/java/org/apache/maven/api/DependencyCoordinates.java
- api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/PathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Type.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverResult.java
- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolverResult.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/PathModularizationCache.java
In particular I've followed Oracle's usage of unhyphenated  "class path" and "module path" when referring to the concepts instead of the CLI argument. --module-path is still used when referring to the command line flags.
> Copy edits in comments, API doc, and messages

- impl/maven-executor/src/main/java/org/apache/maven/cling/executor/embedded/EmbeddedMavenExecutor.java
- impl/maven-executor/src/test/java/org/apache/maven/cling/executor/impl/HelperImplTest.java
Salvaged from the "split repo for ITs" experiment. The experiment failed but this improvement is good to have, as makes the embedded executor behave more closely like forked executor.
Embedded so far did not obey MAVEN_ARGS env variable while forked did.
---
https://issues.apache.org/jira/browse/MNG-8502
> [MNG-8502] Embedded executor should obey MAVEN_ARGS env variable

- compat/maven-compat/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java
- compat/maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
- impl/maven-core/src/main/java/org/apache/maven/internal/aether/ReverseTreeRepositoryListener.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoDescriptorCreator.java
Under loops, string concatenation using StringBuilder performs better.
> [MNG-8475] In the loop scenario, StringBuilder is used instead of concatenation

- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/reflection/IntrospectionException.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/model/reflection/MethodMap.java
- impl/maven-logging/src/main/java/org/apache/maven/slf4j/MavenBaseLogger.java
- impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
JIRA issue: [MNG-8493](https://issues.apache.org/jira/browse/MNG-8493) …
> [MNG-8493] 'serialVersionUID' can be annotated with '@Serial' annotation

- impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
JIRA issue: [MNG-8513](https://issues.apache.org/jira/browse/MNG-8513)
null
> [MNG-8513] Be stricter about xml combination modes

- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionRangeResolverResult.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/AbstractSession.java
- impl/maven-impl/src/main/java/org/apache/maven/internal/impl/resolver/DefaultModelResolver.java
JIRA issue: [MNG-8514](https://issues.apache.org/jira/browse/MNG-8514)
Aims at superseding #2036
> [MNG-8514] Improve VersionRangeResolverResult

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactDeployerRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactInstallerRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactResolverRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/BaseRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverRequest.java
`List.copyOf()` is exactly what we need to make a defensive copy of the input collection.  It also has the benefit of not doing anything if the input collection is already an immutable list.
> [MNG-8484] Replace BaseRequest#unmodifiable with List.copyOf()

- compat/maven-builder-support/pom.xml
- compat/maven-builder-support/src/main/java/org/apache/maven/building/DefaultProblem.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/DefaultProblemCollector.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/FileSource.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/Problem.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/ProblemCollector.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/ProblemCollectorFactory.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/Source.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/StringSource.java
- compat/maven-builder-support/src/main/java/org/apache/maven/building/UrlSource.java
JIRA issue: [MNG-8522](https://issues.apache.org/jira/browse/MNG-8522)
The `maven-builder-support` contains classes shared between `maven-model-builder`, `maven-settings-builder` and `maven-toolchain-builder`, all of those subprojects being deprecated as they are part of the Maven 3 API.
This PR thus also deprecates this subproject and its classes.
> [MNG-8522] Deprecate maven-builder-support artifact and its classes

- apache-maven/src/assembly/maven/conf/settings.xml
JIRA issue: [MNG-6113](https://issues.apache.org/jira/browse/MNG-6113)
> [MNG-6113] Restore 'Maven Central Repository' name (lost with #1139)

- impl/maven-cli/src/main/java/org/apache/maven/cling/logging/impl/MavenSimpleConfiguration.java
- impl/maven-logging/src/main/java/org/apache/maven/slf4j/MavenLoggerFactory.java
- impl/maven-logging/src/main/java/org/apache/maven/slf4j/MavenSimpleLogger.java
JIRA issue: [MNG-8512](https://issues.apache.org/jira/browse/MNG-8512)
> [MNG-8512] Fix org.slf4j.simpleLogger.defaultLogLevel Configuration conflict

- api/maven-api-model/src/main/mdo/maven.mdo
- src/mdo/reader-stax.vm
JIRA issue: [MNG-8395](https://issues.apache.org/jira/browse/MNG-8395)
Add a `<Source>` element in the model. Properties are:
- `directory` (inherited from `FileSet`)
- `includes`  (inherited from `PatternSet`)
- `excludes`  (inherited from `PatternSet`)
- `scope`
- `lang`
- `module`
- `targetVersion`
- `targetPath` (taken from `<Resource>`)
- `filtering` (taken from `<Resource>`)
- `enabled`
This commit also renames `source` parameter value in `reader-stax.vm` for avoiding name collision with the new `Source` model element.
> [MNG-8395] Add a <Source> element in the model.

- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8477MultithreadedFileActivationTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8477/m1/pom.xml
- its/core-it-suite/src/test/resources/mng-8477/m2/pom.xml
- its/core-it-suite/src/test/resources/mng-8477/pom.xml
JIRA issue: [MNG-8477](https://issues.apache.org/jira/browse/MNG-8477)
Disable profile activation interpolation before checking profile activations.
The interpolated activations are cached and lead to wrong evaluations.
Given the activations are interpolated anyway during activation, there's
no need to do that before.
> [MNG-8477] Fix problems with file activation being wrongly cached

- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8525MavenDIPlugin.java
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/pom.xml
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/it/hello-maven-plugin/invoker.properties
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/it/hello-maven-plugin/pom.xml
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/it/hello-maven-plugin/verify.groovy
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/it/settings.xml
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/main/java/org/apache/maven/plugins/HelloMojo.java
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/main/java/org/apache/maven/plugins/MavenDIComponent.java
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/src/test/java/org/apache/maven/plugins/HelloMojoTest.java
JIRA issue: [MNG-8525](http://issues.apache.org/jira/browse/MNG-8525)
Add an integration test for a Maven 4 plugin sample. 
Based on the sample for [Maven 3 plugins](https://github.com/apache/maven-integration-testing/tree/master/core-it-suite/src/test/resources/mng-5382)
Thanks, @gnodet, for resolving some issues.  …
> [MNG-8525]  Add an integration test with Maven 4 Plugin Sample

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTest.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTestSupport.java
Now that Maven4 has several extension sources, we need to be able to detect conflicts. For now, we allow only one GA and fail the bootstrapping, if conflict discovered.
User should fix the situation, with the help of detailed error message enumerating all the conflicts.
---
https://issues.apache.org/jira/browse/MNG-8544
> [MNG-8544] Conflicting extensions went unnoticed

- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultRemoteRepository.java
But they have no hash/equals defined.
---
https://issues.apache.org/jira/browse/MNG-8545
> [MNG-8545] Use of RemoteRepository in keys w/o equals/hashes

- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8523ModelPropertiesTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8523-model-properties/pom.xml
JIRA issue: [MNG-8523](https://issues.apache.org/jira/browse/MNG-8523)
Needs ITs.  The idea is to actually override model properties in the model for projects in the reactor.
> [MNG-8523] Make sure user properties override model properties

- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/Mojo.java
- impl/maven-core/src/main/java/org/apache/maven/plugin/DefaultBuildPluginManager.java
JIRA issue: [MNG-8541](https://issues.apache.org/jira/browse/MNG-8541) …
> [MNG-8541] Support throwing Exception from Mojo#execute

- api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocation.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelValidatorTest.java
- impl/maven-impl/src/test/resources/poms/validation/raw-model/self-combine-bad.xml
- impl/maven-impl/src/test/resources/poms/validation/raw-model/self-combine-ok.xml
- impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
As Central has POMs using wrong values, causing even dependency collation to fail.
---
https://issues.apache.org/jira/browse/MNG-8513
> [MNG-8513] Move xml combination mode validation to validator

- impl/maven-jline/src/main/java/org/apache/maven/jline/FastTerminal.java
- impl/maven-jline/src/main/java/org/apache/maven/jline/JLineMessageBuilderFactory.java
No issue as no functional change done. Merely
simplifying FastTerminal and making JLine
factory (seemingly) complete.
> Simplify and complete method implementation

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/EncryptInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/goals/Init.java
- pom.xml
Update to 3.29.0
---
https://issues.apache.org/jira/browse/MNG-8550
> [MNG-8550] Update JLine3 to 3.29.0

- impl/maven-cli/pom.xml
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTestSupport.java
- impl/maven-cli/src/test/resources/mavenHome/conf/maven.properties
The whole UT suite was written to rely on maven.properties of the "outer build", hence UTs were not even running when built with Maven 3. Latest changes made it simply fail.
Fix the UT suite, as BasePasrser is depending on maven.properties being loaded, so provide one in a fake maven.home. Now the UT is always running, irrelevant of Maven being built with.
---
https://issues.apache.org/jira/browse/MNG-8554
> [MNG-8554] Fix UT suite for CLI

- compat/maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
This is a characterization test for existing behavior with ASCII characters. I'm going to add this to the docs as well but that's in a separate repo.
> [MNG-8241] Test comparing letters to numbers

- api/maven-api-model/src/main/mdo/maven.mdo
- compat/maven-model/src/test/java/org/apache/maven/model/pom/PomMemoryAnalyzer.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
JIRA issue: [MNG-7592](https://issues.apache.org/jira/browse/MNG-7592)
> [MNG-7592] String deduplication in model building

- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8561SourceRootTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8561/pom.xml
Add includes/excludes to the SourceKey
JIRA issue: [MNG-8561](https://issues.apache.org/jira/browse/MNG-8561)
> [MNG-8561] SourceRoot should be more lenient wrt duplicates

- api/maven-api-model/pom.xml
- api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocation.java
- api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocationTracker.java
- api/maven-api-model/src/main/java/org/apache/maven/api/model/InputSource.java
- api/maven-api-model/src/test/java/org/apache/maven/api/model/CacheManagerTest.java
- api/maven-api-model/src/test/java/org/apache/maven/api/model/InputLocationTest.java
- api/maven-api-model/src/test/java/org/apache/maven/api/model/InputSourceTest.java
- compat/maven-compat/src/main/java/org/apache/maven/project/interpolation/StringSearchModelInterpolator.java
- compat/maven-model/src/main/java/org/apache/maven/model/InputLocation.java
- compat/maven-model/src/main/java/org/apache/maven/model/InputSource.java
- compat/maven-model/src/test/java/org/apache/maven/model/v4/Xpp3DomPerfTest.java
- compat/maven-settings-builder/src/main/java/org/apache/maven/settings/io/DefaultSettingsReader.java
- compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/io/DefaultToolchainsReader.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java
- impl/maven-core/src/test/java/org/apache/maven/settings/PomConstructionWithSettingsTest.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSettingsXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultToolchainsXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/SettingsUtilsV4.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultDependencyManagementImporter.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultDependencyManagementImporterTest.java
- src/mdo/common.vm
- src/mdo/java/CacheManager.java
- src/mdo/java/Cacheable.java
- src/mdo/java/InputLocation.java
- src/mdo/merger.vm
- src/mdo/model.vm
- src/mdo/reader-stax.vm
JIRA issue: [MNG-8563](https://issues.apache.org/jira/browse/MNG-8563)
> [MNG-8563] Provide a weak cache for objects from the main model

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/MavenInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/transfer/SimplexTransferListener.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/transfer/ConsoleMavenTransferListenerTest.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/transfer/SimplexTransferListenerTest.java
One runtime and one testtime thread leak.
---
https://issues.apache.org/jira/browse/MNG-8565
> [MNG-8565] Thread leaks in maven-cli

- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTest.java
- impl/maven-executor/src/main/java/org/apache/maven/cling/executor/internal/ToolboxTool.java
- impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MavenExecutorTestSupport.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8400CanonicalMavenHomeTest.java
As they are used in various tests and test supporting code. Just to lessen download (once, and reuse same).
> Align Toolbox versions

- compat/maven-settings/src/site/apt/index.apt
Adjust link for Maven 4 Password Encryption
> Fix links to Settings Descriptor Reference

- api/maven-api-core/src/main/java/org/apache/maven/api/services/OsService.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultOsService.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/profile/OperatingSystemProfileActivator.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/util/Os.java
And move the OS static helper to util, is not
profile specific.
---
https://issues.apache.org/jira/browse/MNG-8573
> [MNG-8573] OS Service

- api/maven-api-cli/pom.xml
- api/maven-api-core/pom.xml
- compat/maven-builder-support/pom.xml
- compat/maven-compat/pom.xml
- compat/maven-embedder/pom.xml
- compat/maven-model-builder/pom.xml
- compat/maven-repository-metadata/pom.xml
- compat/maven-resolver-provider/pom.xml
- compat/maven-toolchain-builder/pom.xml
- compat/maven-toolchain-model/pom.xml
- impl/maven-cli/pom.xml
- impl/maven-cli/src/main/java/org/apache/maven/cling/utils/CLIReportingUtils.java
- impl/maven-core/pom.xml
- impl/maven-core/src/main/java/org/apache/maven/eventspy/EventSpy.java
- impl/maven-jline/pom.xml
- pom.xml
Fix inter-module connections
---
https://issues.apache.org/jira/browse/MNG-8517
> [MNG-8517] Cleanup dependencies

- impl/maven-core/src/main/java/org/apache/maven/internal/impl/SisuDiBridgeModule.java
- impl/maven-core/src/test/java/org/apache/maven/di/DiTest.java
JIRA issue: [MNG-8571](https://issues.apache.org/jira/browse/MNG-8571)
> [MNG-8571] Sisu @Priority annotation is not honoured

- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
JIRA issue: [MNG-8575](https://issues.apache.org/jira/browse/MNG-8575)
The use of `AbstractList` with an implementation that creates the whole list every time that `get(int)` is invoked implies that iterations over that list would have a performance cost of O(N²) where _N_ is the number of elements. Extending `AbstractSequentialList` instead brings back the performance cost to O(N) at least during iterations.
> [MNG-8575] Replace a list with O(N²) performance by O(N) at least during iteration.

- compat/maven-compat/src/main/java/org/apache/maven/toolchain/DefaultToolchain.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/MisconfiguredToolchainException.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/RequirementMatcher.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/RequirementMatcherFactory.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/Toolchain.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/ToolchainFactory.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/ToolchainManager.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/ToolchainManagerFactory.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/ToolchainManagerPrivate.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/ToolchainPrivate.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/java/JavaToolchain.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/java/JavaToolchainFactory.java
- compat/maven-compat/src/main/java/org/apache/maven/toolchain/java/JavaToolchainImpl.java
- compat/maven-compat/src/test/java/org/apache/maven/toolchain/DefaultToolchainManagerTest.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultJavaToolchainFactory.java
JIRA issue: [MNG-8558](http://issues.apache.org/jira/projects/MNG/issues/MNG-8558)
* move JavaToolchain support to maven-impl
* deprecate Maven 3 toolchain support classes
* add a factory to create toolchain managers wrapping both v3 and v4 toolchains
> [MNG-8558] Move JavaToolchain

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
This call has severe implications (re-ties logger, and in case is invoked multiple times, causes "loop").
Make sure it happens only once, This changes does not affect mvn and mvnd (it installs own stdout/stderr), but does affects mvnsh and resident maven,
---
https://issues.apache.org/jira/browse/MNG-8582
> [MNG-8582] Keep stdout/stderr functioning

- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvn/MavenOptions.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LayeredOptions.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/CommonsCliMavenOptions.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/LayeredMavenOptions.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/MavenParser.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8594AtFileTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8594/cmd.txt
- its/core-it-suite/src/test/resources/mng-8594/pom.xml
Where user can create ad-hoc command line parms. The difference between .mvn/maven.conf and this file is that this file allows goals as well. The CLI and atFile are merged, in this order, hence, goals in atFile will come AFTER goals specified on CLI, if CLI has them.
Source order (first wins for options, while goals are collected/aggregated from sources):
* CLI
* atFile (if specified, may have goals that are appended)
* maven.config (if present, may not have goals)
Note: option is called `af` or long `at-file` for similarity with `javac @file`, but commons CLI does not support options without leading hyphen.
---
https://issues.apache.org/jira/browse/MNG-8594
> [MNG-8594] Add atFile option

- impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- impl/maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomArtifactTransformerTest.java
- impl/maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java
JIRA issue: [MNG-8602](https://issues.apache.org/jira/browse/MNG-8602)
> [MNG-8602] Fix BOM consumer pom

- impl/maven-logging/src/main/java/org/apache/maven/slf4j/SimpleLoggerConfiguration.java
JIRA issue: [MNG-8605](https://issues.apache.org/jira/browse/MNG-8605)
> [MNG-8605] The log file should be appended to

- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/extensions/package-info.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/logging/package-info.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvn/package-info.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvnenc/package-info.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvnsh/package-info.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/package-info.java
- api/maven-api-core/src/main/java/org/apache/maven/api/feature/package-info.java
- api/maven-api-core/src/main/java/org/apache/maven/api/package-info.java
- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/package-info.java
- api/maven-api-core/src/main/java/org/apache/maven/api/plugin/package-info.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/package-info.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/package-info.java
- api/maven-api-metadata/src/main/java/org/apache/maven/api/metadata/package-info.java
- api/maven-api-model/src/main/java/org/apache/maven/api/model/package-info.java
- api/maven-api-plugin/src/main/java/org/apache/maven/api/plugin/annotations/package-info.java
- api/maven-api-plugin/src/main/java/org/apache/maven/api/plugin/descriptor/lifecycle/package-info.java
- api/maven-api-plugin/src/main/java/org/apache/maven/api/plugin/descriptor/package-info.java
- api/maven-api-settings/pom.xml
- api/maven-api-settings/src/main/java/org/apache/maven/api/settings/package-info.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/package-info.java
- api/maven-api-toolchain/pom.xml
- api/maven-api-toolchain/src/main/java/org/apache/maven/api/toolchain/package-info.java
JIRA issue: [MNG-8610](https://issues.apache.org/jira/browse/MNG-8610)
> [MNG-8610] Add javadoc for all o.a.m.api packages

- pom.xml
There is no sources parameter for maven-source-plugin
added in #2133
sources.jar still contains generated code 😄
> [MNG-8599] Fix configuration for maven-source-plugin

- api/maven-api-cli/pom.xml
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/CoreExtensions.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/InvokerRequest.java
- api/maven-api-cli/src/main/java/org/apache/maven/api/cli/ParserRequest.java
- compat/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- impl/maven-cli/pom.xml
- impl/maven-cli/src/main/java/org/apache/maven/cling/extensions/BootstrapCoreExtensionManager.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/extensions/LoadedCoreExtension.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseInvokerRequest.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/CoreExtensionSelector.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PrecedenceCoreExtensionSelector.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/MavenInvokerRequest.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/EncryptInvokerRequest.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnsh/ShellInvokerRequest.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTest.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTestSupport.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/resident/ResidentMavenInvokerTest.java
It all started with MNG-8615 to not swallow DI problems while loading core extensions. Then tried to add origin as well, but it turns out there is lack of context. Then turned out models are not location tracking. Then came MNG-8616 as Maven was too rigid and did not apply precedence for extensions making project hopping problematic, if not impossible...
Changes:
* do not swallow DI issues happened during core extension loading; belly up instead.
* report which extension caused DI issue
* make core extension models and IO location tracking
* alter CLI api to carry all extensions "by origin" (project, user, installation)
* parser should be plain dumb, all it does is load extensions in precedence order and validates them (validity: they must be GA unique)
* DI capsule performs now …
> [MNG-8615] [MNG-8616] Maven core extensions handling improvements

- .github/ci-extensions.xml
- .github/workflows/maven.yml
- its/core-it-suite/pom.xml
- its/core-it-suite/src/test/resources-filtered/it-mimir.properties
- pom.xml
Use Maveniverse Mimir to cache central artifacts. This makes caching way simpler as well. Update Maven used to build to Maven 4.0.0-rc-3 as well.
> [experiment] Mimir

- api/maven-api-core/src/main/java/org/apache/maven/api/DependencyScope.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProject.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/AbstractSession.java
`Session.requireDependencyScope(…)` is annotated as `@Nonnull` but its implementation can still return null, causing `NullPointerException` later. This pull request replace the null value by an `IllegalArgumentException` that describes the problem.
> Replace a `NullPointerException` by a more explicit error message

- .github/workflows/maven.yml
- Jenkinsfile
> Use Maven 3.9.9 for build maven-3.9.x branch

- apache-maven/src/bin/mvn
- apache-maven/src/bin/mvn.cmd
In order to avoid
WARNING A restricted method in java.lang.System has been called
https://issues.apache.org/jira/browse/MNG-8248
similar on master:
https://github.com/apache/maven/pull/1718
--- …
> [MNG-8248] Add enable-native-access to startup scripts

- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8400CanonicalMavenHomeTest.java
when we execute ITs without cleaning a project test will fail
> Remove old symbolic link in ITmng8400 test

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderRequest.java
- impl/maven-core/src/main/java/org/apache/maven/ReactorReader.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/MappedList.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3477DependencyResolutionErrorMessageTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4660ResumeFromTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6090CIFriendlyTest.java
- its/core-it-suite/src/test/resources-filtered/settings-remote.xml
- its/core-it-suite/src/test/resources-filtered/settings.xml
- its/core-it-suite/src/test/resources/mng-5175/settings-template.xml
As it turned out, ITs were not using Mimir as they redefined Maven Central to allow snapshots, and that made Mimir not handle the IT used Maven Central (while those did not contain snapshots, it was still pointing at canonical Maven Central URL).
Fixing this revealed several other (related or unrelated) issues:
* MavenProject was NPE prone regarding remote repositories handling
* MappedList was NPE prone regarding null values (emitted by MavenProject remote repositories)
several ProjectModelBuilder (detailed below) had no remote repositories set anymore (as central is not in super POM anymore)
* some ITs revaled ReactorReader issues as well
The `org.apache.maven.project.DefaultProjectBuilder issues` fixed:
* model request type CONSUMER_PARENT is used for non-locally built projects (ie. …
> [MNG-8646] Make IT tests use "outer" Mimir caching as well

- api/maven-api-core/src/main/java/org/apache/maven/api/SourceRoot.java
- api/maven-api-model/src/main/mdo/maven.mdo
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
JIRA issue: [MNG-8647](https://issues.apache.org/jira/browse/MNG-8647)
The `maven.mdo` file for the `<Source>` element said that the default directories are `src/${scope}/${lang}`. but this is effective only if no source is specified at all. It would be helpful to have this default value when some `<Source>` are specified. The intend is to allow users to write:
```xml
<build>
<sources>
<source>
<targetVersion>21</targetVersion>
</source>
<source>
<scope>test</scope>
</source>
</sources>
</build>
```
instead of:
```xml
<build>
<sources>
<source>
<directory>src/main/java</directory>
<targetVersion>21</targetVersion>
</source>
<source>
<scope>test</scope>
<directory>src/test/java</directory>
</source>
</sources>
</build>
```
> [MNG-8647] Set the default source directory to `src/${scope}/${lang}` as per documentation

- impl/maven-di/pom.xml
- impl/maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java
- impl/maven-di/src/test/java/org/apache/maven/di/impl/InjectorImplTest.java
JIRA issue: [MNG-8548](https://issues.apache.org/jira/browse/MNG-8548)
Adds cycle detection during instance creation in the DI container to prevent StackOverflowError when circular dependencies are present. The error message now clearly shows the dependency chain that caused the cycle.
> [MNG-8548] - Add cycle detection to dependency injection

- api/maven-api-core/src/main/java/org/apache/maven/api/Lifecycle.java
- impl/maven-core/src/main/java/org/apache/maven/ReactorReader.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java
- impl/maven-core/src/main/java/org/apache/maven/internal/impl/Lifecycles.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanExecutor.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildStep.java
- impl/maven-core/src/test/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanCreatorTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8653AfterAndEachPhasesWithConcurrentBuilderTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8653/child-1/pom.xml
- its/core-it-suite/src/test/resources/mng-8653/child-2/pom.xml
- its/core-it-suite/src/test/resources/mng-8653/pom.xml
JIRA issue: [MNG-8653](https://issues.apache.org/jira/browse/MNG-8653)
Fixes the existing 'all' phase and introduces a new 'each' phase to better support 
hierarchical builds and concurrent execution:
- 'all': Properly coordinates execution across parent-child project hierarchies
- 'each': A new phase that executes for each individual project in isolation
Key changes:
- Enhanced BuildPlanExecutor to properly handle parent-child relationships in phases
- Added new children() pointer type for explicit phase dependencies
- Improved phase dependency management to ensure:
- Parent's before:all executes before children's phases
- Children's after:all executes before parent's after:all
- Each project's phases execute in isolation within the 'each' phase
- Added comprehensive documentation to …
> [MNG-8653] Fix 'all' phase and  add 'each' phase

- apache-maven/src/assembly/maven/bin/mvn
- apache-maven/src/assembly/maven/bin/mvn.cmd
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8598JvmConfigSubstitutionTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8598/.mvn/jvm.config
- its/core-it-suite/src/test/resources/mng-8598/pom.xml
JIRA issue: [MNG-8598](https://issues.apache.org/jira/browse/MNG-8598)
Added support for substituting  `${MAVEN_PROJECTBASEDIR}` and `$MAVEN_PROJECTBASEDIR`
in `.mvn/jvm.config` with the actual project base directory.
Changes:
- Modified `mvn` and `mvn.cmd` scripts to handle the substitution
- Added integration test to verify the functionality
The test verifies:
- Both curly brace and simple syntax variants work
- Substitution happens correctly in forked JVM
- Feature is available in Maven 4.0+
> [MNG-8598] Add support for MAVEN_PROJECTBASEDIR substitution in jvm.config

- src/site/xdoc/index.xml
JIRA issue: [MNG-8467](https://issues.apache.org/jira/browse/MNG-8467)
Add links to configuring.html and maven-configuration.html in the main index page to improve documentation navigation and discoverability of configuration options.
> [MNG-8467] Add links to configuration pages in index.xml

- compat/maven-compat/src/main/java/org/apache/maven/repository/MetadataResolutionResult.java
- compat/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/VersionTest.java
Another batch of small cleanups IntelliJ noticed.
> minor cleanups

- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTestSupport.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MimirInfuser.java
- impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MavenExecutorTestSupport.java
- impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MimirInfuser.java
- impl/maven-executor/src/test/java/org/apache/maven/cling/executor/impl/ToolboxToolTest.java
- impl/maven-executor/src/test/resources-filtered/ut-mimir.properties
Make subproject maven-cli use "outer" Mimir (if used): This locally cuts UT runtime from 10+ sec to 2+ sec.
Same thing for maven-executor.
> Make maven-cli module tests use Mimir as well

- .github/ci-mimir-daemon.properties
- .github/workflows/maven.yml
We do not utilize LAN sharing on CI, caches are "local" only. 
Also, as can be seen, Jgroups may fail to start on Windoze.
> [CI] Disable Mimir JGroups node

- apache-maven/src/assembly/maven/bin/mvn
- apache-maven/src/assembly/maven/bin/mvn.cmd
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4559MultipleJvmArgsTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4559SpacesInJvmOptsTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6255FixConcatLines.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-4559-multiple-jvm-args/pom.xml
- its/core-it-suite/src/test/resources/mng-4559-spaces-jvm-opts/.mvn/jvm.config
- its/core-it-suite/src/test/resources/mng-4559-spaces-jvm-opts/pom.xml
JIRA issue: [MNG-4559](https://issues.apache.org/jira/browse/MNG-4559)
The .mvn/jvm.config file parsing in mvn.cmd needed improvements to properly handle multiple JVM arguments, especially when dealing with comments, quotes and spaces in values.
This PR:
- Ensures proper parsing of multiple JVM arguments from .mvn/jvm.config
- Maintains proper spacing between arguments
- Handles both inline and full-line comments correctly
- Fixes a bug in the space trimming logic (%%x -> %%i)
- Preserves spaces within quoted values
The changes are validated by MavenITmng4559MultipleJvmArgsTest which verifies:
- Multiple JVM arguments are properly handled
- Comments are correctly processed
- Arguments with spaces in quotes are preserved
- Arguments from multiple lines are properly combined
> [MNG-4559] Support spaces in jvm.config

- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
JIRA issue: [MNG-8662](https://issues.apache.org/jira/browse/MNG-8662)
Add missing methods for removing project source roots
> [MNG-8662] Add missing methods for removing project source roots

- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactResolver.java
The only spot where trace was set but not context, all the rest of the spots were checked and are ok.
---
https://issues.apache.org/jira/browse/MNG-8669
> [MNG-8669] Add missing context

- api/maven-api-annotations/src/main/java/org/apache/maven/api/annotations/Config.java
- api/maven-api-core/src/main/java/org/apache/maven/api/ExtensibleEnums.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Lifecycle.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ExtensibleEnumRegistry.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/MavenBuilderException.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelProblem.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProblemCollector.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilderRequest.java
- api/maven-api-core/src/main/java/org/apache/maven/api/services/TypeRegistry.java
- api/maven-api-di/src/main/java/org/apache/maven/di/tool/DiIndexProcessor.java
- api/maven-api-di/src/main/java/org/apache/maven/di/tool/package-info.java
- api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocation.java
- api/maven-api-model/src/main/java/org/apache/maven/api/model/InputSource.java
- api/maven-api-model/src/main/java/org/apache/maven/api/model/package-info.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ExtensibleEnumProvider.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/LanguageProvider.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/LifecycleProvider.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ModelTransformer.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/PackagingProvider.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/PathScopeProvider.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ProjectScopeProvider.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/SpiService.java
- api/maven-api-spi/src/main/java/org/apache/maven/api/spi/TypeProvider.java
- api/maven-api-xml/src/main/java/org/apache/maven/api/xml/XmlNode.java
- api/maven-api-xml/src/main/java/org/apache/maven/api/xml/XmlService.java
This PR adds missing Javadoc to various classes and interfaces in the API subprojects.
- Add class-level and method-level Javadoc to various classes in api/ subprojects
- Add missing package-info.java for org.apache.maven.di.tool package
- Enhance existing package-info.java files with more detailed documentation
- Ensure consistent Javadoc style across the API
These changes improve the API documentation, making it more comprehensive and consistent, which will help developers using the Maven API.
> Add missing Javadoc to API subprojects

- api/maven-api-core/src/main/java/org/apache/maven/api/services/PrompterException.java
- compat/maven-compat/src/main/java/org/apache/maven/internal/compat/interactivity/LegacyPlexusInteractivity.java
- impl/maven-jline/src/main/java/org/apache/maven/jline/DefaultPrompter.java
JIRA issue: [MNG-8660](https://issues.apache.org/jira/browse/MNG-8660)
The legacy prompter should only use the Prompter interface, not the DefaultPrompter implementaiton, so that the Maven daemon can override how prompting is implemented.
See https://github.com/apache/maven-mvnd/pull/1303
be performed on your pull …
> [MNG-8660] Decouple legacy prompter from implementation details

- impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
ValidationReportLevel isn't public so there shouldn't be a public constant with this type
> Avoid exposing non-public type outside its scope

- compat/maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
- impl/maven-impl/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3843PomInheritanceTest.java
The filtered resources were not added in mvn3, causing slight diffs when a model 4.0.0 project is built with mvn3 and mvn4.
---
https://issues.apache.org/jira/browse/MNG-8679
> [MNG-8679] Align superpom with mvn3

- Jenkinsfile
ITs can not use system default local repository as tests can install own artifacts.
It is a cause of unstable tests on 3.9.x branch on Jenkins
> Use dedicated local repo for ITs on Jenkins

- api/maven-api-core/src/main/java/org/apache/maven/api/SourceRoot.java
- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
JIRA issue: [MNG-8673](https://issues.apache.org/jira/browse/MNG-8673)
> [MNG-8673] SourceRoot includes and excludes should be String

- compat/maven-model-builder/src/main/java/org/apache/maven/model/building/FileModelSource.java
- compat/maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultModelResolver.java
When worked on https://github.com/apache/maven-resolver/commit/35c2d7579d0c1c1e577c4d847171102ca91be2c7 turned out that Resolver "demos" cannot run anymore on JIMFS. Restore that _minimally_ to make sure lowest possible binary compatibility disruption.
---
https://issues.apache.org/jira/browse/MNG-8687
> [MNG-8687] Restore ability to run on JIMFS

- impl/maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelValidatorTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3220ImportScopeTest.java
Only the one that is easy to be mixed up with GAV: DepMgtKey is GAT and not GAV. The rest (XML, PK/GA, REPOID, DIR, GAV) ones are not quite mixable, and string "A:B:C" is usually always assumed is GAV.
The problem with these two are that they look pretty much same (both a "A:B:C", colon segmented string of 3 or 4), but in one case C is dependency type, in other is version.
This PR now lessens the "A:B:C" string overload a bit, and also makes crystal clear that T is not V. The message is precise, but a bit longer. In turn, is not misleading at all now.
---
https://issues.apache.org/jira/browse/MNG-8676
> [MNG-8676] Improve model builder error messages

- apache-maven/src/assembly/component.xml
This just emits warning by assembly plugin, as is unused, since this module is gone.
> Drop unused assembly exclude

- impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
- impl/maven-core/src/test/resources/projects/pom-parent-version-from-nested-properties/pom.xml
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultInterpolator.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultInterpolatorTest.java
Fix for https://issues.apache.org/jira/browse/MNG-8694
@slawekjaranowski as mentioned today on jug challenge accepted!
> [MNG-8694] Fix version interpolation and ternary operator

- api/maven-api-model/src/main/mdo/maven.mdo
JIRA issue: [MNG-8674](https://issues.apache.org/jira/browse/MNG-8674)
> [MNG-8674] Deprecate mergeId in the Maven 3 model and remove it in the new model

- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
JIRA issue: [MNG-8707](https://issues.apache.org/jira/browse/MNG-8707)
This PR adds new methods to the `MavenProject` class to allow removing source roots, complementing the existing methods for adding them. This provides a more complete API for managing source roots in Maven projects.
- Added `removeCompileSourceRoot(String)` method to remove a compile source root
- Added `removeTestCompileSourceRoot(String)` method to remove a test compile source root
- Added `removePath(List<String>, String)` utility method to handle path removal
- Extracted common path handling logic into a new `sanitizePath(String)` method
- Added proper Javadoc with `@since 3.9.10` tags to new methods
- Added warning mechanism when source root collections are modified directly
- Improved code readability by …
> [MNG-8707] Add methods to remove compile and test source roots

- maven-model/src/main/mdo/maven.mdo
see https://issues.apache.org/jira/browse/MNG-8712
hoping this will help users discover how dependency version in `pom.xml` is completely different to every other versions like project or plugin
> [MNG-8712] dependency version is a requirement, not effective

- compat/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java
The Sisu "strict" flag has issues, but also, it is best and simplest to help transitioning by making Sisu in Maven 4 behave in very same way as it behaves in Maven 3.
---
https://issues.apache.org/jira/browse/MNG-8614
> [MNG-8614] Maven Sisu in Maven 4 same as in Maven 3

- api/maven-api-model/src/main/mdo/maven.mdo
Added it as deprecated indirection for legacy code.
It was removed 1y ago probably by mistake by this commit:
https://github.com/apache/maven/commit/2a9f39336cec1d8e52d30cc48503d51ed8672536
---
https://issues.apache.org/jira/browse/MNG-8719
> [MNG-8719] Restore Maven3 compat: model setInherited(boolean)

- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7587Jsr330.java
When we use the latest ASM, sisu test should be passed on every JDK
When we drop JDK 17 from build, the test will be skipped
> Test MavenITmng7587Jsr330 should be executed on every JDK

- apache-maven/src/main/appended-resources/licenses/unrecognized-asm-9.8.txt
- maven-core/pom.xml
- maven-embedder/pom.xml
- maven-model-builder/pom.xml
- maven-resolver-provider/pom.xml
- pom.xml
https://issues.apache.org/jira/browse/MNG-8722
Extends IT 
- https://github.com/apache/maven-integration-testing/pull/404
> [MNG-8722] Use a single standalone version of asm

- impl/maven-impl/src/main/java/org/apache/maven/impl/model/rootlocator/DefaultRootLocator.java
Applied proposed fix and a bit more.
---
https://issues.apache.org/jira/browse/MNG-8720
> [MNG-8720] Fix for symlinked project directory

- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTestSupport.java
No issue, as this is more about the MavenInvoker UTs. When invocation was throwing (and some test cases expect that), the whole maven output and possible errors were lost, making it hard to figure out in case of unexpected exit.
Now the test always emit, even if (expected) InvocationEx is being thrown.
> Improve invoker test

- api/maven-api-core/src/main/java/org/apache/maven/api/SourceRoot.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/PathSelectorTest.java
Following the revert of includes/excludes filters from `PathMatcher` to `String` in #2232, this pull request adds a new `SourceRoot.matcher(boolean)` method which provides the `PathMatcher`. Contrarily to the previous methods, this new method provides a single matcher combining the work of all includes and all excludes. The default implementation is ported from https://github.com/apache/maven-clean-plugin/pull/243.
> [MNG-8686] Add `SourceRoot.matcher(boolean)` method

- impl/maven-jline/src/main/java/org/apache/maven/jline/FastTerminal.java
- pom.xml
Also, add newly introduced methods to `FastTerminal`.
JLine 3.30.0 release notes:
https://github.com/jline/jline3/releases/tag/jline-3.30.0
---
https://issues.apache.org/jira/browse/MNG-8726
> [MNG-8726] Bump jlineVersion from 3.29.0 to 3.30.0

- impl/maven-executor/src/main/java/org/apache/maven/cling/executor/internal/ToolboxTool.java
- its/core-it-suite/src/test/resources/mng-7045/pom.xml
- its/core-it-suite/src/test/resources/mng-7160-extensionclassloader/extension/pom.xml
- its/core-it-suite/src/test/resources/mng-7587-jsr330/plugin/pom.xml
- pom.xml
Simple changes that makes build/ITs work with Java 24.
PR does not contains:
* action addition of Java 24 to CI
* updated Eclipse Sisu version (needed for that above)
---
https://issues.apache.org/jira/browse/MNG-8727
> [MNG-8727] Prepare for Java 24

- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTypeRegistry.java
- impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8525MavenDIPlugin.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8572DITypeHandlerTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/pom.xml
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/README.md
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/pom.xml
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/src/main/java/org/apache/maven/its/mng8572/extension/CustomType.java
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/src/main/java/org/apache/maven/its/mng8572/extension/CustomTypeProvider.java
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/src/main/java/org/apache/maven/its/mng8572/extension/NoOpMojo.java
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/dummy-artifact-pom.xml
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/install-dummy.sh
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/pom.xml
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/settings.xml
- its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/src/main/java/org/apache/maven/its/mng8572/test/DummyClass.java
This PR adds support for using the Maven API DI system in build extensions (plugins with extensions=true). It enables build extensions to provide custom artifact type handlers using the new DI mechanism.
- Added an integration test that demonstrates a custom artifact type handler using the Maven API DI system in a build extension
- The test shows how to implement a TypeProvider using `@Named` annotation
- The annotation processor automatically generates the DI index file
- The custom type handler is properly discovered and used during the build
This enhancement allows build extensions to leverage the new Maven API DI system, making it easier to create and maintain extensions that provide custom artifact type handlers.
Fixes: https://issues.apache.org/jira/browse/MNG-8572
> [MNG-8572] Support DI beans in build extensions

- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPluginXmlFactory.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPluginXmlFactoryTest.java
JIRA issue: [MNG-8729](https://issues.apache.org/jira/browse/MNG-8729)
follow up of:
- https://github.com/apache/maven/pull/2303
finally 100
> [MNG-8729] Use correct `outputStream` destination; `request` instead of `path` in `DefaultPluginXmlFactory#write`

- api/maven-api-cli/src/main/mdo/core-extensions.mdo
- api/maven-api-plugin/src/main/mdo/lifecycle.mdo
- api/maven-api-settings/src/main/mdo/settings.mdo
- api/maven-api-toolchain/src/main/mdo/toolchains.mdo
Attribute xml.schemaLocation is used by modello to generate documentations
We have mixed http/https, so it should be fixed to use everywhere https
> [MNG-8731] Use https for xsi:schemaLocation in generated descriptors

- api/maven-api-core/src/main/java/org/apache/maven/api/SourceRoot.java
- api/maven-api-model/src/main/mdo/maven.mdo
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
If a `<source>` element in POM does not provide any value for the `<directory>` element, the default value is currently defined as `src/${scope}/${lang}`. This default value provides the familiar `src/main/java` and `src/test/java` default directories. However, if the `<source>` element contains a `<module>` element, the module name must appear somewhere in the default directory name, otherwise the source code of multi-modular projects will collide.
Different conventions are possible:
* OpenJDK uses `src/${module}/` for the main code and a bazar of directories for the tests with no obvious order.
* [Project Jigsaw: Module System Quick-Start Guide](https://openjdk.org/projects/jigsaw/quick-start) uses `src/${module}/` for main code and does not mention tests.
* …
> [MNG-8713] SourceRoot.directory() default value should include the module when present

- maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
Just add it to CLIManager and make Maven 3 ignore it instead to belly up on it.
Also, help output should make it clear this is no-op option.
---
https://issues.apache.org/jira/browse/MNG-8734
> [MNG-8734] Make Maven 3.9.10 ignore --raw-streams option

- its/core-it-suite/pom.xml
As this is IT suite, but just to get rid of Security warning on GH. Update, as there is newer version we use, but the reported issue is for sure not exploitable as we use Jetty 9 in ITs only.
> Symbolic change (no issue)

- maven-core/src/main/java/org/apache/maven/graph/FilteredProjectDependencyGraph.java
Backport of 62f85a4233366064750079d50fd86ef25a97c6f3
---
https://issues.apache.org/jira/browse/MNG-8396
> [MNG-8396] Backport: add cache layer to the filtered dep graph

- impl/maven-impl/src/main/java/org/apache/maven/impl/AbstractSession.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifact.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactCoordinates.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactCoordinatesFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactDeployer.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactInstaller.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactResolver.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultChecksumAlgorithmService.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultDependencyCoordinatesFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultDependencyResolver.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultLocalRepository.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPluginXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultRepositoryFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultToolchainsXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultVersionParser.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultVersionResolver.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/ExtensibleEnumRegistries.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/ImplUtils.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java
Modernize codebase with Java improvements - Replace custom null checks with `Objects.requireNonNull`
- #2277
- #2287
> [chore] Modernize codebase with Java improvements - Replace custom null checks with `Objects.requireNonNull`

- compat/maven-toolchain-model/pom.xml
- compat/maven-toolchain-model/src/main/java/org/apache/maven/toolchain/model/io/xpp3/MavenToolchainsXpp3Reader.java
- compat/maven-toolchain-model/src/main/java/org/apache/maven/toolchain/model/io/xpp3/MavenToolchainsXpp3Writer.java
https://issues.apache.org/jira/browse/MNG-8761
> [MNG-8761] Add Maven 3 MavenToolchainsXpp3Reader/Writer

- impl/maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java
- impl/maven-di/src/test/java/org/apache/maven/di/impl/InjectorImplTest.java
When injecting List<T> dependencies, the DI container now sorts the
bindings by their @Priority annotation value in descending order
(highest priority first) to ensure deterministic ordering.
This change ensures that components with higher priority values
appear first in injected lists, providing predictable behavior
for dependency injection scenarios where order matters.
- Modified InjectorImpl.doGetCompiledBinding() to sort bindings
by priority before creating supplier lists
- Added comprehensive tests for priority-based list ordering
- Includes tests for mixed priorities and default priority handling
JIRA issue: [MNG-8764](https://issues.apache.org/jira/browse/MNG-8764)
> [MNG-8764] Sort injected lists by @Priority annotation

- impl/maven-core/src/test/java/org/apache/maven/model/PropertiesOrderTest.java
- impl/maven-core/src/test/java/org/apache/maven/model/WrapperPropertiesOrderTest.java
- src/mdo/java/WrapperProperties.java
- src/mdo/model-v3.vm
This PR fixes MNG-8746 by implementing property insertion order preservation in Maven's WrapperProperties class. The issue was that properties accessed through `model.getProperties()` were not maintaining their insertion order, leading to inconsistent behavior.
The WrapperProperties class in the Maven compat layer was not preserving the insertion order of properties. When properties were added through the Properties API and then accessed via methods like `keySet()` or `entrySet()`, they would be returned in an arbitrary order (often alphabetical) rather than the order they were inserted.
Implemented a comprehensive order preservation mechanism:
1. **Enhanced WrapperProperties Template** (`src/mdo/java/WrapperProperties.java`):
- Added internal `OrderedProperties` class that maintains …
> [MNG-8746] Preserve property insertion order in WrapperProperties

- impl/maven-di/src/main/java/org/apache/maven/di/impl/Binding.java
this api seems unused.
should we test this? @elharo
> chore: resolve unused `Binding#getDisplayString`

- impl/maven-impl/src/main/java/org/apache/maven/impl/cache/AbstractRequestCache.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/cache/AbstractRequestCacheTest.java
JIRA issue: [MNG-8767](https://issues.apache.org/jira/browse/MNG-8767)
When batch requests fail, individual exceptions are now added as suppressed
exceptions to preserve stack traces and error context for debugging.
- Modify AbstractRequestCache.requests() to call addSuppressed() for each failed request
- Add comprehensive test suite in AbstractRequestCacheTest to verify exception handling
- Test covers batch failures, mixed success/failure, and successful batch scenarios
> [MNG-8767] Add suppressed exceptions to BatchRequestException in AbstractRequestCache

- its/core-it-support/core-it-plugins/maven-it-plugin-uses-wagon/src/main/java/org/apache/maven/plugin/coreit/LookupWagonMojo.java
- https://github.com/apache/maven/pull/2424
ref 
- https://github.com/apache/maven/pull/2396#issuecomment-2936965168
> use `try-with-resources` statement in `LookupWagonMojo`

- .github/dependabot.yml
- add 'dependencies' label
- check GitHub Action in 3.x
> Improve configuration for dependabot in 3.x branch

- CONTRIBUTING.md
similar like in README in other projects
> Update CONTRIBUTING after GitHub issues enabled

- maven-model/src/main/mdo/maven.mdo
Not sure where this file has moved to in Maven 4, but for now this seems to be where the live site is pulled from.
> [MNGSITE-393] remove references to Maven 2

- .gitignore
SVG is a data file, not autogenerated
> Don't ignore SVG files

- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
Move method into lock scope as it is mutating MavenProject instance.
This ensures that instance mutation happens by single caller.
Fixes #2455
> Move project mutation inside project lock

- impl/maven-cli/pom.xml
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
- impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/BaseParserTest.java
- impl/maven-cli/src/test/resources/mavenHome/conf/maven.properties
- impl/maven-cli/src/test/resources/userHome/.m2/maven.properties
- impl/maven-cli/src/test/resources/userHome/.m2/settings.xml
Basically the two special paths from `extraInterpolationSource()` were never applied to user provided properties.
> User properties are not interpolated for paths

- api/maven-api-core/src/main/java/org/apache/maven/api/Artifact.java
- api/maven-api-core/src/main/java/org/apache/maven/api/ArtifactCoordinates.java
- api/maven-api-core/src/main/java/org/apache/maven/api/Dependency.java
- api/maven-api-core/src/main/java/org/apache/maven/api/DownloadedArtifact.java
- api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
- api/maven-api-core/src/main/java/org/apache/maven/api/SourceRoot.java
- api/maven-api-core/src/test/java/org/apache/maven/api/JavaPathTypeTest.java
The main purpose of this pull request is to put the file paths between quotes in the command line. For example instead of:
```
--module-source-path my.module=src/foo:src/bar
```
Format as:
```
--module-source-path my.module="src/foo:src/bar"
```
This pull request also contains opportunistic Javadoc formatting: missing dots at the end of summary sentences, missing closing `</p>` HTML tag.
> Add quotes in the command-line arguments formatted by `JavaPathType`.

- .github/workflows/release-drafter.yml
We should execute release drafter for branch in which we want to generate draft of release.
> Update branch name for release-drafter in maven-4.0.x

- .github/AUTO_PORT.md
- .github/workflows/auto-port.yml
This PR introduces a comprehensive GitHub Actions workflow for automated porting of changes between the `maven-4.0.x` branch (for 4.0.x releases) and the `master` branch (for 4.1.0 development).
**🆕 Updated Implementation**: Now uses the proven [korthout/backport-action](https://github.com/korthout/backport-action) instead of a custom implementation, providing better reliability and maintainability.
Maintaining fixes between the 4.0.x release branch and the 4.1.0 development branch (master) currently requires manual cherry-picking, which is:
- Time-consuming for maintainers
- Error-prone
- Often forgotten, leading to inconsistencies
- Difficult to track
This automated porting system provides:
- **`backport-to-4.0.x`** - Automatically backports PRs from master to maven-4.0.x
- …
> Add automated porting system between maven-4.0.x and master branches

- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh2532DuplicateDependencyEffectiveModelTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/gh-2532-duplicate-dependency-effective-model/module-a/pom.xml
- its/core-it-suite/src/test/resources/gh-2532-duplicate-dependency-effective-model/pom.xml
This PR fixes #2532 where a project POM installation may fail.
This only happens if the same dependency is somehow defined once in a regular way and another time with a property placeholder.  The reason is that the deduplication is wrongly done before interpolation.
Fixes #2532
> bug: fix duplicate dependency in effective model (fixes #2532)

- api/maven-api-core/src/main/java/org/apache/maven/api/Constants.java
- api/maven-api-core/src/main/java/org/apache/maven/api/feature/Features.java
- api/maven-api-core/src/test/java/org/apache/maven/api/feature/FeaturesTest.java
- impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/ConsumerPomArtifactTransformer.java
- impl/maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomArtifactTransformerTest.java
- src/site/markdown/configuration.yaml
Implements the ability to turn off build POM deployment as requested in [MNG-8568](https://issues.apache.org/jira/browse/MNG-8568).
Adds a new user property `maven.deploy.buildPom` that controls whether build POMs are deployed alongside consumer POMs in Maven 4.
- **Constants.java**: Added `MAVEN_DEPLOY_BUILD_POM` constant with proper `@Config` annotation
- **Features.java**: Added `deployBuildPom()` method following Maven 4 feature flag patterns
- **ConsumerPomArtifactTransformer.java**: Updated deployment logic to conditionally exclude build POMs
- **configuration.yaml**: Updated documentation for the new property
- **FeaturesTest.java**: New comprehensive test suite (12 test methods) for the feature flag
- **ConsumerPomArtifactTransformerTest.java**: Enhanced with 7 new test methods …
> [MNG-8568] Add maven.deploy.buildPom property to control build POM deployment

- pom.xml
- [chore: remove unused managed dependency (#2570)](https://github.com/apache/maven/pull/2570)
> [maven-4.0.x] chore: remove unused managed dependency (#2570)

- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- impl/maven-core/src/test/java/org/apache/maven/project/PluginConnectionSimpleTest.java
- [Fix MavenProject#getPlugin(String) performances (#2530)](https://github.com/apache/maven/pull/2530)
> [maven-4.0.x] Fix MavenProject#getPlugin(String) performances (#2530)

- .github/workflows/maven.yml
From security reason we should use a hash for GitHub action versions
> Pin GitHub action versions by hash

- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/ConcurrencyDependencyGraph.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/MultiThreadedBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparator.java
- impl/maven-core/src/test/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparatorTest.java
This enhancement improves parallel build efficiency by implementing intelligent project scheduling based on dependency chain analysis, inspired by the Takari Smart Builder approach.
- Orders projects by dependency chain length to prioritize critical path projects
- Uses algorithm: `weight = 1 + max(downstream_project_weights)`
- Ensures projects with longer downstream chains are built first
- Projects with equal weights are ordered by project ID for deterministic results
- Integrates smart scheduling for both initial and dynamic project ordering
- Maintains priority ordering when new projects become available
- Focuses solely on scheduling without external dependencies
- No file persistence or complex state management
- Deterministic behavior based on project structure
For a project …
> feat: enhance MultiThreadedBuilder with smart project scheduling

- impl/maven-xml/BENCHMARKS.md
- impl/maven-xml/pom.xml
- impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlPlexusConfiguration.java
- impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationBenchmark.java
- impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationConcurrencyBenchmark.java
- impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationMemoryBenchmark.java
- impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationOld.java
- impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationTest.java
- [Optimize XmlPlexusConfiguration for performance and thread safety (#2527)](https://github.com/apache/maven/pull/2527)
> [maven-4.0.x] Optimize XmlPlexusConfiguration for performance and thread safety (#2527)

- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultSourceRootTest.java
- [Bug fix in the default directory computed by `DefaultSourceRoot`. (#10912)](https://github.com/apache/maven/pull/10912)
> [maven-4.0.x] Bug fix in the default directory computed by `DefaultSourceRoot`. (#10912)

- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
Address the comment at https://github.com/apache/maven/pull/10921#discussion_r2210635789 by renaming all single letter variables in the DefaultModelValidator class to improve code readability.
- **Renamed method parameters**: `s` → `session`, `m` → `model`, `d` → `dependency`
- **Renamed loop variables**: `i` → `index`, `j` → `charIndex`, `n` → `size`
- **Renamed local variables**: `p` → `plugin`/`reportPlugin`, `f` → `frameIterator`, `c` → `character`, `e` → `exception`
- **Updated validateModelVersion method** to accept Session parameter and include Maven version in error messages
- **Renamed string parameter** to `requestedModel` for clarity
- **Improved code readability**: Variable names now clearly indicate their purpose
- **Better maintainability**: Easier for developers to …
> Rename single letter variables in DefaultModelValidator

- impl/maven-di/src/main/java/org/apache/maven/di/Injector.java
- impl/maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java
- impl/maven-di/src/test/java/org/apache/maven/di/impl/InjectorImplTest.java
- impl/maven-testing/src/main/java/org/apache/maven/api/di/testing/MavenDIExtension.java
Dispose() clears all internal state including bindings, scopes, singleton caches, and loaded URLs Add unit test verifying that injector no longer provides disposed bindings
- [X ] Your pull request should address just one issue, without pulling in other changes.
- [X ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [X ] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
- …
> Implement Injector.dispose() and add cleanup test

- api/maven-api-core/src/main/java/org/apache/maven/api/services/PathMatcherFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPathMatcherFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPathMatcherFactoryTest.java
This PR adds a comprehensive PathMatcherFactory service to Maven 4 API with directory filtering optimization capabilities, addressing the need for exclude-only pattern matching and performance optimizations.
- `createPathMatcher(baseDirectory, includes, excludes, useDefaultExcludes)` - Full control over include/exclude patterns
- `createPathMatcher(baseDirectory, includes, excludes)` - Convenience overload without default excludes
- `createExcludeOnlyMatcher(baseDirectory, excludes, useDefaultExcludes)` - **NEW**: Exclude-only pattern matching
- `createIncludeOnlyMatcher(baseDirectory, includes)` - Convenience method for include-only patterns
- `deriveDirectoryMatcher(fileMatcher)` - **NEW**: Directory filtering optimization
- Full implementation of all PathMatcherFactory methods
- …
> Add PathMatcherFactory service with directory filtering optimization

- impl/maven-core/pom.xml
- impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelper.java
- impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedConfigurationConverter.java
- impl/maven-core/src/test/java/org/apache/maven/configuration/internal/CompositeBeanHelperPerformanceTest.java
- impl/maven-core/src/test/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelperTest.java
This PR optimizes the performance of `CompositeBeanHelper` by implementing caching for frequently accessed reflection operations.
```
Benchmark                                                                      Mode  Cnt   Score   Error  Units
CompositeBeanHelperPerformanceTest.benchmarkOptimizedHelper                    avgt    5  17,473 ± 1,537  us/op
CompositeBeanHelperPerformanceTest.benchmarkOptimizedHelperMultipleProperties  avgt    5  24,902 ± 1,994  us/op
CompositeBeanHelperPerformanceTest.benchmarkOptimizedHelperMultipleTypes       avgt    5  14,124 ± 1,293  us/op
CompositeBeanHelperPerformanceTest.benchmarkOptimizedHelperRepeatedOperations  avgt    5  74,146 ± 4,325  us/op
CompositeBeanHelperPerformanceTest.benchmarkOriginalHelper                     avgt    5  18,716 ± 2,615 …
```
> Optimize CompositeBeanHelper performance with comprehensive caching

- api/maven-api-core/src/main/java/org/apache/maven/api/Constants.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPluginXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSettingsXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultToolchainsXmlFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/XmlFactoryTransformerTest.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/model/InterningTransformerTest.java
- src/site/markdown/configuration.properties
- src/site/markdown/configuration.yaml
- src/site/markdown/maven-configuration.md
This PR expands the value interning optimization in Maven's XML parsing and fixes transformer usage across all XML factories to improve memory efficiency during Maven builds.
Expanded the `InliningTransformer` in `DefaultModelBuilder` to intern **16 additional commonly repeated contexts** (from 11 to 27 total):
**Added contexts:**
- **Dependency-related**: `type`, `classifier`
- **Build and plugin-related**: `goal`, `execution`
- **Common metadata**: `modelVersion`, `name`, `url`, `system`, `distribution`, `status`
- **SCM fields**: `connection`, `developerConnection`, `tag`
- **Common enum-like values**: `id`, `inherited`, `optional`
Fixed all XML factories to properly use the transformer from `XmlReaderRequest`:
- ✅ `DefaultSettingsXmlFactory` - Now uses transformer
- ✅ …
> Expand value interning optimization and fix XML factory transformer usage

- impl/maven-core/pom.xml
- impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelper.java
- impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedConfigurationConverter.java
- impl/maven-core/src/test/java/org/apache/maven/configuration/internal/CompositeBeanHelperPerformanceTest.java
- impl/maven-core/src/test/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelperTest.java
- [perf: optimize CompositeBeanHelper with reflection caching](https://github.com/apache/maven/pull/2526)
> [maven-4.0.x] perf: optimize CompositeBeanHelper with reflection caching

- api/maven-api-core/src/main/java/org/apache/maven/api/services/ProblemCollector.java
- compat/maven-builder-support/src/test/java/org/apache/maven/building/ProblemCollectorFactoryTest.java
…n.api.services to address [MNG-8449], enabling selective problem collection via Predicate, with thread-safe handling and integration with existing lossy behavior, tested thoroughly to ensure robust severity and message-based filtering.
- [X ] Your pull request should address just one issue, without pulling in other changes.
- [ X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ X] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not …
> [MNG-8449] - Add Filtering Support to ProblemCollector

- impl/maven-executor/src/main/java/org/apache/maven/api/cli/ExecutorRequest.java
- impl/maven-executor/src/main/java/org/apache/maven/cling/executor/forked/ForkedMavenExecutor.java
- its/core-it-suite/pom.xml
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/Verifier.java
* Add skipMavenRc to ExecutorRequest and use it in ITs
ITs should be isolated from the executing system, so:
- skip mavenrc in forked mode
- exclude MAVEN_ARGS and MAVEN_OPTS from test environments
(cherry picked from commit e2ad3e6abcf9676a996668a721ceb84232d1300e)
- #10925
> Add skipMavenRc to ExecutorRequest and use it in ITs

- api/maven-api-xml/src/main/java/org/apache/maven/api/xml/XmlNode.java
- impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
- impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlNodeImplTest.java
This will backport the following commits from `maven-4.0.x` to `master`:
- [Fix XmlNode.equals returning false between two different node implementations (#10942)](https://github.com/apache/maven/pull/10942)
> [master] Fix XmlNode.equals returning false between two different node implementations (#10942)

- api/maven-api-core/src/main/java/org/apache/maven/api/services/PathMatcherFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPathMatcherFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPathMatcherFactoryTest.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/PathSelectorTest.java
Minor modifications to the `PathMatcherFactory` service:
* Simplify the patch matcher when possible.
* Add a `PathMatcherFactory.includesAll()` method.
The two changes, combined together, allows the caller to know when a matcher includes all files. The Maven Clean Plugin needs this information for deciding if it can delete the files in a background thread.
> Add PathMatcherFactory.includesAll()

- impl/maven-core/src/main/java/org/apache/maven/project/DefaultDependencyResolutionRequest.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultDependencyResolutionResult.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingRequest.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingResult.java
- impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectDependenciesResolver.java
- impl/maven-core/src/main/java/org/apache/maven/project/DependencyResolutionException.java
- impl/maven-core/src/main/java/org/apache/maven/project/DependencyResolutionRequest.java
- impl/maven-core/src/main/java/org/apache/maven/project/DependencyResolutionResult.java
- impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuilder.java
- impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuildingException.java
- impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuildingRequest.java
- impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuildingResult.java
- impl/maven-core/src/main/java/org/apache/maven/project/ProjectDependenciesResolver.java
Deprecates the old project builder API in favor of the new `org.apache.maven.api.services.ProjectBuilder` API, following the same pattern used for the model builder API deprecation.
This addresses the issue mentioned in #10984 where `ProjectBuildingResult` exposes `ModelProblem` from the deprecated model builder API, creating an inconsistency since `ModelProblem` is deprecated but `ProjectBuildingResult` was not.
- Added `@Deprecated(since = "4.0.0")` annotations to all project builder related classes and interfaces
- Added deprecation messages pointing users to `org.apache.maven.api.services.ProjectBuilder`
- Follows the exact same deprecation pattern used for the model builder API
**Core Project Builder API:**
- `ProjectBuilder` - Main interface
- `ProjectBuildingRequest` - Request …
> Deprecate old project builder API in favor of new API

- apache-maven/src/bin/mvn.cmd
Fixes #10937 by introducing an additional INTERNAL_MAVEN_OPTS for any arguments that need to be inserted by the script. Parsing the externally-defined MAVEN_OPTS variable can lead to incorrect processing of quotes and special characters, so use the separate variable to avoid doing so.
Specifically, this fixes this case:
```
$env:MAVEN_OPTS='"-Dfoo=bar|baz"'
mvn
```
by implementing proposed fix 2 from #10937
---
[Individual Contributor …
> Avoid parsing MAVEN_OPTS (3.9.x)

- apache-maven/src/assembly/maven/bin/mvn
- apache-maven/src/assembly/maven/bin/mvn.cmd
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10937QuotedPipesInMavenOptsTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/gh-10937-pipes-maven-opts/.mvn/jvm.config
- its/core-it-suite/src/test/resources/gh-10937-pipes-maven-opts/pom.xml
Fixes #10937 by introducing an additional INTERNAL_MAVEN_OPTS for any arguments that need to be inserted by the script. Parsing the externally-defined MAVEN_OPTS variable can lead to incorrect processing of quotes and special characters, so use the separate variable to avoid doing so.
Additionally JVM_CONFIG_MAVEN_OPTS is introduced as its own variable to preserve the append behaviour.
Specifically, this fixes this case:
```
$env:MAVEN_OPTS='"-Dfoo=bar|baz"'
mkdir .mvn
New-Item .mvn\jvm.config
mvn
```
by implementing proposed fix 2 from https://github.com/apache/maven/issues/10937
The related fix for 3.9.x branch is in PR #10969
---
This may …
> Avoid parsing MAVEN_OPTS (master/4.x)

- impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
- [Port the bug fixes identified when using that class in Maven clean and compiler plugin (#10935)](https://github.com/apache/maven/pull/10935)
> [maven-4.0.x] Port the bug fixes identified when using that class in Maven clean and compiler plugin (#10935)

- apache-maven/src/assembly/maven/bin/m2.conf
Fixes #10996
When external tools like IntelliJ launch Maven directly using the ClassWorlds launcher without setting the `maven.mainClass` system property, Maven fails with:
```
org.codehaus.plexus.classworlds.launcher.ConfigurationException: No such property: maven.mainClass
```
The m2.conf file was changed to use `${maven.mainClass}` but this property is only set by the Maven launcher scripts (`mvn` and `mvn.cmd`). External tools that launch Maven directly don't set this property.
This change adds a default value for `maven.mainClass` in m2.conf:
```
set maven.mainClass default org.apache.maven.cling.MavenCling
```
1. When Maven launcher scripts run, they set `-Dmaven.mainClass=org.apache.maven.cling.MavenCling` (or other variants for `--enc`, `--shell`, `--up`)
2. When external tools …
> Fix maven.mainClass property missing for external tools

- api/maven-api-core/src/main/java/org/apache/maven/api/services/PathMatcherFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPathMatcherFactory.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPathMatcherFactoryTest.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/PathSelectorTest.java
This is a backport of #10964. The following is copied from the original pull request:
Minor modifications to the `PathMatcherFactor` service:
* Make package-private.
* Ensure that `simplify()` is always invoked.
* Add `PathMatcherFactory.includesAll()` and `isIncludesAll(PathMatcher)` methods.
The Maven Clean Plugin needs this information for checking if it can run in a background thread.
> Backport of "Add PathMatcherFactory.includesAll()"

- apache-maven/src/assembly/maven/bin/m2.conf
- [Fix maven.mainClass property missing for external tools (#10998)](https://github.com/apache/maven/pull/10998)
> [maven-4.0.x] Fix maven.mainClass property missing for external tools (#10998)

- impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparator.java
- impl/maven-core/src/test/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparatorTest.java
Fixes #10995 - Resolves `IllegalStateException: Recursive update` in `SmartProjectComparator` during parallel builds of large multi-module projects.
The `SmartProjectComparator.getProjectWeight()` method was using `ConcurrentHashMap.computeIfAbsent()` in a recursive context. When `calculateWeight()` calls `getProjectWeight()` for downstream projects, it creates recursive `computeIfAbsent()` calls that violate ConcurrentHashMap's internal constraints, leading to:
```
java.lang.IllegalStateException: Recursive update
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1760)
at org.apache.maven.lifecycle.internal.builder.multithreaded.SmartProjectComparator.getProjectWeight(SmartProjectComparator.java:83)
```
- **Replace `computeIfAbsent()`** with …
> Fix recursive update issue in SmartProjectComparator

- .github/workflows/maven.yml
As build takes a long time when a new commit is pushed, 
we should cancel previous build and build only the last one.
> Allow single build per branch or pull request

- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelBuilderTest.java
Backport of https://github.com/apache/maven/pull/11037
On parent loading, the repositories were interpolated okay, but there was a problem that parent own properties were not considered in interpolation (of own repositories).
Fixes #11021
> Uninterpolated repositories from parent POMs during model building (backport)

- impl/maven-jline/src/main/java/org/apache/maven/jline/MessageUtils.java
Wait for the AnsiConsole#systemInstall call in the FastTerminal background thread before uninstalling. Otherwise a quickly finishing build might leave the terminal and system streams in a broken state.
the [Apache License Version 2.0, January …
> [#11048]  Fix race condition in MessageUtils

- api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/XmlReaderRequest.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPluginXmlFactoryTest.java
- [Fix XMLReader#getURL and enable the unit test (#11069)](https://github.com/apache/maven/pull/11069)
> [maven-4.0.x] Fix XMLReader#getURL and enable the unit test (#11069)

- impl/maven-core/src/main/java/org/apache/maven/project/ConnectedResource.java
- impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
- impl/maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
- impl/maven-core/src/test/java/org/apache/maven/project/ResourceIncludeTest.java
- impl/maven-core/src/test/resources-project-builder/target-path-regression/pom.xml
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
- impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultSourceRootTest.java
- [Fix targetPath parameter ignored in resource bundles (fixes #11062) (#11063)](https://github.com/apache/maven/pull/11063)
> [maven-4.0.x] Fix targetPath parameter ignored in resource bundles (fixes #11062) (#11063)

- compat/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Port of Maven 3 bugfix to Maven 4 (deprecated) `maven-embedder` module. Maven 4 by default is **not affected**, but this PR aligns Maven 3 and deprecated `maven-embedder` module in Maven 4.
The "early" session used to load extension will populate cache in MavenExecutionRequest and same cache is later reused in "normal" session as well.
This is wrong, as if project uses same parent POM as any of loaded extnsions, data loss in form of lost input locations occurs.
Fixes #11081
> Bug: bad cache isolation between two sessions

- impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectBuilder.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultDependencyResolver.java
- impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultDependencyResolverResult.java
This is an alternative to pull request #2219 resolving the same issue, but with more emphasis that `PathModularizationCache` should not be created in the `DefaultDependencyResolverResult` constructor, and that doing so is a temporary hack that may be removed in a future version. More specifically:
* Make package-private the `DefaultDependencyResolverResult` constructor having a `PathModularizationCache` argument, because the latter is package-private.
* Add a public constructor without the cache argument for codes in other packages that need to instantiate `DefaultDependencyResolverResult`  directly.
* Put a warning in the javadoc saying that this constructor may be removed in a future version.
* Add `PathModularizationCache` private field in `DefaultDependencyResolver`. This is partially …
> [MNG-8696] Hide the cache from DefaultDependencyResolverResult constructor

- src/mdo/java/InputLocation.java
- src/mdo/java/InputLocationTracker.java
- src/mdo/model.vm
This ports #11128 to master.
- modello templates: add Objects.requireNonNull(key, "key") in InputLocation.getLocation(Object)
- modello templates: document non-null key requirement in InputLocationTracker and method Javadoc
- ensure generated model code across modules reflects the contract
Formatting via Spotless; verified local generation and targeted module build. Full CI will validate the entire reactor.
After merge, we can consider back/forward-port alignment as needed.
---
Pull Request opened by [Augment Code](https://www.augmentcode.com/) with guidance from the PR author
> Fix #11127: enforce non-null keys for InputLocation lookups and document behavior (master)

- impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
- impl/maven-core/src/test/resources/projects/modules-empty/child/pom.xml
- impl/maven-core/src/test/resources/projects/modules-empty/pom.xml
- impl/maven-core/src/test/resources/projects/subprojects-empty/child/pom.xml
- impl/maven-core/src/test/resources/projects/subprojects-empty/pom.xml
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
When a profile from the current pom defines subprojects somehow, the discovery mechanism should not kick in.
- Treat explicit empty <subprojects/> as disabling discovery.
- Base decision solely on explicit subprojects/modules in the main model; ignore profiles.
Fixes #11114
> Fix subproject discovery kicking in too often

- api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
> Add missing equals and hashCode methods in modular Java path type.

- maven-core/src/main/java/org/apache/maven/project/MavenProject.java
This PR improves the warning message for deprecated source root collection modifications to address concerns raised in #11089.
- **More specific method recommendations**: Instead of generic "add/remove methods", now shows exact method names:
- For `compileSourceRoots`: "Use MavenProject.addCompileSourceRoot()/removeCompileSourceRoot() methods instead"
- For `testCompileSourceRoots`: "Use MavenProject.addTestCompileSourceRoot()/removeTestCompileSourceRoot() methods instead"
- **Clearer language**: Changed "Direct modification of" to "Plugin is modifying" to make it clearer what's happening
- **More concise messaging**: Removed redundant phrases while keeping essential information
- **Better debugging information**: Improved the debug stack trace message description
- **Ecosystem health**: …
> Improve source root modification warning message

- impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
- impl/maven-core/src/test/resources/projects/modules-empty/child/pom.xml
- impl/maven-core/src/test/resources/projects/modules-empty/pom.xml
- impl/maven-core/src/test/resources/projects/subprojects-empty/child/pom.xml
- impl/maven-core/src/test/resources/projects/subprojects-empty/pom.xml
- impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
- [model-builder: simplify subproject auto-discovery decision (#11124)](https://github.com/apache/maven/pull/11124)
> [maven-4.0.x] model-builder: simplify subproject auto-discovery decision (#11124)

- maven-core/src/main/java/org/apache/maven/plugin/prefix/internal/DefaultPluginPrefixResolver.java
Simplify prefix resolution and drop use of BuildPluginManager (as descriptor will be re-resolved again later) and focus only on prefix to GA resolution, using a map of rules:
* collect POM enlisted plugin groupId:artifactId pairs that come from non-settings-enlisted groupIDs (and allow only enlisted artifactIDs)
* add settings enlisted plugin groupIds (keep their order) but "allow any" artifactId
Using this map, figure out plugin GA from prefix using Maven metadata only.
Fixes #11067
Backport of 2b7bb9c6fdb7b4bedc9b1c0581c70dc5b5a19671
ITs fix:
- https://github.com/apache/maven-integration-testing/pull/412
> Simplify prefix resolution

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
- [Improve mvn usage message (#11211)](https://github.com/apache/maven/pull/11211)
> [maven-4.0.x] Improve mvn usage message (#11211)

- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
- impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PrecedenceCoreExtensionSelector.java
- impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
- its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh11181CoreExtensionsMetaVersionsTest.java
- its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/pw-metaversion-is-invalid/.mvn/extensions.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/pw-metaversion-is-invalid/pom.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-metaversion-is-valid/HOME/.m2/extensions.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-metaversion-is-valid/pom.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-different-version-is-conflict/.mvn/extensions.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-different-version-is-conflict/HOME/.m2/extensions.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-different-version-is-conflict/pom.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-same-version-is-not-conflict/.mvn/extensions.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-same-version-is-not-conflict/HOME/.m2/extensions.xml
- its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-same-version-is-not-conflict/pom.xml
Changes:
* validate for metaversions in extensions XML
* conflict detection should not report conflict for same V
* support for metaversions during extension resolution
Fixes #11181
Backport of 033bf6f9dfe710dbe4927cea7e3f57aa9b2f4b9b
> GH-11181 Metaversion validation and lax conflict detection (#11184)

- .github/workflows/maven.yml
maven-4.0.x caches are `mvn40` and master caches
are now `mvn`. No need to repeat the "mimir" string everywhere.
> Rename cache keys
