apache/maven

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
I found a small typo and I fixed it.
=> Fixed typo 'propery' to 'property'

maven-compat/src/test/java/org/apache/maven/repository/DefaultMirrorSelectorTest.java, maven-core/src/test/java/org/apache/maven/graph/DefaultProjectDependencyGraphTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorSubModulesTest.java
Similar to Pull Request #83, I found more test names I believe are misspelled, and this pull request simply addresses those misspellings.
=> Fixing misspellings in test names

maven-compat/src/main/java/org/apache/maven/repository/legacy/LegacyRepositorySystem.java
=> Fixed typo in exception logging

CONTRIBUTING.md, apache-maven/README.txt
The details are in https://issues.apache.org/jira/browse/MNG-6559.
=> [MNG-6559] Fix mailing list URL

Jenkinsfile
Signed-off-by: Mickael Istria <mistria@redhat.com>
=> Always deploy snapshot from master

pom.xml
=> [MNG-6718] Upgrade to plexus-utils 3.2.1

maven-compat/src/main/java/org/apache/maven/project/inheritance/DefaultModelInheritanceAssembler.java
Relates to the 735b72fcf1b848ee424d6755e5a624fbcbc65862 commit.
To make …
=> [MNG-6844] Remove outdated TODOs

maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java, maven-core/src/test/java/org/apache/maven/graph/DefaultGraphBuilderTest.java
=> [MNG-6863] - Fixing that --also-make is being ignored when calling --resume-from

maven-model-builder/pom.xml, maven-model-builder/src/test/java/org/apache/maven/model/interpolation/StringSearchModelInterpolatorTest.java, pom.xml
https://jira.apache.org/jira/browse/MNG-6856
https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven/job/MNG-6856/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/maven/320)
=> [MNG-6856] Remove dependency to Powermock

Jenkinsfile.its, pom.xml
=> Add a Jenkinsfile to run it test (per default it runs it master branch but now there is a parameter to use a different it source branch)

maven-core/src/main/java/org/apache/maven/project/MavenProject.java, maven-core/src/test/java/org/apache/maven/DefaultMavenTest.java
=> [MNG-5868] No duplicate artifacts in attached artifacts

maven-core/src/main/java/org/apache/maven/DefaultMaven.java
@rfscholte Here it is, prerequisite for release profile removal.
=> [MNG-7019] Notify also at start when profile is missing

maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepositoryPolicy.java, maven-compat/src/test/java/org/apache/maven/artifact/AbstractArtifactComponentTestCase.java, maven-compat/src/test/java/org/apache/maven/repository/legacy/DefaultWagonManagerTest.java, maven-core/src/main/java/org/apache/maven/bridge/MavenRepositorySystem.java, maven-model/src/main/mdo/maven.mdo, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/ArtifactDescriptorUtils.java
Signed-off-by: rfscholte <rfscholte@apache.org>
Signed-off-by: Michael Osipov <michaelo@apache.org>
=> [MNG-5728] Switch the default checksum policy from "warn" to "fail"

maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepositoryPolicy.java, maven-compat/src/test/java/org/apache/maven/artifact/AbstractArtifactComponentTestCase.java, maven-compat/src/test/java/org/apache/maven/repository/legacy/DefaultWagonManagerTest.java, maven-core/src/main/java/org/apache/maven/bridge/MavenRepositorySystem.java, maven-model/src/main/mdo/maven.mdo, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/ArtifactDescriptorUtils.java
=> Revert "[MNG-5728] Switch the default checksum policy from "warn" to "fail""

maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java, maven-core/src/test/resources-settings/test-pom-and-settings-interpolation/pom.xml
=> [MNG-7071] Remove the profiles.xml functionality, which is ignored since Maven 3.

maven-core/src/main/java/org/apache/maven/DefaultMaven.java, maven-core/src/main/java/org/apache/maven/MissingProfilesException.java, maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionRequest.java, maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java, maven-core/src/main/java/org/apache/maven/execution/ProfileActivation.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java, maven-model-builder/src/main/java/org/apache/maven/model/building/ModelProblem.java, maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java, maven-model-builder/src/test/java/org/apache/maven/model/validation/DefaultModelValidatorTest.java, maven-model-builder/src/test/resources/poms/validation/invalid-profile-id.xml
=> [MNG-7051] - Optionally skip non-existing profiles and break on missing required profiles

maven-core/src/main/java/org/apache/maven/DefaultMaven.java
This PR is raised because the functionality should be consistent with project selection: 
https://github.com/apache/maven/pull/446#discussion_r579859091
Relevant Integration test: https://github.com/apache/maven-integration-testing/pull/102
If your pull request is about ~20 lines of …
=> [MNG-7051] When an optional profile could not be found, an info message should be thrown instead of a warning.

maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java, maven-core/src/test/java/org/apache/maven/graph/DefaultGraphBuilderTest.java
=> [MNG-7102] The child modules of excluded projects are now excluded

maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java, maven-core/src/test/java/org/apache/maven/graph/DefaultGraphBuilderTest.java
Follow-up from !448
To make clear that you license your contribution …
=> [MNG-7102] Exclude all children of aggregators, even if the aggregator was already removed from the reactor.

maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/java/org/apache/maven/cli/CLIManagerDocumentationTest.java
This PR is layered on top of #433 
To make clear that you license your …
=> [MNG-7080] Add a --color option to simplify color support

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
=> [MNG-7032] Evaluate --help and --version after configuring the logging/color

apache-maven/src/assembly/shared/run.cmd
=> [MNG-7197] Simplify exit code handling in Windows command startup script

README.md, maven-bom/pom.xml, pom.xml
Replace ci-builds occurences by ci-maven
- ~[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
pulling in other changes.~
- ~[ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
commit message.~
- ~[ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
be performed on …
=> [chore] - Update CI environment

maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/test/java/org/apache/maven/model/building/DefaultModelBuilderTest.java
as it ignores pom file
To make clear that you license your contribution …
=> [MNG-7226] DefaultModelBuilder.buildRawModel fails

maven-core/src/main/java/org/apache/maven/graph/DefaultProjectDependencyGraph.java
=> [MNG-7271] - Code Improvement

pom.xml
=> [MNG-7274] - JUnit Jupiter via BOM

maven-core/src/main/java/org/apache/maven/graph/DefaultProjectDependencyGraph.java, maven-core/src/main/java/org/apache/maven/project/ProjectSorter.java
=> [MNG-7272] - Code Improvement - II

maven-caching/src/main/java/org/apache/maven/caching/HttpCacheRepositoryImpl.java
=> [MNG-7129] Remove redundant http calls to cache

maven-caching/src/main/java/org/apache/maven/caching/CacheControllerImpl.java, maven-caching/src/main/java/org/apache/maven/caching/artifact/RestoredArtifact.java, maven-caching/src/main/java/org/apache/maven/caching/xml/CacheConfig.java, maven-caching/src/main/java/org/apache/maven/caching/xml/CacheConfigImpl.java
Provide CLI flags to restore artifacts lazily which could provide significant performance benefits especially if huge bundles cached. In this mode artifacts are downloaded from cache on demand only which gives significant performance boost especially with remote cache
If your pull …
=> [MNG-7129] Restore artifacts from cache lazily

maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java
=> Remove duplicate call to longOpt

src/main/java/org/apache/maven/buildcache/CachingMojosExecutionStrategy.java
=> MNG-7129 fix for cleanup of partial state

maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
Proposed changes for https://github.com/apache/maven/pull/651:
* validate input
* do not modify loop invariant within loop body
Remarks:
* IF we allow "null" life-cycles then modify validation from `if ( len < 1 || len % 2 != 0 )` to `if ( len % 2 != 0 )`
* IF we do NOT allow "null" life-cycles, then modify validation from `if ( len < 1 || len % 2 != 0 )` to `if ( len < 2 || len % 2 != 0 )`
(and in both cases adjust exception message as well)
=> Proposal to change abstract provider

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleStarter.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/ReactorContext.java, maven-core/src/main/java/org/apache/maven/session/scope/internal/SessionScope.java, maven-core/src/test/java/org/apache/maven/session/scope/internal/SessionScopeTest.java
Same as https://github.com/apache/maven/pull/621 but for 3.8.x branch.
=> [3.8.x][MNG-7347] SessionScoped beans should be singletons for a given session

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java, maven-core/src/main/java/org/apache/maven/plugin/internal/ValidatingConfigurationListener.java
=> [MNG-5222]  Maven 3 no longer logs warnings about deprecated plugin  parameters

apache-maven/src/assembly/maven/conf/logging/simplelogger.properties, maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
Addendum to be2b7f890d98af20eb0753650b6605a68a97ac05:
* fix property name to align with existing ones
* fix logging configuration as no more shaded httpClient
* fix constant names
=> [MNG-7454] Include resolver-transport-http in Maven

pom.xml
Updates Maven Resolver to 1.8.0.
---
https://issues.apache.org/jira/browse/MNG-7453
=> [MNG-7453] Update Resolver to 1.8.0 (3.9.x)

pom.xml
Updates Maven Resolver to latest 1.8.0.
---
https://issues.apache.org/jira/browse/MNG-7453
=> [MNG-7453] Update Resolver to 1.8.0 (master)

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java, maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java, maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginConfigurationValidator.java, maven-core/src/main/java/org/apache/maven/plugin/internal/ValidatingConfigurationListener.java
This is backport of commit 9ac2d08dc7dec66acc2c835710065b677190e700 from master to maven-3.9.x branch.
--- …
=> [MNG-5222] Improvement in deprecated params detection

maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedPluginValidator.java
=> [MNG-7457] Warn about deprecated plugin Mojo

maven-core/src/main/java/org/apache/maven/plugin/internal/AbstractMavenPluginParametersValidator.java, maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java, maven-core/src/main/java/org/apache/maven/plugin/internal/ReadOnlyPluginParametersValidator.java
=> [MNG-7464] Warn about using read-only parameters for Mojo in configuration

pom.xml
This saves quite some time on the build.
https://issues.apache.org/jira/browse/MNG-7405
=> [MNG-7405] Update animal-sniffer to 1.21

maven-model/pom.xml, pom.xml
Update parent POM to v 36.
---
https://issues.apache.org/jira/browse/MNG-7491
=> [MNG-7491] Update parent POM 36

pom.xml
Update parent POM to v 36.
---
https://issues.apache.org/jira/browse/MNG-7491
=> [MNG-7491] Update parent POM 36 (3.9.x)

maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultMojoExecutionConfigurator.java
(cherry picked from commit 54f9d91ebb05ff8a051272c4e91dca4ee4984d80)
To make clear that you …
=> [MNG-7468] Check unsupported plugins parameters in configuration - 3.9

maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultMojoExecutionConfigurator.java
=> [MNG-7504] Don't print warning unsupported reportPlugins for m-site-p

maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java, maven-embedder/src/test/java/org/apache/maven/cli/event/ExecutionEventLoggerTest.java
https://issues.apache.org/jira/browse/MNG-7501
implementing option 1
```
[INFO] --< org.apache.maven.its.plugins:maven-it-plugin-dependency-resolution >--
[INFO] Building Maven IT Plugin :: Dependency Resolution 2.1-SNAPSHOT   [31/78]
[INFO]     from core-it-support/core-it-plugins/maven-it-plugin-dependency-resolution/pom.xml
[INFO] ----------------------------[ maven-plugin ]----------------------------
```
=> MNG-7501 display relative path to pom.xml

apache-maven/pom.xml
This closes #770
@abstratt Please check
=> [MNG-7515] Cannot see a dependency tree for apache-maven module

maven-compat/src/main/java/org/apache/maven/repository/MetadataResolutionRequest.java, maven-compat/src/test/java/org/apache/maven/repository/legacy/DefaultUpdateCheckManagerTest.java, maven-core/plugin-manager.txt, maven-core/src/main/java/org/apache/maven/DefaultProjectDependenciesResolver.java, maven-core/src/main/java/org/apache/maven/ProjectDependenciesResolver.java, maven-core/src/main/java/org/apache/maven/plugin/internal/MavenPluginValidator.java, maven-core/src/main/java/org/apache/maven/project/artifact/MavenMetadataSource.java, maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/MavenExecutionPlanTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/PhaseRecorderTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/builder/BuilderCommonTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/LifecycleExecutionPlanCalculatorStub.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/ProjectDependenciesResolverStub.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/ProjectDependencyGraphStubTest.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java, maven-model-builder/src/test/java/org/apache/maven/model/building/FileModelSourceTest.java
Fix minor typos in code :
- test method names,
- method parameter names,
- variable names.
Public API is not modified by this PR, so it should be safe to merge.
Following this checklist to help us incorporate your contribution quickly and easily:
If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the developers list. To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
=> Fix typos in code

maven-embedder/pom.xml
=> [MNG-7521] - Remove WARNING during build

maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
=> Fix MNG-7529

pom.xml
=> [MNG-7530] Upgrade Apache Maven parent POM to version 37

maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
Ensure that any versions resolved as part of a version range request
only reference repositories that are actually enabled for the type of
version (SNAPSHOT versions against snapshot repos, release versions
against release repositories).
If your pull request is about ~20 lines of code you don't need to …
=> [MNG-7529] Maven resolver makes bad repository choices

apache-maven/src/main/appended-resources/META-INF/NOTICE.vm, apache-maven/src/main/appended-resources/licenses/unrecognized-aopalliance-1.0.txt, maven-core/pom.xml, maven-embedder/pom.xml, maven-model-builder/pom.xml, maven-resolver-provider/pom.xml, pom.xml
=> [MNG-7502] Upgrade to Guice 5.1.0

maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/MojoDescriptor.java, maven-plugin-api/src/main/mdo/plugin.mdo
=> [MNG-7463] Improve documentation about deprecation in Mojo

maven-core/src/main/java/org/apache/maven/lifecycle/DefaultLifecycles.java, maven-core/src/test/java/org/apache/maven/lifecycle/DefaultLifecyclesTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/LifecycleExecutionPlanCalculatorTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/DefaultLifecyclesStub.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/LifecycleExecutionPlanCalculatorStub.java
Related issue: https://issues.apache.org/jira/browse/MNG-7310
Related PR for integration tests: https://github.com/apache/maven-integration-testing/pull/131
---
[Individual Contributor License …
=> [MNG-7310] Using the plexusContainer to prevent loading lifecycle defined by extensions from other submodules.

maven-model/src/main/mdo/reader-ex.vm, maven-model/src/main/mdo/reader.vm, maven-model/src/test/java/org/apache/maven/model/v4/ModelXmlTest.java, maven-settings/src/main/mdo/reader.vm, maven-toolchain-model/src/main/mdo/reader.vm
See https://issues.apache.org/jira/browse/MNG-6801
=> [MNG-6801] MavenXpp3Writer doesn't retain order of properties

maven-artifact/src/main/java/org/apache/maven/artifact/versioning/VersionRange.java, maven-artifact/src/test/java/org/apache/maven/artifact/versioning/VersionRangeTest.java
=> [MNG-7106] Accept same lower and upper bound in version spec string

maven-artifact/src/main/java/org/apache/maven/artifact/versioning/VersionRange.java, maven-artifact/src/test/java/org/apache/maven/artifact/versioning/VersionRangeTest.java
=> [MNG-7106] Maven 3.9 Accept same lower and upper bound in version spec string

maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java, maven-embedder/src/test/java/org/apache/maven/cli/event/ExecutionEventLoggerTest.java
This code change was accidentally already merged into master, and then reverted. This is the [original PR](https://github.com/apache/maven/pull/783).
---
This PR ensures that when a multi module project is resumed halfway, the project progress counter is not reset. 
[Related issue](https://issues.apache.org/jira/browse/MNG-7098).
be performed on your …
=> [MNG-7098] Keep the project counter intact when resuming a multi-module project.

.github/workflows/maven_build_itself.yml, api/maven-api-core/src/main/java/org/apache/maven/api/Dependency.java, api/maven-api-core/src/main/java/org/apache/maven/api/Listener.java, api/maven-api-settings/src/main/mdo/settings.mdo, maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4.java, maven-model-builder/src/main/java/org/apache/maven/model/inheritance/DefaultInheritanceAssembler.java, maven-model/src/main/mdo/writer-ex.vm, maven-model/src/main/mdo/writer.vm, maven-plugin-api/pom.xml, maven-plugin-api/src/main/mdo/writer.vm, maven-repository-metadata/src/test/java/org/apache/maven/artifact/repository/metadata/MetadataTest.java, maven-settings/src/main/mdo/writer.vm, maven-toolchain-model/src/main/mdo/writer.vm
Fix site generation using 4.0.0-alpha-1.
It is currently broken because the report plugins are badly merged.
=> Fix site generation

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java, maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptorBuilder.java, maven-plugin-api/src/main/mdo/plugin.mdo
Takes precedence over POMs Maven prerequisite
To make clear that you license your …
=> [MNG-7570] Plugin descriptor can carry required Maven version

api/maven-api-model/src/main/mdo/maven.mdo
DOC - spelling fix in maven.mdo file …
=> DOC - spelling fix in maven.mdo file

maven-model/src/main/java/org/apache/maven/model/WrapperProperties.java, maven-settings/src/main/java/org/apache/maven/settings/WrapperProperties.java, maven-toolchain-model/src/main/java/org/apache/maven/toolchain/model/WrapperProperties.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7584
=> [MNG-7584] The properties-maven-plugin fails to load project properties

maven-plugin-api/pom.xml, maven-plugin-api/src/main/mdo/plugin.mdo
Improve descriptions
Add anchors
[MNG-7575] Remove deprecated requiresReports
Relax validation of "configuration" by marking it as "DOM"
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you …
=> [MNG-7569] Add new v4Api element

maven-core/src/main/java/org/apache/maven/DefaultMaven.java
I propose this cosmetic (key change is in new line 485, two other changes - CS:LineLength).
This allows to deactivate profiles from settings and from pom with the same id, and avoid confusing warning:
```
$ mvn -P \!XYZ verify
...
[WARNING] The requested profile "XYZ" could not be activated because it does not exist.
...
```
Similar issues
- MNG-7211 (done in unspecified version, while MNG-7051 fixed in v4)
--- 
title in the …
=> [MNG-7568] Consider inactive profiles for validation

api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/Execute.java
=> [MPLUGIN-439] Support custom lifecycle phase ids in Execute annotation

maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
=> [MNG-7590] Allow to configure resolver by properties in settings.xml

.github/workflows/maven.yml, .github/workflows/maven_build_itself.yml
Old actions use deprecated node 12
- cache v2 -> v3
- checkout v2 -> v3
- download-artifact v2 -> v3
- setup-java v2 -> v3
- disable access to GITHUB_TOKEN
- don't store credentials with checkout
- don't execute build for PR from local repository branches - we have build on push event
---
If your pull …
=> Update actions in GH build

maven-core/src/main/java/org/apache/maven/DefaultMaven.java, maven-core/src/main/java/org/apache/maven/internal/aether/ResolverLifecycle.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, pom.xml
Update to Maven Resolver 1.9.1 and apply required changed changes in Maven.
Changes:
- hook in lifecycle
---
https://issues.apache.org/jira/browse/MNG-7586
=> [3.9.x][MNG-7586] Update Maven Resolver to 1.9.1

maven-core/src/main/java/org/apache/maven/DefaultMaven.java, maven-core/src/main/java/org/apache/maven/internal/aether/ResolverLifecycle.java, pom.xml
Changes:
- hook in lifecycle
---
https://issues.apache.org/jira/browse/MNG-7586
=> [MNG-7586] Update Maven Resolver to 1.9.1

maven-core/src/main/java/org/apache/maven/internal/impl/PropertiesAsMap.java, maven-core/src/test/java/org/apache/maven/internal/impl/PropertiesAsMapTest.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7597
=> [MNG-7597] Fix infinite loop when iterating PropertiesAsMap

maven-core/src/test/java/org/apache/maven/internal/impl/TestRepositorySystem.java, maven-core/src/test/java/org/apache/maven/repository/TestRepositorySystem.java, maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelProcessor.java, maven-model-builder/src/main/java/org/apache/maven/model/io/DefaultModelReader.java, maven-model-builder/src/main/java/org/apache/maven/model/io/ModelReader.java, maven-model-builder/src/main/java/org/apache/maven/model/superpom/DefaultSuperPomProvider.java, maven-model-builder/src/test/java/org/apache/maven/model/inheritance/DefaultInheritanceAssemblerTest.java
Restore `ModelReader` compatibility which had been switched to new api too soon...
=> [MNG-7576] Restore compatibility with maven 3.x

maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
LocalRepositoryManager needs configurations from RepositorySystemSession so must be created after session configuration is finished.
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you …
=> [MNG-7600] LocalRepositoryManager is created too early

maven-core/src/main/java/org/apache/maven/internal/aether/ResolverLifecycle.java, pom.xml
Updates resolver to latest release.
---
https://issues.apache.org/jira/browse/MNG-7586
=> [MNG-7586] Update Maven Resolver to 1.9.2

maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
=> Maven 3.9 backport [MNG-7561] never resolve versions with same upper and lower bound

maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/main/java/org/apache/maven/model/profile/ProfileActivationContext.java
=> [MNG-6609] Maven 3.9: profile activation by packaging

maven-core/src/main/resources/META-INF/maven/extension.xml
=> [MNG-7616] Fix missing exported artifacts

maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
Adds new feature: Chained Local Repository Manager.
---
https://issues.apache.org/jira/browse/MNG-7612 …
=> [MNG-7612] Chained LRM

Jenkinsfile
=> simplify build and get rid of withMaven

maven-bom/pom.xml, pom.xml
=> [MNG-7626] maven-bom should have the same parent version as project

.github/pull_request_template.md
PR template has multiple actions associated to the same bullet, this result in confusion and required actions not taken.
each atomic task should have its own bullet.
---
[Individual Contributor …
=> [MNG-7643] Each atomic task should have its own bullet

maven-core/src/test/java/org/apache/maven/project/ProjectBuilderTest.java, maven-core/src/test/projects/project-builder/MNG-7648/pom.xml, maven-core/src/test/remote-repo/org/apache/maven/its/bom/0.1/bom-0.1.pom, maven-core/src/test/remote-repo/org/apache/maven/its/bom/maven-metadata.xml, maven-core/src/test/remote-repo/org/apache/maven/its/parent/0.1/parent-0.1.pom, maven-core/src/test/remote-repo/org/apache/maven/its/parent/maven-metadata.xml, maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuildingRequest.java
This is backport / cherry-pick of #940.
--
To make clear …
=> [MNG-7648] Fix locationTracking in DefaultModelBuildingRequest copy constructor

maven-model-builder/src/main/java/org/apache/maven/model/interpolation/DefaultModelVersionProcessor.java
This closes #945
To make clear that you license your …
=> [MNG-7658] CI-friendly versions should only come/rely on user properties

Jenkinsfile
=> Jenkinsfile: pickup results from ITs and Maven 3.8.x for build

pom.xml
Update Maven Resolver to 1.9.4
---
https://issues.apache.org/jira/browse/MNG-7668
=> [maven-3.9.x] [MNG-7668] Update Resolver to 1.9.4

maven-core/src/main/java/org/apache/maven/lifecycle/providers/CleanLifecycleProvider.java, maven-core/src/main/java/org/apache/maven/lifecycle/providers/DefaultLifecycleProvider.java, maven-core/src/main/java/org/apache/maven/lifecycle/providers/SiteLifecycleProvider.java, maven-core/src/main/java/org/apache/maven/lifecycle/providers/WrapperLifecycleProvider.java, maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
Finally use 3.x plugins for all.
---
https://issues.apache.org/jira/browse/MNG-7666
=> [MNG-7666] Update default binding and lifecycle plugin versions

.github/workflows/maven.yml, Jenkinsfile
=> Execute IT tests with clean local repository

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
=> [MNG-7672] Fork should only execute the project and its submodules

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
=> [3.9.x] [MNG-7672] Fork should only execute the project and its submodules

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
=> [3.8.x] [MNG-7672] Fork should only execute the project and its submodules

maven-core/src/main/java/org/apache/maven/settings/SettingsUtilsV4.java
=> [MNG-7673] IllegalArgumentException thrown for invalid checksum 'never'

maven-core/src/main/java/org/apache/maven/ReactorReader.java
Ignore `ExecutionEvent` if execution `lifecyclePhase` is `null`.
--- …
=> [MNG-7689] Check if execution lifecycle phase is not null

maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
And have it aligned with install plugin. These two now provides all the fixes and new functionalities like working deployAtEnd etc.
---
https://issues.apache.org/jira/browse/MNG-7702
=> [MNG-7702] Update to Maven Deploy Plugin 3.1.0

pom.xml
Updates resolver to 1.9.5 w/ many fixes.
---
https://issues.apache.org/jira/browse/MNG-7695
=> [MNG-7695] Update resolver to 1.9.5

pom.xml
(when the fixed release is done, this is just a placeholder)
---
https://issues.apache.org/jira/browse/MNG-7710
=> [maven-3.9.x][MNG-7710] Upgrade plexus-utils to 3.5.1

maven-core/src/main/java/org/apache/maven/plugin/internal/DeprecatedCoreExpressionValidator.java
The implementation for MNG-7706 is wrong: it checks parameter **name** where it should check **type** and **defaultValue** (expression) instead.
---
https://issues.apache.org/jira/browse/MNG-7717
=> [MNG-7717] Maven warns wrongly about deprecated parameter

maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/ConcurrencyDependencyGraph.java
If ConcurrencyDependencyGraph#getRootSchedulableBuilds returns an empty list then MultiThreadedBuilder is locked forever as it never gets a build result (because nothing is scheduled).
This changes the method, that in such case just the first project is returned, this might not give the best performance, but ensures that there is at least one build scheduled and the build-loop can proceed.
If this is merged I can contribute a fix for 3.9.x as well!
This relates to:
- https://github.com/eclipse-tycho/tycho/issues/2169
The fix for this issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com). …
=> [3.8.x][MNG-7716] ConcurrencyDependencyGraph deadlock if no root is selected

maven-core/src/test/java/org/apache/maven/project/ProjectModelResolverTest.java, maven-resolver-provider/src/test/java/org/apache/maven/repository/internal/DefaultModelResolverTest.java, pom.xml
Adjust some UTs as error message did change.
---
https://issues.apache.org/jira/browse/MNG-7715
=> [MNG-7715] Update to resolver 1.9.6

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
Backport of fix.
---
https://issues.apache.org/jira/browse/MNG-7720
=> [3.8.x] [MNG-7720] Wrong build order of forked projects

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
Forward port of fix.
---
https://issues.apache.org/jira/browse/MNG-7720
=> [MNG-7720] Wrong build order of forked projects

pom.xml
=> [MNG-7710] Upgrade plexus-utils to 3.5.1

maven-xml-impl/src/test/java/org/apache/maven/internal/xml/XmlNodeImplTest.java
=> Additional XmlNode tests from plexus-utils

maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
Port of https://github.com/codehaus-plexus/plexus-utils/commit/bf198ff5d8f3bd5eb90d09826006c4d419884660
=> [MNG-7709] Regression in configuration merge

pom.xml
That carries mostly transport-http bugfixes and improvements.
---
https://issues.apache.org/jira/browse/MNG-7723
=> [MNG-7723] Upgrade to Maven Resolver 1.9.7

maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
=> [MNG-7725] Update surefire to 3.0.0 in default binding

maven-core/src/test/java/org/apache/maven/project/artifact/DefaultMavenMetadataCacheTest.java, maven-core/src/test/java/org/apache/maven/repository/TestRepositorySystem.java
I think this code is all unused, but let's see...
=> remove unused branches in fake

pom.xml
=> [MNG-7749] Upgrade animal-sniffer from 1.21 to 1.23

maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactCoordinateFactory.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactFactory.java
=> [MNG-6825] Replace StringUtils

maven-slf4j-provider/src/main/java/org/slf4j/impl/MavenLoggerFactory.java
=> Simplify logger creation leveraging Map.computeIfAbsent

maven-core/src/test/java/org/apache/maven/toolchain/DefaultToolchainManagerTest.java, pom.xml
=> [MNG-7766] - Migrate to use mockito-bom 4.11.0

pom.xml
Upgrade resolver to 1.9.8 (was 1.9.7).
---
https://issues.apache.org/jira/browse/MNG-7753
=> [MNG-7753] Upgrade to Resolver 1.9.8

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Changes:
* resolve file argument against workingDirectory explicitly
* the check Files.isRegularFile should happen against path
=> [MNG-7038] Fixes for topDirectory

maven-model-builder/src/main/java/org/apache/maven/model/building/ArtifactModelSource.java
=> [MNG-7783] Profile source point to file instead of to module

api/maven-api-core/src/main/java/org/apache/maven/api/services/SuperPomProvider.java, maven-core/src/main/java/org/apache/maven/DefaultMaven.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSuperPomProvider.java, maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/main/java/org/apache/maven/model/superpom/DefaultSuperPomProvider.java
=> [MNG-7784] Fix compatibility for SuperPomProvider

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java, maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
Added NONE and INLINE modes.
---
https://issues.apache.org/jira/browse/MNG-7787
=> [MNG-7787] Introduce new options for plugin validation report

pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7587
=> [3.9.x][MNG-7587] Upgrade to sisu 0.9.0.M2

pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7587
=> [MNG-7587] Upgrade to sisu 0.9.0.M2

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Backport of https://github.com/apache/maven/pull/1130
=> [3.9.x][MNG-7796] Be lenient when using toRealPath

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
Make BRIEF a legal value again.
---
https://issues.apache.org/jira/browse/MNG-7797
=> [MNG-7797] Return BRIEF mode

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
But to show no issue, as locality to be shown is not in "to be shown" ones.
---
https://issues.apache.org/jira/browse/MNG-7799
=> [MNG-7799] Plugin validation may falsely report there are issues

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java, maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java, maven-embedder/src/test/java/org/apache/maven/cli/event/ExecutionEventLoggerTest.java
=> [MNG-7795] IllegalArgumentException: 'other' has different root during plugin validation

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/projects/mavenConfigProperties/.mvn/maven.config
JIRA issue: https://issues.apache.org/jira/projects/MNG/issues/MNG-7698
=> [MNG-7698] Support comments in maven.config

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/projects/mavenConfigProperties/.mvn/maven.config
Backport of https://github.com/apache/maven/pull/1134
---
https://issues.apache.org/jira/browse/MNG-7698
=> [MNG-7698] Allow comments in .mvn/maven.config

maven-embedder/pom.xml, maven-embedder/src/main/java/org/apache/maven/cli/CLIManager.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
After a discussion with @rmannibucau, @slawekjaranowski and @michael-o, I think this is the best solution.
The env CI check is done in Java code, making it easy to unit test. Also, a new flag had to be added to de-activate the CI=true behavior (named `--force-interactive`). To make it consistent I created an additional flag/alias to -B (`--non-interactive`). The flags were suggested by @michael-o since it's also used in other widely used CLI tools such as SVN.
Happy to hear your thoughts.
Relevant [maven-integration-testing PR](https://github.com/apache/maven-integration-testing/pull/209)
--- 
require a JIRA …
=> [MNG-7338] Automatically activate batch-mode and make output quiet when running in CI.

maven-core/src/main/java/org/apache/maven/lifecycle/providers/WrapperLifecycleProvider.java, maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
Changes:
install: 3.1.0 -> 3.1.1
deploy: 3.1.0 -> 3.1.1
resources: 3.3.0 -> 3.3.1
compiler: 3.10.1 -> 3.11.0
surefire: 3.0.0 -> 3.1.2
plugin: 3.7.0 -> 3.9.0
wrapper: 3.1.1 -> 3.2.0
---
https://issues.apache.org/jira/browse/MNG-7790
=> [MNG-7790] Update lifecycle plugins

maven-core/src/main/resources/META-INF/plexus/default-bindings.xml
Changes:
install: 3.1.0 -> 3.1.1
deploy: 3.1.0 -> 3.1.1
resources: 3.3.0 -> 3.3.1
compiler: 3.10.1 -> 3.11.0
surefire: 3.0.0 -> 3.1.2
plugin: 3.7.0 -> 3.9.0
wrapper: 3.1.1 -> 3.2.0
---
https://issues.apache.org/jira/browse/MNG-7790
=> [3.9.x][MNG-7790] Update lifecycle plugins

maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
Changes:
* antrun: 1.3 -> 3.1.0
* assembly: 2.2-beta-5 -> 3.6.0
* dependency: 2.8 -> 3.6.0
* release: 2.5.3 -> 3.0.1 (and removed config)
---
https://issues.apache.org/jira/browse/MNG-7807
=> [MNG-7807] Super POM plugin updates

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
=> [MNG-7806] Plugins verification - remove used in module(s) report

maven-core/src/main/java/org/apache/maven/DefaultMaven.java
=> Simplify code

maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
Changes:
* war 3.3.2 -> 3.4.0
---
https://issues.apache.org/jira/browse/MNG-7790
=> [MNG-7790] Update lifecycle plugins, take 2

maven-core/src/main/resources/META-INF/plexus/default-bindings.xml
Changes:
* war 3.3.2 -> 3.4.0
---
https://issues.apache.org/jira/browse/MNG-7790
=> [3.9.x][MNG-7790] Update lifecycle plugins, take 2

apache-maven/pom.xml, maven-slf4j-provider/pom.xml, pom.xml
Changes:
* buildnumber 1.4 -> 3.2.0
* buildhelper 1.12 -> 3.4.0
* checksum ? -> 1.11
=> [3.9.x] Update some ancient build plugins

apache-maven/pom.xml, maven-slf4j-provider/pom.xml, pom.xml
=> Update some build plugins

maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
The original patch is made by: Christian Schulte <schulte@apache.org>
Supersedes #295
=> [MNG-5600] Dependency management import should support exclusions

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
=> [MNG-7811] Plugins verification - reporting improvements

maven-core/src/main/java/org/apache/maven/internal/impl/DefaultToolchainsBuilder.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultMojoExecutionConfigurator.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/ProjectBuildList.java, maven-core/src/main/java/org/apache/maven/lifecycle/mapping/LifecyclePhase.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-model/src/test/java/org/apache/maven/model/DeveloperTest.java
=> [MNG-7764] Small code improvements

pom.xml
Resolver 1.9.11 release notes:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12353188
---
=> [MNG-7800] Update to Resolver 1.9.11

pom.xml
=> [3.9] [MNG-7800] Update resolver to 1.9.12

pom.xml
=> [MNG-7800] Update resolver to 1.9.12

maven-embedder/src/site/apt/logging.apt, maven-slf4j-provider/src/site/apt/index.apt
some parts are obsolete, undocumented or even simply wrong because misunderstood
=> update logging documentation

pom.xml
=> [3.9.x][MNG-7800] Update to resolver 1.9.13

pom.xml
=> [MNG-7800] Update resolver to 1.9.13

pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7824
=> [MNG-7824] Bump plexus-xml from 4.0.0 to 4.0.1

Jenkinsfile.s390x
JIRA issue: https://issues.apache.org/jira/browse/MNG-7848
Apache INFRA team has installed necessary JDK flavours on all s390x nodes (Please check issue https://issues.apache.org/jira/projects/INFRA/issues/INFRA-24781). We’d like to add the s390x build and test pipeline to Jenkins CI by adding `Jenkinsfile.s390x` to the code base.
Can anyone from Maven team help us review the PR and create the s390x pipeline on Jenkins? Thanks!
------------------------------------------------------------------------------- …
=> [MNG-7848] Add s390x pipeline to Jenkins CI

Jenkinsfile.s390x
This PR aims to change the notification recipients in `Jenkinsfile.s390x` to Linux on IBM Z Open Source Team.
------------------------------------------------------------------------------------- …
=> [MNG-7848] Change the notification recipients in s390x pipeline

Jenkinsfile.s390x
This PR aims to address the issue in this [comment](https://github.com/apache/maven/pull/1207#discussion_r1285167844) by removing `Configure deploy` stage from s390x pipeline.
-------------------------------------------------------------
If your pull request is about …
=> [MNG-7848] Remove `Configure deploy` stage from s390x pipeline

api/maven-api-settings/src/main/mdo/settings.mdo, maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsBuilder.java, maven-settings-builder/src/main/java/org/apache/maven/settings/validation/DefaultSettingsValidator.java
JIRA: https://issues.apache.org/jira/browse/MNG-6401
IT PR: https://github.com/apache/maven-integration-testing/pull/275
=> [MNG-6401] Support interpolation of the proxy port in settings.xml

Jenkinsfile.s390x
=> [MNG-7863] don't email on s390 failures. The regular results are enough.

maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java, maven-model-builder/src/test/java/org/apache/maven/model/validation/DefaultModelValidatorTest.java, maven-model-builder/src/test/resources/poms/validation/modelVersion-4_0.xml
Improve DefaultModelValidator.compareModelVersions to be able to compare
versions which different numbers of segments, allowing it to compare
"4", "4.0", and "4.0.0" to each other for example.
Signed-off-by: Craig Andrews <candrews@integralblue.com>
#	maven-model-builder/src/test/java/org/apache/maven/model/validation/DefaultModelValidatorTest.java
Best practice is to use the JIRA issue title in both the pull request title and in the …
=> [MNG-7851] Improve error message when modelVersion is 4.0

maven-core/src/main/resources/META-INF/maven/extension.xml
JIRA: https://issues.apache.org/jira/browse/MNG-7861
See https://github.com/apache/maven/commit/e39142b77a5a140cce50592608029c19b9716ed1#r126188891
=> [MNG-7861] Remove artifacts which should be kept hidden

api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocation.java, api/maven-api-model/src/main/java/org/apache/maven/api/model/InputSource.java, maven-core/src/main/java/org/apache/maven/settings/SettingsUtilsV4.java, maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/test/java/org/apache/maven/model/inheritance/MergerTest.java, src/mdo/merger.vm, src/mdo/model.vm, src/mdo/reader-stax.vm, src/mdo/writer-ex.vm, src/mdo/writer-stax.vm
Location tracking incomplete in Maven 4 and cause missing locations to not appear when running `mvn help:effective-pom -Dverbose`.
This PR adds the missing bits and also add the location tracking from settings to the model.
=> [MNG-7871] Fix location tracking

maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/ArtifactDescriptorReaderDelegate.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/ArtifactDescriptorUtils.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultModelCache.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultModelResolver.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionResolver.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/LocalSnapshotMetadata.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/LocalSnapshotMetadataGenerator.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenMetadata.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenResolverModule.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenSnapshotMetadata.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RelocatedArtifact.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadata.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/RemoteSnapshotMetadataGenerator.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/VersionsMetadata.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/VersionsMetadataGenerator.java
Maven Resolver Provider gets similar change as other Resolver components had in MRESOLVER-386.
Also, some minor code updates like adding Override and other cosmetic stuff.
---
https://issues.apache.org/jira/browse/MNG-7856
=> [MNG-7856] Maven Resolver Provider ctor and other minor code changes

maven-xml-impl/pom.xml
… resolve dependencies for project org.apache.maven:maven-xml-impl
reason:Circular dependencies：
maven-xml-impl
->plexus-xml
->maven-xml-impl
plexus-xml need to exclusion maven-xml-impl
2)rename 'Implementation of Maven API XML' to 'maven-xml-impl(Implementation of Maven API XML)'
be performed on your pull request …
=> Resolve circular dependencies for project org.apache.maven:maven-xml-impl

maven-core/src/test/resources/projects/transform/after.pom, maven-core/src/test/resources/projects/transform/before.pom
=> [MNG-7878] Extend test for ConsumerPom and modules in plugin configuration

maven-repository-metadata/pom.xml, maven-repository-metadata/src/main/java/org/apache/maven/artifact/repository/metadata/io/xpp3/MetadataXpp3Reader.java, maven-repository-metadata/src/main/java/org/apache/maven/artifact/repository/metadata/io/xpp3/MetadataXpp3Writer.java
=> [MNG-7889] Preserve MetadataXpp3Reader/Writer for Maven 3 compatible

maven-core/src/main/java/org/apache/maven/plugin/ClassMap.java, maven-core/src/main/java/org/apache/maven/plugin/IntrospectionException.java, maven-core/src/main/java/org/apache/maven/plugin/MethodMap.java, maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluator.java, maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4.java, maven-core/src/main/java/org/apache/maven/plugin/ReflectionValueExtractor.java, maven-core/src/test/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorTest.java, maven-core/src/test/java/org/apache/maven/plugin/PluginParameterExpressionEvaluatorV4Test.java, maven-core/src/test/java/org/apache/maven/plugin/ReflectionValueExtractorTest.java
Use maven-shared-utils reflection classes.
=> [MNG-7820] Get rid of plexus-utils introspection classes

api/maven-api-core/src/main/java/org/apache/maven/api/services/Source.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectBuilder.java, maven-core/src/main/java/org/apache/maven/project/DefaultModelBuildingListener.java, maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java, maven-core/src/main/java/org/apache/maven/project/ReactorModelPool.java, maven-core/src/test/remote-repo/org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.pom, maven-core/src/test/resources/apiv4-repo/org/codehaus/plexus/plexus-containers/1.0-alpha-16/plexus-containers-1.0-alpha-16.pom, maven-core/src/test/resources/org/apache/maven/extension/test-extension-repo/org/codehaus/plexus/plexus-containers/1.0-alpha-16/plexus-containers-1.0-alpha-16.pom, maven-model-builder/src/main/java/org/apache/maven/model/inheritance/DefaultInheritanceAssembler.java
Those fixes are individual commits and the PR is intended to be rebased rather than squashed.
- Make DefaultInheritanceAssembler#merger field final and reorder fields correctly
- Make DefaultModelBuildingListener#project field final
- Fix bad version in test poms
- Add a o.a.maven.api.services.Source#resolve method
- Simplify ReactorModelPool and use a concurrent map
=> Various minor fixes

api/maven-api-model/src/main/mdo/maven.mdo, maven-core/src/main/java/org/apache/maven/extension/internal/CoreExtensionEntry.java, maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java, maven-core/src/main/java/org/apache/maven/plugin/internal/PluginConfigurationModule.java, maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingHelper.java, maven-embedder/pom.xml, maven-embedder/src/main/java/org/apache/maven/cli/ExtensionConfigurationModule.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java, maven-embedder/src/main/mdo/core-extensions.mdo, src/mdo/model-version.vm
JIRA issue: https://issues.apache.org/jira/browse/MNG-7891
IT PR: https://github.com/apache/maven-integration-testing/pull/296
=> [MNG-7891] Support configuration for extensions

maven-core/pom.xml, maven-core/src/test/resources-project-builder/foo/sub/pom.xml, maven-model-builder/pom.xml, maven-plugin-api/pom.xml, maven-resolver-provider/pom.xml, maven-settings-builder/pom.xml, maven-toolchain-builder/pom.xml, maven-xml-impl/pom.xml, pom.xml
JIRA issue: http://issues.apache.org/jira/browse/MNG-7820
Follow up on #1249, #1250 and #1251
=> [MNG-7820] Get rid of plexus-utils

maven-core/pom.xml, pom.xml
=> [MNG-7896] Upgrade Junit from 5.9.1 to 5.10.0

pom.xml
Note: this PR contains repo entry for staging repository just to make ITs run. That will not be merged, and will be unneeded once resolver 1.9.16 is out in the wild.
---
https://issues.apache.org/jira/browse/MNG-7859
=> [3.9.x] [MNG-7859] Update to Resolver 1.9.16

pom.xml
Note: this PR contains repo entry for staging repository just to make ITs run. That will not be merged, and will be unneeded once resolver 1.9.16 is out in the wild.
---
https://issues.apache.org/jira/browse/MNG-7859
=> [MNG-7859] Update to Resolver 1.9.16

maven-core/src/main/java/org/apache/maven/internal/transformation/ConsumerPomArtifactTransformer.java
- [MNG-7880] Trim down consumer POM
=> [MNG-7880] Trim consumer pom

api/maven-api-model/src/main/mdo/maven.mdo, maven-model-builder/src/main/java/org/apache/maven/model/path/ProfileActivationFilePathInterpolator.java, maven-model-builder/src/main/java/org/apache/maven/model/profile/activation/FileProfileActivator.java, maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java, maven-model-builder/src/test/java/org/apache/maven/model/validation/DefaultModelValidatorTest.java, maven-model-builder/src/test/resources/poms/validation/raw-model/profile-activation-file-with-allowed-expressions.xml, maven-model-builder/src/test/resources/poms/validation/raw-model/profile-activation-file-with-project-expressions.xml
https://issues.apache.org/jira/browse/MNG-7895
ITs - https://github.com/apache/maven-integration-testing/pull/299
---
- x ] Also format the first line of the commit message like `[MNG-XXX] SUMMARY`.
If your pull request is about ~20 lines of code you don't need to sign …
=> [MNG-7895] Support ${project.basedir} in file profile activation

Jenkinsfile.s390x
As discussed on https://github.com/apache/maven/pull/1239, we would like to add `Jenkinsfile.s390x` back and re-enable the s390x pipeline on Jenkins CI (https://ci-maven.apache.org/job/Maven/job/Maven%20Core%20s390x/).  The s390x build will run on `master` branch only with no PR checks so we won't encounter issues with custom IT branch.
@olamy @elharo @gnodet I appreciate your help in reviewing this and getting Jenkins CI setup to use the Jenkinsfile once it's merged.  Thank you!
---
where you replace …
=> [MNG-7848] Add Jenkinsfile.s390x for Jenkins CI on s390x

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
ITs fix: https://github.com/apache/maven-integration-testing/pull/309
--- …
=> [MNG-7898] Missing .mvn directory should not be reported in quiet mode

maven-repository-metadata/pom.xml, maven-repository-metadata/src/main/java/org/apache/maven/artifact/repository/metadata/io/xpp3/MetadataXpp3Reader.java, maven-repository-metadata/src/main/java/org/apache/maven/artifact/repository/metadata/io/xpp3/MetadataXpp3Writer.java
https://issues.apache.org/jira/browse/MNG-7901
---
To make …
=> [MNG-7901] Use MetadataStaxReader/Writer in MetadataXpp3Reader/Writer

.github/workflows/maven.yml, .github/workflows/maven_build_itself.yml, Jenkinsfile, maven-model-builder/src/test/java/org/apache/maven/model/building/BuildModelSourceTransformerTest.java, pom.xml
IT PR at https://github.com/apache/maven-integration-testing/pull/310
=> [MNG-7911] Require JDK 11 and support JDK 21 at build time

api/maven-api-model/src/main/mdo/maven.mdo, maven-model/pom.xml, maven-model/src/test/java/org/apache/maven/model/v4/MavenModelVersionTest.java, src/mdo/model-version.vm
JIRA issue: https://issues.apache.org/jira/browse/MNG-7804
IT PR: https://github.com/apache/maven-integration-testing/pull/268
Note that this introduce a new element in a new 4.1.0 model.
=> [MNG-7804] Ability to order plugin executions using the priority xml element

maven-model/src/test/java/org/apache/maven/model/v4/MavenModelVersionTest.java, src/mdo/model-version.vm
This aims at fixing master UT which have been broken (even though each individual PR was passing ok).
=> [MNG-7804] Fix broken MavenModelVersion generation

maven-embedder/src/main/java/org/apache/maven/cli/ExtensionConfigurationModule.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Follow-up to MNG-7891 to make Maven Daemon integration easier.
=> [MNG-7891] Abstract ExtensionConfigurationModule from CliRequest

Jenkinsfile
=> Reuse the same repository so that ITs can access maven snapshot jars from the repository

maven-settings/pom.xml, maven-settings/src/main/java/org/apache/maven/settings/io/xpp3/SettingsXpp3Reader.java, maven-settings/src/main/java/org/apache/maven/settings/io/xpp3/SettingsXpp3Writer.java
=> [MNG-7904] Use SettingsStaxReader/Writer for SettingsXpp3Reader/Writer

pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7917
Release notes: https://github.com/fusesource/jansi/releases/tag/jansi-2.4.1
=> [MNG-7917] Upgrade to Jansi 2.4.1

maven-core/pom.xml, maven-model-builder/pom.xml, pom.xml
Just a small cleanup on dependencies version...
=> Clean up dependencies versions

maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeBuilder.java, maven-xml-impl/src/test/java/org/apache/maven/internal/xml/XmlNodeBuilderTest.java
Fix XML parsing problem with empty namespace
=> Fix XML parsing problem with empty namespace

api/maven-api-core/pom.xml, api/maven-api-core/src/main/java/org/apache/maven/api/Artifact.java, api/maven-api-core/src/main/java/org/apache/maven/api/ArtifactCoordinate.java, api/maven-api-core/src/main/java/org/apache/maven/api/Exclusion.java, api/maven-api-core/src/main/java/org/apache/maven/api/Node.java, api/maven-api-core/src/main/java/org/apache/maven/api/plugin/Log.java, api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/Component.java, api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/Execute.java, api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/Mojo.java, api/maven-api-core/src/main/java/org/apache/maven/api/plugin/annotations/Parameter.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactInstaller.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/Prompter.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/XmlFactory.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/XmlReaderRequest.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/XmlWriterRequest.java, api/maven-api-meta/pom.xml, api/maven-api-model/pom.xml, api/maven-api-settings/pom.xml, api/maven-api-xml/pom.xml, api/maven-api-xml/src/main/java/org/apache/maven/api/xml/XmlNode.java, api/maven-api-xml/src/main/java/org/apache/maven/api/xml/package-info.java
=> Add some love to the API

Jenkinsfile.s390x
=> Improve build on s390

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
https://issues.apache.org/jira/browse/MNG-7939
https://github.com/apache/maven-integration-testing/pull/320
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) …
=> [MNG-7939] Allow to exclude plugins from validation

maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeBuilder.java
=> Improve exception docs

pom.xml
Use latest resolver.
---
https://issues.apache.org/jira/browse/MNG-7934
=> [MNG-7934] Update to Resolver 1.9.17

pom.xml
https://issues.apache.org/jira/browse/MNG-7942
=> [MNG-7942] Upgrade maven-parent to 41

pom.xml
Use latest resolver.
---
https://issues.apache.org/jira/browse/MNG-7934
=> [MNG-7934] Update to Resolver 1.9.18

maven-core/src/main/resources/META-INF/plexus/default-bindings.xml, maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
- surefire from 3.1.2 to 3.2.2
- dependency from 3.6.0 to 3.6.1
--- …
=> [MNG-7943] Upgrade default plugin bindings

api/maven-api-xml/src/main/java/org/apache/maven/api/xml/XmlNode.java, maven-model/src/test/java/org/apache/maven/model/v4/ModelXmlTest.java, maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeBuilder.java, maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java, maven-xml-impl/src/main/java/org/apache/maven/internal/xml/XmlNodeWriter.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-6036
This provides support for XML namespaces inside the configuration.
=> [MNG-6036] Add namespace to XmlNode

api/maven-api-core/src/main/java/org/apache/maven/api/Type.java, maven-core/src/main/java/org/apache/maven/artifact/handler/manager/DefaultArtifactHandlerManager.java, maven-core/src/main/java/org/apache/maven/internal/aether/TypeRegistryAdapter.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultType.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTypeRegistry.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/BomTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/EarTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/EjbClientTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/EjbTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/JarTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/JavaSourceTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/JavadocTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/MavenPluginTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/ParTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/PomTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/RarTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/TestJarTypeProvider.java, maven-core/src/main/java/org/apache/maven/internal/impl/types/WarTypeProvider.java, maven-core/src/test/java/org/apache/maven/artifact/handler/ArtifactHandlerTest.java
Returns the language property to Type
---
https://issues.apache.org/jira/browse/MNG-7962
=> [MNG-7962] Return language to Type

src/mdo/reader-stax.vm, src/mdo/reader.vm
JIRA issue: https://issues.apache.org/jira/browse/MNG-7965
IT PR: https://github.com/apache/maven-integration-testing/pull/327
=> [MNG-7965] Fix duplicate tags not rejected

maven-slf4j-provider/src/main/java/org/slf4j/impl/MavenSimpleLogger.java, maven-slf4j-provider/src/test/java/org/slf4j/impl/MavenSimpleLoggerTest.java
Regular formatted stack traces do not have a space before the file/line section.
before:
`at java.util.zip.ZipFile$Source.get (ZipFile.java:1426)`
after:
`at java.util.zip.ZipFile$Source.get(ZipFile.java:1426)`
If your pull request is about ~20 lines of code you don't …
=> [MNG-7970] Remove extra space in MavenSimpleLogger stack trace formatter

api/maven-api-core/src/main/java/org/apache/maven/api/Artifact.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifact.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependency.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7971
=> [MNG-7971] Add Artifact#getBaseVersion

api/maven-api-core/src/main/java/org/apache/maven/api/Session.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactCoordinateFactory.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactCoordinateFactoryRequest.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyCoordinateFactoryRequest.java, maven-core/src/main/java/org/apache/maven/internal/impl/AbstractSession.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactCoordinateFactory.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyCoordinateFactory.java
Expose ArtifactCoordinate creation out of standard string.
---
https://issues.apache.org/jira/browse/MNG-7972
=> [MNG-7972] Artifact coordinate out of "standard string"

maven-core/src/main/java/org/apache/maven/internal/impl/DefaultDependencyResolver.java
There was a TODO in code that I missed.
---
https://issues.apache.org/jira/browse/MNG-7974
=> [MNG-7974] Upgrade to Resolver 2.0.0-alpha-5 Addendum

maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/ArtifactDescriptorUtils.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultArtifactDescriptorReader.java
Extra handling if redirection happens within same GAV.
---
https://issues.apache.org/jira/browse/MNG-7959
=> [MNG-7959] User controlled rewrite

api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectManager.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectManager.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7985
=> [MNG-7985] Provide project access to modified resources / test-resources and to the executionProject

maven-model-builder/src/main/java/org/apache/maven/utils/Os.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-7992
=> [MNG-7992] Fix windows identified as dos

maven-core/src/main/java/org/apache/maven/ReactorReader.java
JIRA issue: [MNG-7977](https://issues.apache.org/jira/browse/MNG-7977)
IT PR: https://github.com/apache/maven-integration-testing/pull/329
=> [MNG-7977] Fix reactor reader to not resolve any artifacts from projects being built outside the reactor

maven-artifact/src/test/java/org/apache/maven/artifact/versioning/ComparableVersionTest.java
=> Fixed a typo in ComparableVersionTest.java

maven-core/src/main/java/org/apache/maven/lifecycle/DefaultLifecycleExecutor.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/DefaultLifecycleExecutionPlanCalculator.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/GoalTask.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleExecutionPlanCalculator.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleTask.java, maven-core/src/main/java/org/apache/maven/lifecycle/internal/Task.java, maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorTest.java, maven-core/src/test/java/org/apache/maven/lifecycle/internal/stub/LifecycleExecutionPlanCalculatorStub.java
Just a minor cleanup regarding internals of "tasks".
---
https://issues.apache.org/jira/browse/MNG-7998
=> [MNG-7998] Minor cleanup regarding "tasks"

maven-artifact/src/main/java/org/apache/maven/artifact/DefaultArtifact.java
=> [MNG-8000] DefaultArtifact lacks constructors for version and optional

maven-bom/pom.xml, pom.xml
JIRA issue: https://issues.apache.org/jira/projects/MNG/issues/MNG-8003
=> [MNG-8003] The Maven BOM should have a cleaner parent

maven-model-builder/pom.xml, maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/main/java/org/apache/maven/model/building/ModelCache.java, maven-model-builder/src/main/java/org/apache/maven/model/building/ModelCacheTag.java, maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultModelCache.java
The `ModelCache` is now bloated and can be simplified a lot.
---
https://issues.apache.org/jira/browse/MNG-8016
=> [MNG-8016] Simplify ModelCache

maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
JIRA issue: https://issues.apache.org/jira/browse/MNG-8014
=> [MNG-8014] Workaround for deadlocks in model building

.github/workflows/maven.yml
=> [MNG-8013] Integration testing process logs can be output github artifact

.github/workflows/maven.yml, .github/workflows/maven_build_itself.yml
=> [MNG-8046] Upgrade github action version from v3 to v4

maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
https://issues.apache.org/jira/browse/MNG-8039
=> [MNG-8039] Don't change resolved artifact by DefaultProjectBuilder

apache-maven/src/site/site.xml, api/maven-api-settings/src/main/mdo/settings.mdo, maven-artifact/src/site/site.xml, maven-builder-support/src/site/site.xml, maven-compat/src/site/site.xml, maven-core/src/main/java/org/apache/maven/bridge/MavenRepositorySystem.java, maven-core/src/site/site.xml, maven-embedder/src/site/site.xml, maven-model-builder/src/site/site.xml, maven-model/src/site/site.xml, maven-plugin-api/src/site/site.xml, maven-repository-metadata/src/site/site.xml, maven-resolver-provider/src/site/site.xml, maven-settings-builder/src/site/site.xml, maven-settings/src/site/apt/index.apt, maven-settings/src/site/site.xml, maven-slf4j-provider/src/site/site.xml, src/site/site.xml
cherry pick for Maven 4 of #1395
=> [MNG-8029] improve documentation about mirror settings

pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-8057
=> [MNG-8057] Upgrade Modello to 2.3.0

maven-core/src/main/java/org/apache/maven/internal/aether/PropertyContributorExtender.java
... else, the map seems empty and not dynamically populated.
=> [MNG-8006] Switch property contributors to use a lazy lookup

maven-core/src/main/java/org/apache/maven/lifecycle/mapping/DefaultLifecycleMapping.java
=> [MNG-7976] Investigate MNG-6127 IT instability

.github/workflows/maven.yml, .github/workflows/maven_build_itself.yml, Jenkinsfile, Jenkinsfile.s390x, README.md, pom.xml
However, the vote was not for this PR in particular (code vote), but rather 
a procedural vote.
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
=> [MNG-8061] Maven: Require Java 17

maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java, maven-model-builder/src/test/resources/poms/validation/raw-model/repository-with-basedir-expression.xml
https://issues.apache.org/jira/browse/MNG-8075
---
To make …
=> [MNG-8075] Allow project.baseUri in repository.url

api/maven-api-plugin/src/main/mdo/plugin.mdo, maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java
=> [MNG-4840] document requiredMavenVersion in plugin descriptor

apache-maven/README.txt
Update README.txt in 3.9 branch to mention that Java 8 is required. …
=> [MNG-6399] Lift JDK minimum to JDK 8

maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultTransport.java
See org.apache.maven.internal.impl.DefaultTransportProvider
=> This is NOT a component

api/maven-api-plugin/src/main/mdo/plugin.mdo, maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java, maven-plugin-api/src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptorBuilder.java
fix to #1445 
cherry-picked from 3.9.x #1456 done against #1444
=> [MNG-4840] fix requiredMavenVersion description #1445

maven-model-builder/pom.xml, pom.xml
https://issues.apache.org/jira/browse/MNG-8101
=> [MNG-8101] Upgrade Parent to 42

maven-core/src/main/resources/META-INF/plexus/default-bindings.xml
https://issues.apache.org/jira/browse/MNG-8100
https://github.com/apache/maven-integration-testing/pull/335
=> [MNG-8100] Upgrade default plugin bindings

pom.xml
That contains file locking bugfix.
---
https://issues.apache.org/jira/browse/MNG-8094
=> [MNG-8094] Resolver 1.9.19

maven-api-impl/src/main/java/org/apache/maven/internal/impl/AbstractSession.java, maven-api-impl/src/main/java/org/apache/maven/internal/impl/InternalSession.java, maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java, maven-compat/src/test/java/org/apache/maven/AbstractCoreMavenComponentTestCase.java, maven-compat/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java, maven-compat/src/test/java/org/apache/maven/repository/LegacyRepositorySystemTest.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSession.java, maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSessionFactory.java, maven-core/src/main/java/org/apache/maven/project/ProjectModelResolver.java, maven-core/src/test/java/org/apache/maven/MavenTestHelper.java, maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java, maven-core/src/test/java/org/apache/maven/internal/transformation/AbstractRepositoryTestCase.java, maven-core/src/test/java/org/apache/maven/model/ModelBuilderTest.java, maven-embedder/src/main/java/org/apache/maven/cli/internal/BootstrapCoreExtensionManager.java
This fixes failing tests on master.
=> Fix nasty concurrency issue in AbstractSession

pom.xml
Update resolver to latest.
---
https://issues.apache.org/jira/browse/MNG-8109
=> [3.9.x][MNG-8109] Resolver 1.9.20

maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java, maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
- **Tone down to debug**
- **Fix possible NPE**
- **Fix problem when loading reactors**
=> reactor loading problems

pom.xml
Using latest modello release and putting license
into POM.
---
https://issues.apache.org/jira/browse/MNG-8073
=> [MNG-8073] Adding ASL2 header to XSD files

maven-core/src/main/java/org/apache/maven/plugin/version/internal/DefaultPluginVersionResolver.java
Backport same fix, as very same issue stands there, user cannot really tell what and why is happening.
Maven 3 has only Maven prerequisite, but still same code is present.
This is the backport of https://github.com/apache/maven/pull/1502
---
https://issues.apache.org/jira/browse/MNG-8117
=> [3.9.x][MNG-8117] Backport to Maven 3.9.x

pom.xml
Changes:
* buildhelper-m-p 3.6.0
* logback-classic to 1.2.13
* guava to 33.2.0-jre
---
https://issues.apache.org/jira/browse/MNG-8125
https://issues.apache.org/jira/browse/MNG-8126
https://issues.apache.org/jira/browse/MNG-8127
=> [MNG-8126] Mild updates

.github/workflows/maven.yml, .github/workflows/maven_build_itself.yml
We should control Maven version used for builds
=> Use Maven Wrapper to build

apache-maven/src/main/appended-resources/META-INF/LICENSE.vm, apache-maven/src/main/appended-resources/licenses/EPL-2.0.txt, pom.xml
Update Eclipse Sisu 0.9.0.M3 (carries ASM 9.7).
---
https://issues.apache.org/jira/browse/MNG-8136
=> [3.9.x] [MNG-8136] Update Eclipse Sisu to 0.9.0.M3

apache-maven/src/main/appended-resources/META-INF/LICENSE.vm, apache-maven/src/main/appended-resources/licenses/EPL-2.0.txt, maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java, pom.xml
Update Eclipse Sisu to 0.9.0.M3
---
https://issues.apache.org/jira/browse/MNG-8136
=> [MNG-8136] Update Eclipse Sisu to 0.9.0.M3

pom.xml
Changes:
* commons-cli 1.8.0
* guava 32.2.1-jre
---
https://issues.apache.org/jira/browse/MNG-8144
https://issues.apache.org/jira/browse/MNG-8143
=> [3.9.x] Dependency updates

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginValidationManager.java
(cherry picked from commit dd9679450e00d08caf4f042d92c22acd38585bd5)
=> [MNG-7902] Sort plugins in the validation report (#1510)

maven-core/src/main/resources/META-INF/plexus/default-bindings.xml, maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml
https://issues.apache.org/jira/browse/MNG-8154
=> [MNG-8154] Upgrade default plugin bindings

maven-embedder/src/main/java/org/apache/maven/cli/event/ExecutionEventLogger.java
=> [MNG-8155] Improve not built error message

pom.xml
Upgrade to Resolver 1.9.21
---
https://issues.apache.org/jira/browse/MNG-8175
=> [3.9.x] [MNG-8175] Update Resolver to 1.9.21

pom.xml
Update to [Resolver 1.9.22](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12354902).
---
https://issues.apache.org/jira/browse/MNG-8193
=> [3.9.x][MNG-8193] Update to Resolver 1.9.22

pom.xml
Use latest Hamcrest that is Java 8.
---
https://issues.apache.org/jira/browse/MNG-8199
=> [MNG-8199] Hamcrest 3.0

pom.xml
Update to [Resolver 2.0.1](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12354901), JIRA pending.
---
https://issues.apache.org/jira/browse/MNG-8194
=> [4.0.x][MNG-8194] Update to Resolver 2.0.1

maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
Hence, they missed resolution errors.
---
https://issues.apache.org/jira/browse/MNG-8182
=> [MNG-8182] Resolved errors were created based on collect exceptions

maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java, maven-model-builder/src/test/java/org/apache/maven/model/profile/DefaultProfileInterpolationTest.java, maven-model-builder/src/test/resources/poms/profile/mng8188.xml
Restore of uninterpolated things did "too much", we need to restore activations only.
Maven4 is not affected, manually checked using reproducer.
---
https://issues.apache.org/jira/browse/MNG-8188
=> [MNG-8188] Profile properties are not interpolated

apache-maven/README.txt
This is MR with the aim to port the changes done on https://github.com/apache/maven/pull/1470 over to master branch.
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
---
https://issues.apache.org/jira/browse/MNG-8010
=> [MNG-8010]: Minimize and make generic the README.txt

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
This happens when passing an empty profile or project
=> Fix StringIndexOutOfBoundsException

maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
This was introduced with
https://github.com/eclipse-sisu/sisu.plexus/issues/51.
This leads to exceptions in case of issues with loading potential extensions/plexus components instead of logging just with DEBUG level.
If your pull request is about ~20 lines of code you …
=> [MNG-8228] Enable Sisu Plexus strict classpath scanning

api/maven-api-core/src/main/java/org/apache/maven/api/services/PathSource.java
Possible fix for https://issues.apache.org/jira/browse/MNG-8218
An IT would be interesting to determine if this is the only problem.
=> [MNG-8218] Always normalize Path in PathSource

.asf.yaml
This has been discussed in
https://lists.apache.org/thread/h6z2prghwk69vjfflgvpcs25dry4sggy …
=> Disable automated JIRA comments from GitHub

maven-api-impl/pom.xml, maven-api-impl/src/main/java/org/apache/maven/internal/impl/di/MojoExecutionScope.java, maven-api-impl/src/main/java/org/apache/maven/internal/impl/di/OutOfScopeException.java, maven-api-impl/src/main/java/org/apache/maven/internal/impl/di/SessionScope.java, maven-api-impl/src/test/java/org/apache/maven/internal/impl/standalone/ApiRunner.java, maven-core/src/main/java/org/apache/maven/execution/scope/internal/MojoExecutionScope.java, maven-core/src/main/java/org/apache/maven/execution/scope/internal/MojoExecutionScopeModule.java, maven-core/src/main/java/org/apache/maven/internal/impl/SisuDiBridgeModule.java, maven-core/src/main/java/org/apache/maven/session/scope/internal/SessionScope.java, maven-core/src/test/java/org/apache/maven/di/DiTest.java, maven-core/src/test/java/org/apache/maven/execution/scope/internal/MojoExecutionScopeTest.java, maven-core/src/test/java/org/apache/maven/session/scope/SessionScopeProxyTest.java, maven-di/src/main/java/org/apache/maven/di/Injector.java, maven-di/src/main/java/org/apache/maven/di/Key.java, maven-di/src/main/java/org/apache/maven/di/Scope.java, maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java, maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
... and reuse them for Sisu
IT PR: https://github.com/apache/maven-integration-testing/pull/363
Jira issue: https://issues.apache.org/jira/browse/MNG-8259
=> [MNG-8259] Improve Sisu / DI bridge

apache-maven/src/assembly/shared/run, apache-maven/src/assembly/shared/run.cmd
JIRA issue: https://issues.apache.org/jira/browse/MNG-8260
=> [MNG-8260] Fix warning on latest JDK 24.ea

maven-api-impl/src/main/java/org/apache/maven/internal/impl/DefaultModelXmlFactory.java
=> Simple typo bugfix (NPE)

maven-api-impl/src/main/java/org/apache/maven/internal/impl/model/DefaultModelBuilder.java
Try disabling parallelism to see if that changes IT stability
=> Disable parallelism

src/mdo/reader-stax.vm
[JIRA issue MNG-8278](https://issues.apache.org/jira/browse/MNG-8278)
=> [MNG-8278] Improve speed in stax readers

maven-api-impl/src/main/java/org/apache/maven/internal/impl/util/PhasingExecutor.java
- **Fix**
- **Refactor using a lock**
=> Fix phaser

maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/DefaultMavenInvoker.java
Parser must not (esp "partially") alter global state like setting Java System Properties. If invoker wants, invoker can set those (and cleanup).
---
https://issues.apache.org/jira/browse/MNG-8283
=> [MNG-8283] Parser must not alter global state

maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/BaseMavenParser.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/DefaultMavenParser.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/forked/DefaultForkedMavenParser.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/resident/DefaultResidentMavenInvoker.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/DefaultEncryptParser.java
And move all logic out of invoke. Also, parser and other improvements, mostly adding "extension points" in form of overridable protected method.
---
https://issues.apache.org/jira/browse/MNG-8283
=> [MNG-8283] Make resident able to restore state

maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnenc/CommonsCliEncryptOptions.java
Help output: https://gist.github.com/cstamas/c63354848c54df7ae53ed6b56a0c21be
=> Minor fixes: proper help syntax and ability to extend core exports

maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTypeRegistry.java
JIRA issue: [MNG-8296](https://issues.apache.org/jira/browse/MNG-8296)
=> [MNG-8296] Support creating unknown Language on the fly

apache-maven/src/bin/mvn.cmd
fixes https://issues.apache.org/jira/browse/MNG-8315
To …
=> [MNG-8315] Failure of mvn.cmd if a .mvn folder is located at drive root

maven-api-impl/src/main/resources/org/apache/maven/model/pom-4.0.0.xml, maven-api-impl/src/main/resources/org/apache/maven/model/pom-4.1.0.xml, maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java, maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml, maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.1.0.xml
IT PR: https://github.com/apache/maven-integration-testing/pull/392
-----
The Maven used the own inception year 2001.
But the Gradle already use the 1 Feb 1980 for preserveFileTimestamps.
The 1 Jan 1980 is a minimal date in Zip archive but the 1 Jan has some special treatment by Java that's why the Gradle team used the 1 Feb.
See more detailed description in CONSTANT_TIME_FOR_ZIP_ENTRIES https://github.com/gradle/gradle/blob/master/platforms/core-runtime/files/src/main/java/org/gradle/api/internal/file/archive/ZipEntryConstants.java#L39
The change was first proposed in the https://github.com/apache/maven/pull/1726#issuecomment-2376407039 and also slightly discussed in the MSHARED-1430
> @hboutemy:
> many people have many opinions: there are even more opinions than people
> The default …
=> [MNG-8258] Change the fixed reproducible build outputTimestamp to 1 Feb 1980

maven-api-impl/pom.xml, pom.xml
Changes:
* fix typo, assertj is not compile dependency
* exclude error_prone_annos that come in via gson in Resolver SPI (RFC 9457)
=> Sort out dependency issues

apache-maven/pom.xml
Make them reside within apache-maven artifactId.
=> Fix BOMs location

maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java, maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/CommonsCliMavenOptions.java
Fixing the 3 new script params.
---
https://issues.apache.org/jira/browse/MNG-8335
=> [MNG-8335] The mvnenc command is busted

apache-maven/pom.xml
Make the usable with xinclude (properties).
Depends on https://github.com/maveniverse/bom-builder-maven-plugin/pull/8
=> Tidy up generated BOMs

maven-embedder/src/main/java/org/apache/maven/cli/transfer/ConsoleMavenTransferListener.java
JIRA issue: [MNG-8339](https://issues.apache.org/jira/browse/MNG-8339)
=> [MNG-8339] An error during transfer output seems to freeze the output

api/maven-api-core/src/main/java/org/apache/maven/api/Constants.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/MessageBuilder.java, maven-jline/src/main/java/org/apache/maven/jline/JLineMessageBuilderFactory.java, src/site/markdown/configuration.md
JIRA issues: [MNG-8361](https://issues.apache.org/jira/browse/MNG-8361) and [MNG-8300](https://issues.apache.org/jira/browse/MNG-8300)
- **[MNG-8361] Document color styles properly**
- **[MNG-8300] Revert to bright-black to restore transfer colors**
=> [MNG-8361][MNG-8300] Fix color styles"

impl/maven-cli/pom.xml, impl/maven-core/pom.xml, impl/maven-di/pom.xml, impl/maven-impl/pom.xml, impl/maven-jline/pom.xml, impl/maven-logging/pom.xml, impl/maven-xml/pom.xml, impl/pom.xml
No issue, just make subprojects better named.
=> Better subproject names

api/maven-api-core/src/main/java/org/apache/maven/api/Session.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactDeployer.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactDeployerRequest.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactInstaller.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactInstallerRequest.java, impl/maven-impl/src/main/java/org/apache/maven/internal/impl/AbstractSession.java, impl/maven-impl/src/main/java/org/apache/maven/internal/impl/DefaultArtifactDeployer.java, impl/maven-impl/src/main/java/org/apache/maven/internal/impl/InternalSession.java
JIRA issue: [MNG-8329](https://issues.apache.org/jira/browse/MNG-8329)
=> [MNG-8329] ArtifactInstallerRequest and ArtifactDeployerRequest should use Collection<ProducedArtifact>

pom.xml
Once it is out, just to not be forgotten.
=> Drop staging repository for Resolver 2.0.3

its/core-it-support/core-it-plugins/maven-it-plugin-ant-based/pom.xml
Dependabot missed that it needs several deps updated at once.
=> IT: Ant update

api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvn/forked/ForkedMavenInvoker.java, api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvn/local/LocalMavenInvoker.java, api/maven-api-cli/src/main/java/org/apache/maven/api/cli/mvn/resident/ResidentMavenInvoker.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/forked/DefaultForkedMavenParser.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/local/DefaultLocalMavenInvoker.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/resident/DefaultResidentMavenInvoker.java
=> CLIng: finish TODO

its/core-it-support/core-it-plugins/maven-it-plugin-site/pom.xml, its/core-it-support/core-it-plugins/maven-it-plugin-site/src/main/java/org/apache/maven/plugin/coreit/GenerateMojo.java
Attempt to stop ITs pulling in ancient (and vulnerable) deps.
=> IT fix: Drop ancient reporting, use latest

impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java, its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8336UnknownPackagingTest.java, its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, its/core-it-suite/src/test/resources/mng-8336-unknown-packaging/pom.xml, its/core-it-suite/src/test/resources/mng-8336-unknown-packaging/src/main/java/io/github/danthe1st/mavenrepro/MavenRepro.java
JIRA issue: [MNG-8336](https://issues.apache.org/jira/browse/MNG-8336)
=> [MNG-8336] Only inject plugins information if requested

impl/maven-core/src/main/java/org/apache/maven/RepositoryUtils.java, impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
JIRA issue: [MNG-8384](https://issues.apache.org/jira/browse/MNG-8384)
This fixes CXF build on Maven 4.
=> [MNG-8384] Make sure plugin's artifacts have a scope

impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/ContainerCapsule.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsule.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/resident/ResidentMavenInvoker.java
As part of capsule creation, capsule logging setup happened as well but it got "stuck" on very first invocation and never updated.
=> CLIng+resident: logging subsystem still needs an update

.github/workflows/maven.yml, its/core-it-suite/pom.xml, its/core-it-support/maven-it-helper/pom.xml, pom.xml
Changes:
* remove unneeded POM cruft
* remove embedded profile (is default) introduce forked profile
* CI: drop "embedded" profile use
=> IT: Streamline ITs more

impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java, impl/maven-core/src/main/java/org/apache/maven/lifecycle/providers/packaging/AbstractLifecycleMappingProvider.java
All the plugins referenced by Maven Core.
---
https://issues.apache.org/jira/browse/MNG-8463
=> [MNG-8463] Update plugins

impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelCache.java
=> Just some details i spotted during debug

pom.xml
This allows using externalized secret values in Maven settings and supports 1Password CLI as master source
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if …
=> [MNG-8555] Use plexus-sec-dispatcher 4.1.0

pom.xml
Update Resolver to 2.0.6.
---
https://issues.apache.org/jira/browse/MNG-8553
=> [MNG-8553] Resolver 2.0.6

impl/maven-core/src/main/java/org/apache/maven/execution/ActivationSettings.java, impl/maven-core/src/main/java/org/apache/maven/execution/DefaultBuildResumptionDataRepository.java, impl/maven-core/src/main/java/org/apache/maven/execution/ProfileActivation.java, impl/maven-core/src/main/java/org/apache/maven/execution/ProjectActivation.java, impl/maven-core/src/main/java/org/apache/maven/graph/DefaultGraphBuilder.java, impl/maven-core/src/main/java/org/apache/maven/graph/ProjectSelector.java, impl/maven-core/src/test/java/org/apache/maven/graph/DefaultGraphBuilderTest.java
JIRA issue: [MNG-8567](https://issues.apache.org/jira/browse/MNG-8567)
=> [MNG-8567] Fix resumption to not recurse into subprojects

api/maven-api-metadata/pom.xml, api/maven-api-plugin/pom.xml, api/maven-api-toolchain/pom.xml, compat/maven-artifact/pom.xml, compat/maven-builder-support/pom.xml, compat/maven-compat/pom.xml, compat/maven-embedder/pom.xml, compat/maven-model-builder/pom.xml, compat/maven-model/pom.xml, compat/maven-plugin-api/pom.xml, compat/maven-repository-metadata/pom.xml, compat/maven-resolver-provider/pom.xml, compat/maven-settings-builder/pom.xml, compat/maven-settings/pom.xml, compat/maven-toolchain-builder/pom.xml, compat/maven-toolchain-model/pom.xml, impl/maven-cli/pom.xml, impl/maven-core/pom.xml, impl/maven-di/pom.xml, impl/maven-executor/pom.xml, impl/maven-impl/pom.xml, impl/maven-jline/pom.xml, impl/maven-logging/pom.xml, impl/maven-xml/pom.xml
And some other minor formatting cleanup.
---
https://issues.apache.org/jira/browse/MNG-8577
=> [MNG-8577] Project POM hierarchy

impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java, impl/maven-core/src/main/java/org/apache/maven/logging/LoggingOutputStream.java
This bug was introduced during CLIng dev, when a
wrong force flush was added to flush body.
---
https://issues.apache.org/jira/browse/MNG-8579
=> [MNG-8579] StdOut/StdErr printstream bug

.github/workflows/pr-automation.yml
https://github.com/apache/maven-gh-actions-shared?tab=readme-ov-file#pull-request-automation
=> Add PR Automation action

impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
To have deployed POMs comply with https://central.sonatype.org/publish/requirements/
---
https://issues.apache.org/jira/browse/MNG-8580
=> [MNG-8580] Keep devs/contributors

compat/maven-resolver-provider/pom.xml
We create additional JAR that is very same to main JAR but has sisu index present.
---
https://issues.apache.org/jira/browse/MNG-8592
=> [MNG-8592] Package Sisu enabled JAR separately

pom.xml
JIRA issue: [MNG-8599](https://issues.apache.org/jira/browse/MNG-8599)
This helps debugging and reuse of those files.
=> [MNG-8599] Generated source files should be included in the sources jars

pom.xml
Update from 2.0.6.
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12355612
---
https://issues.apache.org/jira/browse/MNG-8593
=> [MNG-8593] Bump to Resolver 2.0.7

api/maven-api-core/src/main/java/org/apache/maven/api/Type.java, impl/maven-impl/src/main/java/org/apache/maven/impl/resolver/type/DefaultTypeProvider.java
Similar to java-source type, but for tests sources.
---
https://issues.apache.org/jira/browse/MNG-8601
=> [MNG-8601] Add type test-java-source type

impl/maven-impl/src/main/java/org/apache/maven/impl/cache/DefaultRequestCache.java, impl/maven-impl/src/main/java/org/apache/maven/impl/cache/SoftIdentityMap.java, impl/maven-impl/src/test/java/org/apache/maven/impl/cache/SoftIdentityMapTest.java
JIRA issue: [MNG-8604](https://issues.apache.org/jira/browse/MNG-8604)
null
=> [MNG-8604] Use soft references for cache

.github/workflows/maven.yml, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuilder.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuildingRequest.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuildingResult.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuilder.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuildingException.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuildingRequest.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuildingResult.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/io/ToolchainsReader.java, compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/io/ToolchainsWriter.java
JIRA issue: [MNG-8611](https://issues.apache.org/jira/browse/MNG-8611)
=> [MNG-8611] Build with apache-release profile

api/maven-api-core/src/main/java/org/apache/maven/api/Dependency.java, api/maven-api-core/src/main/java/org/apache/maven/api/DependencyCoordinates.java, api/maven-api-core/src/main/java/org/apache/maven/api/Node.java, api/maven-api-core/src/main/java/org/apache/maven/api/package-info.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverResult.java
JIRA issue: [MNG-8613](https://issues.apache.org/jira/browse/MNG-8613)
Documentation only changes.
=> [MNG-8613] Copy edit dependency javadocs

src/graph/ReactorGraph.java
Assign correct link prefixes for impl and compat
To make …
=> [MNG-8620] Fix links in SVG

its/pom.xml
This should fix ITs being broken in PRs
=> Fix ITs referencing rc-3-SNAPSHOT

src/mdo/reader-stax.vm
JIRA issue: [MNG-8633](https://issues.apache.org/jira/browse/MNG-8633)
Make the entities map lazily initialised and move its definition to the end of the source file.
=> [MNG-8633] Initialize entities map lazily

impl/maven-core/src/main/resources/META-INF/maven/extension.xml, impl/maven-core/src/test/resources/projects/future-model-version-pom.xml, impl/maven-core/src/test/resources/projects/future-schema-model-version-pom.xml, impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java, impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java, impl/maven-support/pom.xml, impl/maven-support/src/test/java/org/apache/maven/model/v4/MavenStaxReaderTest.java, its/core-it-suite/src/test/resources/mng-7982-transitive-dependency-management/b/pom.xml, its/core-it-suite/src/test/resources/mng-7982-transitive-dependency-management/c/pom.xml, its/core-it-suite/src/test/resources/mng-7982-transitive-dependency-management/d/pom.xml, its/core-it-suite/src/test/resources/mng-7982-transitive-dependency-management/e/pom.xml, its/core-it-suite/src/test/resources/mng-7982-transitive-dependency-management/pom.xml, its/core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-project-props/child/pom.xml, its/core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-project-props/pom.xml, its/core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-user-props/child/pom.xml, its/core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-user-props/pom.xml, its/core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/exp-in-artifactid/pom.xml, its/core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/exp-in-groupid/pom.xml, src/mdo/common.vm, src/mdo/reader-stax.vm
JIRA issue: [MNG-8639](https://issues.apache.org/jira/browse/MNG-8639)
* validate namespace consistency in XML
* make sure a valid namespace is used for modelVersion > 4.0.0
=> [MNG-8639] Check namespaces when reading XML models

api/maven-api-core/src/main/java/org/apache/maven/api/Node.java, api/maven-api-core/src/main/java/org/apache/maven/api/Version.java, api/maven-api-core/src/main/java/org/apache/maven/api/VersionConstraint.java, api/maven-api-core/src/main/java/org/apache/maven/api/VersionRange.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactCoordinatesFactory.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactCoordinatesFactoryRequest.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyCoordinatesFactoryRequest.java, impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectManager.java, impl/maven-impl/src/main/java/org/apache/maven/impl/AbstractNode.java, impl/maven-impl/src/main/java/org/apache/maven/impl/AbstractSession.java, impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelVersionParser.java, impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultNode.java, impl/maven-impl/src/main/java/org/apache/maven/impl/resolver/DefaultModelResolver.java, impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelVersionParserTest.java, impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultNodeTest.java
JIRA issue: [MNG-8612](https://issues.apache.org/jira/browse/MNG-8612)
Supersedes #2149
=> [MNG-8612] Document Node#asString and remove Version#asString and VersionConstraint#asString

impl/maven-core/src/main/java/org/apache/maven/internal/impl/CoreUtils.java, impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultArtifactManager.java, impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProject.java, impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultProjectManager.java, impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultSession.java, impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTypeRegistry.java
Let's see if this breaks anything....
=> requireNonNull

compat/maven-compat/src/main/java/org/apache/maven/project/artifact/MavenMetadataSource.java, compat/maven-compat/src/test/java/org/apache/maven/artifact/resolver/ArtifactResolverTest.java, compat/maven-model/src/test/java/org/apache/maven/model/BuildTest.java, compat/maven-model/src/test/java/org/apache/maven/model/IssueManagementTest.java, compat/maven-model/src/test/java/org/apache/maven/model/LicenseTest.java, compat/maven-model/src/test/java/org/apache/maven/model/MailingListTest.java, compat/maven-model/src/test/java/org/apache/maven/model/OrganizationTest.java, compat/maven-model/src/test/java/org/apache/maven/model/ScmTest.java, impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java, impl/maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
Presumably these were all accidentally disabled but let's see what shape they're in. Not great. Some exception messages seem less precise than they used to be, and there appears to be at least one actual bug these tests would have caught.
=> Reenable many old style tests

compat/maven-embedder/src/test/java/org/apache/maven/cli/props/MavenPropertiesTest.java, impl/maven-core/src/test/java/org/apache/maven/internal/impl/DefaultChecksumAlgorithmServiceTest.java, impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java, impl/maven-core/src/test/java/org/apache/maven/session/scope/SessionScopeProxyTest.java, impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelInterpolatorTest.java
small improvement in failure messages
=> Expected argument comes first in JUnit

impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanExecutor.java, its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8648ProjectStartedEventsTest.java, its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, its/core-it-suite/src/test/resources/mng-8648/extension/pom.xml, its/core-it-suite/src/test/resources/mng-8648/extension/src/main/java/org/apache/maven/its/mng8648/ProjectEventSpy.java, its/core-it-suite/src/test/resources/mng-8648/extension/src/main/resources/META-INF/plexus/components.xml, its/core-it-suite/src/test/resources/mng-8648/project/.mvn/extensions.xml, its/core-it-suite/src/test/resources/mng-8648/project/pom.xml, its/core-it-suite/src/test/resources/mng-8648/project/subproject-a/pom.xml, its/core-it-suite/src/test/resources/mng-8648/project/subproject-b/pom.xml
JIRA issue: [MNG-8648](https://issues.apache.org/jira/browse/MNG-8648) …
=> [MNG-8648] Concurrent executor fires wrong ProjectStarted event

.github/ci-extensions.xml
https://github.com/maveniverse/mimir/releases/tag/release-0.4.1
=> Bump Mimir from 0.4.0 to 0.4.1

its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3558PropertyEscapingTest.java, its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, its/core-it-suite/src/test/resources/mng-3558-property-escaping/pom.xml
JIRA issue: [MNG-3558](https://issues.apache.org/jira/browse/MNG-3558)
=> [MNG-3558] Ensure properties can be escaped

impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
Source hint should tell what it is: GAV? GATC? Anything else? Especially the GAV and GATC are prone to be mixed by humans when trying to decipher error message.
This PR does NOT modify (improve) error output, but it prepares us to do so.
=> [MRESOLVER-673] Improve model validator error messages

impl/maven-impl/src/main/java/org/apache/maven/impl/resolver/type/DefaultTypeProvider.java
Fix https://github.com/apache/maven-compiler-plugin/issues/323
=> Add types for processor annotation path

api/maven-api-model/src/main/mdo/maven.mdo, src/mdo/model.vm
JIRA issue: [MNG-8675](https://issues.apache.org/jira/browse/MNG-8675)
=> [MNG-8675] Correctly deprecate Resource in the model

.github/ci-extensions.xml, apache-maven/pom.xml, impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MavenInvokerTest.java, impl/maven-executor/src/main/java/org/apache/maven/cling/executor/internal/ToolboxTool.java, impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MavenExecutorTestSupport.java, its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8400CanonicalMavenHomeTest.java
Changes:
* mimir 0.5.0
* bom-builder 1.0.4
* toolbox 0.7.4
=> Update Maveniverse stuff

api/maven-api-model/src/main/mdo/maven.mdo
Maven 4 cherry pick of #2279 done in Maven 3.9.x
=> [MNG-8712] dependency version is a requirement, not effective

maven-core/src/main/resources/META-INF/plexus/default-bindings.xml, maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorTest.java
https://issues.apache.org/jira/browse/MNG-8717
=> [MNG-8717] Remove maven-plugin-plugin:addPluginArtifactMetadata from default binding

apache-maven/src/bin/mvn
https://issues.apache.org/jira/browse/MNG-8169
=> [MNG-8169] Add opens java.base/java.lang=ALL-UNNAMED for MinGW

pom.xml
=> [MNG-8716] Bump resolver to 1.9.23

compat/maven-compat/src/test/java/org/apache/maven/repository/legacy/DefaultWagonManagerTest.java, compat/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java, impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultLifecycleBindingsInjector.java, impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
- https://docs.openrewrite.org/recipes/staticanalysis/removeunusedprivatemethods
- https://github.com/checkstyle/checkstyle/issues/16960
- https://github.com/checkstyle/checkstyle/pull/16894
=> RemoveUnusedPrivateMethods

apache-maven/src/test/resources/maven-configuration.md.vm, pom.xml, src/site/markdown/configuration.properties, src/site/markdown/configuration.yaml, src/site/markdown/maven-configuration.md
Bump Resolver from 2.0.8 to 2.0.9
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12320628&version=12355847
---
https://issues.apache.org/jira/browse/MNG-8732
=> [MNG-8732] Bump Resolver to 2.0.9

maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java, maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginDescriptorCache.java, maven-core/src/main/java/org/apache/maven/project/artifact/DefaultProjectArtifactsCache.java
(cherry picked from commit ce151933949ab39eca78b8374531d39bc8c76b0f) with simple conflict resolving
references:
- https://issues.apache.org/jira/browse/MNG-8711
- https://github.com/apache/maven/pull/1425
=> [MNG-8711] Fix concurrent cache access

compat/maven-compat/src/main/java/org/apache/maven/toolchain/ToolchainManagerFactory.java, impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultJavaToolchainFactory.java
https://issues.apache.org/jira/browse/MNG-8759
=> [MNG-8759] Restore toString method in DefaultJavaToolchain

src/site/site.xml
https://issues.apache.org/jira/browse/MNG-8763
=> [MNG-8763] Remove name from site bannerLeft

its/core-it-support/core-it-plugins/maven-it-plugin-context-passing/src/main/java/org/apache/maven/plugin/coreit/CatchMojo.java
isolate error due to flaky CI. @elharo 
- https://github.com/apache/maven/pull/2401
- https://github.com/apache/maven/pull/2401#issuecomment-2927681965
=> use `try-with-resources` statement in `CatchMojo`

.github/ci-extensions.xml, impl/maven-cli/pom.xml, impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvn/MimirInfuser.java, impl/maven-cli/src/test/resources-filtered/ut-mimir.properties, impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MimirInfuser.java, impl/maven-executor/src/test/resources-filtered/ut-mimir.properties
And set up them properly to use outer daemon.
Release notes:
https://github.com/maveniverse/mimir/releases/tag/release-0.7.8
=> Update Mimir to 0.7.8

CONTRIBUTING.md
(cherry picked from commit 761a56b3ca5429bdb450d9356511049418d54a65)
=> Update CONTRIBUTING after GitHub issues enabled

.github/workflows/maven.yml
now we have disable action on branch ....
=> Execute GitHub action - Java CI on maven-4.0.x branch

impl/maven-core/src/main/java/org/apache/maven/ReactorReader.java
- [Fix ReactorReader incorrect warnings and logic (fixes #2497, #2498)](https://github.com/apache/maven/pull/2498)
=> [maven-4.0.x] Fix ReactorReader incorrect warnings and logic (fixes #2497, #2498)

pom.xml
- **cleanups duplicate configs with new parent**
=> Cleanups duplicate configs with new parent

.github/workflows/maven.yml, Jenkinsfile, maven-core/src/test/java/org/apache/maven/graph/DefaultProjectDependencyGraphTest.java
- Spotless is executed only on JDK 11+
- We have ITs executing on JDK 8
=> Build the project by JDK 21 as default

impl/maven-testing/src/main/java/org/apache/maven/api/di/testing/MavenDIExtension.java, impl/maven-testing/src/test/java/org/apache/maven/api/di/testing/SimpleDITest.java
Fixes #10428
=========
- [X ] Your pull request should address just one issue, without pulling in other changes.
- [ X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ X] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
- [ X] Run `mvn verify` to make sure basic checks pass.
If your pull request …
=> Refactor setupContainer to validate ExtensionContext, test class and instance, and throw clear IllegalStateExceptions (fixes #10428)

impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java, impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultSourceRootTest.java
The language was wrongly put in place of the module name. This commit also adds a test case.
=> Bug fix in the default directory computed by `DefaultSourceRoot`.

impl/maven-xml/BENCHMARKS.md, impl/maven-xml/pom.xml, impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlPlexusConfiguration.java, impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationBenchmark.java, impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationConcurrencyBenchmark.java, impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationMemoryBenchmark.java, impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationOld.java, impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationTest.java
This PR significantly optimizes the `XmlPlexusConfiguration` class by addressing both performance bottlenecks and thread safety issues. The changes provide substantial improvements in memory usage, processing speed, and concurrent safety while maintaining 100% backward compatibility.
- **Before**: Constructor performed expensive deep copying of the entire XML tree
- **After**: Wraps the `XmlNode` directly, sharing the underlying structure
- **Impact**: Dramatically reduces object allocation and memory usage
- **Before**: All child configurations were created upfront during construction
- **After**: Child configurations are created only when accessed
- **Impact**: Faster initialization and reduced memory footprint for unused branches
- **Before**: Each configuration maintained its own copy …
=> Optimize XmlPlexusConfiguration for performance and thread safety

impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MavenExecutorTestSupport.java
(cherry picked from commit 0a289125da08b0c2313e9f07ca96b3755a7f6bbd)
- #10907
=> Use local repository as tail in MavenExecutorTest

compat/maven-model/pom.xml, impl/maven-impl/pom.xml, impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java, impl/maven-impl/src/test/java/org/apache/maven/impl/model/ModelValidationBenchmark.java, impl/maven-xml/pom.xml, pom.xml
This PR optimizes Maven validation performance by implementing lazy evaluation of `SourceHint` computations throughout `DefaultModelValidator`, eliminating expensive string formatting when validation passes.
As identified in [PR #2483](https://github.com/apache/maven/pull/2483#issuecomment-3007923313), there are significant performance issues with validation:
- `SourceHint.dependencyManagementKey()` called dozens of times per dependency
- Expensive string concatenation performed even when validation succeeds
- Results rarely used since most validations pass
- Performance degrades significantly with large projects
Implement **comprehensive lazy evaluation** by replacing `SourceHint` with `Supplier<String>` throughout the validation system. SourceHint strings are only computed when …
=> Optimize validation performance with lazy SourceHint evaluation

impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java, impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelValidatorTest.java
Port https://github.com/apache/maven/pull/10899 to master, using `Session.getMavenVersion()` instead of reading the properties file.
- **Modified `validateModelVersion()` method** to accept `Session` parameter and include Maven version in error messages
- **Updated error messages** to be single-line and consistent with Maven's error message style  
- **Enhanced error messages** now show which Maven version is rejecting the model version
- **Added test coverage** to verify Maven version is included in error messages
**Before:**
```
modelVersion of '99.0.0' is newer than the versions supported by this version of Maven: [4.0.0, 4.1.0]. Building this project requires a newer version of Maven.
```
**After:**
```
modelVersion of '99.0.0' is newer than the versions supported by this Maven …
```
=> Add Maven version to error message when rejecting model versions

impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
- **Port the bug fixes identified when using that class in Maven clean and compiler plugin.**
- **Apply corrections for comments posted on the pull request.**
- **Rename fs -> fileSystem**
=> Port the bug fixes identified when using that class in Maven clean and compiler plugin

impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java, impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelValidatorTest.java
=> Make error message less awkward

impl/maven-core/src/main/java/org/apache/maven/plugin/prefix/internal/DefaultPluginPrefixResolver.java
Simplify prefix resolution and drop use of BuildPluginManager (as descriptor will be re-resolved again later) and focus only on prefix to GA resolution, using a map of rules:
* collect POM enlisted plugin groupId:artifactId pairs that come from non-settings-enlisted groupIDs (and allow only enlisted artifactIDs)
* add settings enlisted plugin groupIds (keep their order) but "allow any" artifactId
Using this map, figure out plugin GA from prefix using Maven metadata only.
Fixes #11067
Backport of 2b7bb9c6fdb7b4bedc9b1c0581c70dc5b5a19671
=> Simplify prefix resolution (#11072)

impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactCoordinates.java, impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultArtifactCoordinatesTest.java
Also add hash regression test
- [X ] Your pull request should address just one issue, without pulling in other changes.
- [ X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ X] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
- [X ] Run `mvn verify` to make sure basic checks pass.
If your pull …
=> fix: include extension in equals/hashCode of DefaultArtifactCoordinates

compat/maven-compat/src/main/java/org/apache/maven/project/artifact/MavenMetadataSource.java, impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnup/goals/CompatibilityFixStrategy.java, impl/maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java, impl/maven-testing/src/main/java/org/apache/maven/api/plugin/testing/MojoExtension.java, impl/maven-xml/src/main/java/org/apache/maven/internal/xml/DefaultXmlService.java, its/core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/Verifier.java
Inspired from:
Whats good for check performance could be beneficial to maven as well.
- https://github.com/checkstyle/checkstyle/pull/17782
- https://github.com/apache/maven-parent/pull/496
- https://error-prone.picnic.tech/refasterrules/StreamRules/
- https://docs.openrewrite.org/recipes/tech/picnic/errorprone/refasterrules/streamrulesrecipes
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
=> Apply `StreamRulesRecipes`

api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactDeployerException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactInstallerException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ArtifactResolverException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ChecksumAlgorithmServiceException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/DependencyResolverException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/InterpolatorException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/LookupException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/MavenException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilderException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectBuilderException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/PrompterException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/SettingsBuilderException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/SuperPomProviderException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainManagerException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/ToolchainsBuilderException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/TransportProviderException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionParserException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionRangeResolverException.java, api/maven-api-core/src/main/java/org/apache/maven/api/services/VersionResolverException.java, impl/maven-impl/src/main/java/org/apache/maven/impl/model/reflection/IntrospectionException.java, impl/maven-impl/src/main/java/org/apache/maven/impl/model/reflection/MethodMap.java, impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
Removing serialVersionUID (excluding …
=> 10155 - Removing all serialVersionUID
